# Domainrouting

## Domainoverview

In [1]:
import pandas as pd

# TSV einlesen (so ähnlich machst du es ja schon)
df = pd.read_csv(
    "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv",
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 1) Alle Subjects in einzelne Domains aufsplitten
domains_series = (
    df["subjects"]
    .dropna()                     # NaNs raus
    .astype(str)                  # zur Sicherheit als String
    .str.split(",")               # in Listen splitten
    .explode()                    # jede Domain in eigene Zeile
    .str.strip()                  # Whitespace trimmen
)

# 2) Einzigartige Domains (alphabetisch sortiert)
unique_domains = sorted(domains_series.unique())
print("Einzigartige Domains:")
for d in unique_domains:
    print("-", d)

# 3) Häufigkeiten pro einzelner Domain
domain_counts = domains_series.value_counts().sort_index()
print("\nHäufigkeiten pro Domain:")
print(domain_counts)

Einzigartige Domains:
- 10-news-tampa-bay
- Alcohol
- abc-news-week
- abortion
- afghanistan
- after-the-fact
- agriculture
- animals
- autism
- bankruptcy
- baseball
- bipartisanship
- bush-administration
- campaign-advertising
- campaign-finance
- candidates-biography
- cap-and-trade
- census
- children
- china
- city-budget
- city-government
- civil-rights
- climate-change
- colbert-report
- congress
- congressional-rules
- consumer-safety
- corporations
- corrections-and-updates
- county-budget
- county-government
- crime
- criminal-justice
- death-penalty
- debates
- debt
- deficit
- disability
- diversity
- drugs
- ebola
- economy
- education
- elections
- energy
- environment
- ethics
- fake-news
- families
- federal-budget
- financial-regulation
- fires
- florida
- florida-amendments
- food
- food-safety
- foreign-policy
- gambling
- gas-prices
- gays-and-lesbians
- government-efficiency
- government-regulation
- guns
- health-care
- history
- homeland-security
- homeless
- housing
- human-rights
- hunger
- immigration
- income
- infrastructure
- iraq
- islam
- israel
- job-accomplishments
- jobs
- kagan-nomination
- labor
- legal-issues
- lottery
- marijuana
- market-regulation
- marriage
- medicaid
- medicare
- message-machine
- message-machine-2012
- message-machine-2014
- military
- natural-disasters
- new-hampshire-2012
- nuclear
- obama-birth-certificate
- occupy-wall-street
- oil-spill
- patriotism
- pensions
- polls
- pop-culture
- population
- poverty
- privacy
- public-health
- public-safety
- public-service
- pundits
- recreation
- redistricting
- religion
- retirement
- science
- sexuality
- small-business
- social-security
- sotomayor-nomination
- space
- sports
- state-budget
- state-finances
- states
- stimulus
- supreme-court
- taxes
- technology
- terrorism
- tourism
- trade
- transparency
- transportation
- unions
- urban
- veterans
- voting-record
- water
- wealth
- weather
- welfare
- women
- workers

Häufigkeiten pro Domain:
subjects
10-news-tampa-bay      5
Alcohol               35
abc-news-week         89
abortion             254
afghanistan           50
                    ...
wealth                58
weather               36
welfare               55
women                215
workers              293
Name: count, Length: 142, dtype: int64

## 8 Superlabels

In [1]:
domain_to_super_8 = {
    # ----- 1. economy -----
    "Alcohol": "economy",
    "agriculture": "economy",
    "bankruptcy": "economy",
    "corporations": "economy",
    "consumer-safety": "economy",
    "debt": "economy",
    "deficit": "economy",
    "economy": "economy",
    "financial-regulation": "economy",
    "gas-prices": "economy",
    "gambling": "economy",
    "housing": "economy",
    "income": "economy",
    "infrastructure": "economy",
    "job-accomplishments": "economy",
    "jobs": "economy",
    "labor": "economy",
    "market-regulation": "economy",
    "medicaid": "economy",
    "pensions": "economy",
    "poverty": "economy",
    "retirement": "economy",
    "small-business": "economy",
    "social-security": "economy",
    "stimulus": "economy",
    "taxes": "economy",
    "tourism": "economy",
    "trade": "economy",
    "unions": "economy",
    "wealth": "economy",
    "workers": "economy",
    "food": "economy",

    # ----- 2. health_social -----
    "health-care": "health_social",
    "medicare": "health_social",
    "public-health": "health_social",
    "food-safety": "health_social",
    "drugs": "health_social",
    "marijuana": "health_social",
    "ebola": "health_social",
    "hunger": "health_social",
    "disability": "health_social",
    "women": "health_social",
    "families": "health_social",
    "sexuality": "health_social",
    "veterans": "health_social",
    "children": "health_social",
    "autism": "health_social",
    "homeless": "health_social",

    # ----- 3. foreign_security -----
    "afghanistan": "foreign_security",
    "foreign-policy": "foreign_security",
    "iraq": "foreign_security",
    "israel": "foreign_security",
    "china": "foreign_security",
    "military": "foreign_security",
    "homeland-security": "foreign_security",
    "terrorism": "foreign_security",
    "nuclear": "foreign_security",
    "patriotism": "foreign_security",
    "natural-disasters": "foreign_security",
    "public-safety": "foreign_security",

    # ----- 4. law_rights -----
    "abortion": "law_rights",
    "civil-rights": "law_rights",
    "crime": "law_rights",
    "criminal-justice": "law_rights",
    "guns": "law_rights",
    "legal-issues": "law_rights",
    "privacy": "law_rights",
    "human-rights": "law_rights",
    "supreme-court": "law_rights",
    "kagan-nomination": "law_rights",
    "sotomayor-nomination": "law_rights",
    "islam": "law_rights",
    "immigration": "law_rights",

    # ----- 5. politics_government -----
    "bipartisanship": "politics_government",
    "bush-administration": "politics_government",
    "campaign-advertising": "politics_government",
    "campaign-finance": "politics_government",
    "candidates-biography": "politics_government",
    "congress": "politics_government",
    "congressional-rules": "politics_government",
    "corrections-and-updates": "politics_government",
    "county-government": "politics_government",
    "county-budget": "politics_government",
    "city-government": "politics_government",
    "city-budget": "politics_government",
    "debates": "politics_government",
    "elections": "politics_government",
    "ethics": "politics_government",
    "fake-news": "politics_government",
    "government-efficiency": "politics_government",
    "government-regulation": "politics_government",
    "message-machine": "politics_government",
    "message-machine-2012": "politics_government",
    "message-machine-2014": "politics_government",
    "new-hampshire-2012": "politics_government",
    "occupy-wall-street": "politics_government",
    "politifacts-top-promises": "politics_government",
    "polls": "politics_government",
    "public-service": "politics_government",
    "redistricting": "politics_government",
    "transparency": "politics_government",
    "states": "politics_government",
    "state-budget": "politics_government",
    "state-finances": "politics_government",
    "voting-record": "politics_government",

    # ----- 6. environment_energy -----
    "cap-and-trade": "environment_energy",
    "climate-change": "environment_energy",
    "environment": "environment_energy",
    "energy": "environment_energy",
    "oil-spill": "environment_energy",
    "water": "environment_energy",
    "weather": "environment_energy",
    "transportation": "environment_energy",
    "urban": "environment_energy",
    "recreation": "environment_energy",

    # ----- 7. society_culture -----
    "education": "society_culture",
    "gays-and-lesbians": "society_culture",
    "diversity": "society_culture",
    "religion": "society_culture",
    "marriage": "society_culture",
    "population": "society_culture",
    "pop-culture": "society_culture",
    "sports": "society_culture",
    "nightlife": "society_culture",
    "history": "society_culture",

    # ----- 8. misc -----
    "abc-news-week": "misc",
    "pundits": "misc",
    "obama-birth-certificate": "misc",
    "space": "misc",
    "technology": "misc",
    "10-news-tampa-bay": "misc",
    "after-the-fact": "misc",
    "lottery": "misc",
}

### Train Domain Routing Model

In [2]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_8,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "meta-llama/Llama-3.1-8B-Instruct"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/llama-liar-statement-domain-lora_8Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
economy                3809
politics_government    1698
health_social          1402
law_rights             1276
foreign_security        971
society_culture         473
environment_energy      412
misc                    199
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 156

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

✅ LoRA adapter & tokenizer saved to: adapters/llama-liar-statement-domain-lora_8Classes
Test set size: 1267
True label distribution (test):
super_domain_true
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Routing statements: 100%|██████████| 1267/1267 [09:57<00:00,  2.12it/s]

Predicted label distribution (test):
super_domain_pred
economy                510
politics_government    208
health_social          158
law_rights             147
foreign_security       113
society_culture         59
environment_energy      52
misc                    20
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.734

Classification report (per superlabel):
                     precision    recall  f1-score   support

            economy       0.77      0.83      0.80       473
      health_social       0.66      0.73      0.70       143
   foreign_security       0.84      0.78      0.81       122
         law_rights       0.73      0.74      0.73       145
politics_government       0.69      0.62      0.65       233
 environment_energy       0.71      0.66      0.69        56
    society_culture       0.64      0.62      0.63        61
               misc       0.60      0.35      0.44        34

           accuracy                           0.73      1267
          macro avg       0.71      0.67      0.68      1267
       weighted avg       0.73      0.73      0.73      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']
[[392  27   0   9  32   4   6   3]
 [ 18 105   3  13   1   0   3   0]
 [  6   3  95  11   2   2   2   1]
 [  6  14   6 107  11   0   1   0]
 [ 57   4   6   4 144   7   7   4]
 [  8   0   1   0   8  37   2   0]
 [  9   3   2   3   6   0  38   0]
 [ 14   2   0   0   4   2   0  12]]

In [3]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_8,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "google/gemma-7b-it"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/gemma-liar-statement-domain-lora_8Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
economy                3809
politics_government    1698
health_social          1402
law_rights             1276
foreign_security        971
society_culture         473
environment_energy      412
misc                    199
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 141

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

✅ LoRA adapter & tokenizer saved to: adapters/gemma-liar-statement-domain-lora_8Classes
Test set size: 1267
True label distribution (test):
super_domain_true
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [03:42<00:00,  5.68it/s]

Predicted label distribution (test):
super_domain_pred
economy                496
health_social          182
law_rights             177
politics_government    145
foreign_security       117
environment_energy      71
society_culture         69
misc                    10
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.725

Classification report (per superlabel):
                     precision    recall  f1-score   support

            economy       0.78      0.81      0.79       473
      health_social       0.65      0.83      0.73       143
   foreign_security       0.82      0.79      0.80       122
         law_rights       0.67      0.82      0.74       145
politics_government       0.77      0.48      0.59       233
 environment_energy       0.58      0.73      0.65        56
    society_culture       0.59      0.67      0.63        61
               misc       0.60      0.18      0.27        34

           accuracy                           0.73      1267
          macro avg       0.68      0.66      0.65      1267
       weighted avg       0.73      0.73      0.72      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']
[[385  38   2  13  17  10   6   2]
 [  7 119   3  11   0   0   3   0]
 [  3   4  96  15   2   2   0   0]
 [  5   6   5 119   6   2   2   0]
 [ 64  10   6  13 112  13  14   1]
 [  9   1   0   0   1  41   3   1]
 [  7   2   3   5   2   1  41   0]
 [ 16   2   2   1   5   2   0   6]]

In [3]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_8,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "deepseek-ai/deepseek-llm-7b-base"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/deepseek-liar-statement-domain-lora_8Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
economy                3809
politics_government    1698
health_social          1402
law_rights             1276
foreign_security        971
society_culture         473
environment_energy      412
misc                    199
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 147

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

The model is already on multiple devices. Skipping the move to device specified in `args`.

✅ LoRA adapter & tokenizer saved to: adapters/deepseek-liar-statement-domain-lora_8Classes
Test set size: 1267
True label distribution (test):
super_domain_true
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [09:25<00:00,  2.24it/s]

Predicted label distribution (test):
super_domain_pred
economy                482
politics_government    232
health_social          162
law_rights             151
foreign_security       121
society_culture         57
environment_energy      48
misc                    14
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.744

Classification report (per superlabel):
                     precision    recall  f1-score   support

            economy       0.80      0.82      0.81       473
      health_social       0.71      0.80      0.75       143
   foreign_security       0.79      0.79      0.79       122
         law_rights       0.72      0.75      0.74       145
politics_government       0.69      0.68      0.68       233
 environment_energy       0.71      0.61      0.65        56
    society_culture       0.60      0.56      0.58        61
               misc       0.57      0.24      0.33        34

           accuracy                           0.74      1267
          macro avg       0.70      0.66      0.67      1267
       weighted avg       0.74      0.74      0.74      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']
[[388  28   2   9  32   5   7   2]
 [  9 115   2  12   2   0   3   0]
 [  5   3  96  11   4   0   3   0]
 [  1  10   9 109  13   0   3   0]
 [ 42   3   8   6 159   8   6   1]
 [ 12   0   1   0   5  34   1   3]
 [  9   1   2   4  11   0  34   0]
 [ 16   2   1   0   6   1   0   8]]

### Train-Experts

In [4]:
import pandas as pd
SUPER_LABELS = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_8.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())

Super-Domain-Verteilung:
super_domain
economy                3809
politics_government    1698
health_social          1402
law_rights             1276
foreign_security        971
society_culture         473
environment_energy      412
misc                    199
Name: count, dtype: int64

In [6]:
df_all.to_csv("Results/preprocessed_train_cleaned_binary_with_super_domain_8.csv", sep="\t", index=False)

In [7]:
import pandas as pd

data_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_8.csv"

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# Sicherstellen, dass wir nur sinnvolle Zeilen haben
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Gesamtverteilung super_domain:")
print(df_all["super_domain"].value_counts())

SUPER_LABELS = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

# Pro Domain ein DataFrame
domain_dfs = {
    domain: df_all[df_all["super_domain"] == domain].reset_index(drop=True)
    for domain in SUPER_LABELS
}

for dom, df_dom in domain_dfs.items():
    print(f"\nDomain: {dom} -> {len(df_dom)} Beispiele")

Gesamtverteilung super_domain:
super_domain
economy                3809
politics_government    1698
health_social          1402
law_rights             1276
foreign_security        971
society_culture         473
environment_energy      412
misc                    199
Name: count, dtype: int64

Domain: economy -> 3809 Beispiele

Domain: health_social -> 1402 Beispiele

Domain: foreign_security -> 971 Beispiele

Domain: law_rights -> 1276 Beispiele

Domain: politics_government -> 1698 Beispiele

Domain: environment_energy -> 412 Beispiele

Domain: society_culture -> 473 Beispiele

Domain: misc -> 199 Beispiele

In [8]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_8.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ],
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/experts_8Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

2026-02-01 13:48:29.398978: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

=== Training expert for domain: economy ===
Samples: 3809

Map:   0%|          | 0/3809 [00:00<?, ? examples/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/1431 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'economy' saved to adapters/experts_8Classes/economy

=== Training expert for domain: health_social ===
Samples: 1402

Map:   0%|          | 0/1402 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/528 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'health_social' saved to adapters/experts_8Classes/health_social

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/experts_8Classes/foreign_security

=== Training expert for domain: law_rights ===
Samples: 1276

Map:   0%|          | 0/1276 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/480 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_rights' saved to adapters/experts_8Classes/law_rights

=== Training expert for domain: politics_government ===
Samples: 1698

Map:   0%|          | 0/1698 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/639 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'politics_government' saved to adapters/experts_8Classes/politics_government

=== Training expert for domain: environment_energy ===
Samples: 412

Map:   0%|          | 0/412 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/156 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy' saved to adapters/experts_8Classes/environment_energy

=== Training expert for domain: society_culture ===
Samples: 473

Map:   0%|          | 0/473 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/180 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/experts_8Classes/society_culture

=== Training expert for domain: misc ===
Samples: 199

Map:   0%|          | 0/199 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/75 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/experts_8Classes/misc

Fertig! Modelle gespeichert unter:
  economy: adapters/experts_8Classes/economy
  health_social: adapters/experts_8Classes/health_social
  foreign_security: adapters/experts_8Classes/foreign_security
  law_rights: adapters/experts_8Classes/law_rights
  politics_government: adapters/experts_8Classes/politics_government
  environment_energy: adapters/experts_8Classes/environment_energy
  society_culture: adapters/experts_8Classes/society_culture
  misc: adapters/experts_8Classes/misc

In [9]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_8.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ],
    base_model_id="google/gemma-7b-it",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/gemma_experts_8Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: economy ===
Samples: 3809

Map:   0%|          | 0/3809 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/1431 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'economy' saved to adapters/gemma_experts_8Classes/economy

=== Training expert for domain: health_social ===
Samples: 1402

Map:   0%|          | 0/1402 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/528 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'health_social' saved to adapters/gemma_experts_8Classes/health_social

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/gemma_experts_8Classes/foreign_security

=== Training expert for domain: law_rights ===
Samples: 1276

Map:   0%|          | 0/1276 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/480 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_rights' saved to adapters/gemma_experts_8Classes/law_rights

=== Training expert for domain: politics_government ===
Samples: 1698

Map:   0%|          | 0/1698 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/639 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'politics_government' saved to adapters/gemma_experts_8Classes/politics_government

=== Training expert for domain: environment_energy ===
Samples: 412

Map:   0%|          | 0/412 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/156 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy' saved to adapters/gemma_experts_8Classes/environment_energy

=== Training expert for domain: society_culture ===
Samples: 473

Map:   0%|          | 0/473 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/180 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/gemma_experts_8Classes/society_culture

=== Training expert for domain: misc ===
Samples: 199

Map:   0%|          | 0/199 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/75 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/gemma_experts_8Classes/misc

Fertig! Modelle gespeichert unter:
  economy: adapters/gemma_experts_8Classes/economy
  health_social: adapters/gemma_experts_8Classes/health_social
  foreign_security: adapters/gemma_experts_8Classes/foreign_security
  law_rights: adapters/gemma_experts_8Classes/law_rights
  politics_government: adapters/gemma_experts_8Classes/politics_government
  environment_energy: adapters/gemma_experts_8Classes/environment_energy
  society_culture: adapters/gemma_experts_8Classes/society_culture
  misc: adapters/gemma_experts_8Classes/misc

In [10]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_8.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
    ],
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/deepseek_experts_8Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: economy ===
Samples: 3809

Map:   0%|          | 0/3809 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/1431 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'economy' saved to adapters/deepseek_experts_8Classes/economy

=== Training expert for domain: health_social ===
Samples: 1402

Map:   0%|          | 0/1402 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/528 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'health_social' saved to adapters/deepseek_experts_8Classes/health_social

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/deepseek_experts_8Classes/foreign_security

=== Training expert for domain: law_rights ===
Samples: 1276

Map:   0%|          | 0/1276 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/480 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_rights' saved to adapters/deepseek_experts_8Classes/law_rights

=== Training expert for domain: politics_government ===
Samples: 1698

Map:   0%|          | 0/1698 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/639 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'politics_government' saved to adapters/deepseek_experts_8Classes/politics_government

=== Training expert for domain: environment_energy ===
Samples: 412

Map:   0%|          | 0/412 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/156 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy' saved to adapters/deepseek_experts_8Classes/environment_energy

=== Training expert for domain: society_culture ===
Samples: 473

Map:   0%|          | 0/473 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/180 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/deepseek_experts_8Classes/society_culture

=== Training expert for domain: misc ===
Samples: 199

Map:   0%|          | 0/199 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/75 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/deepseek_experts_8Classes/misc

Fertig! Modelle gespeichert unter:
  economy: adapters/deepseek_experts_8Classes/economy
  health_social: adapters/deepseek_experts_8Classes/health_social
  foreign_security: adapters/deepseek_experts_8Classes/foreign_security
  law_rights: adapters/deepseek_experts_8Classes/law_rights
  politics_government: adapters/deepseek_experts_8Classes/politics_government
  environment_energy: adapters/deepseek_experts_8Classes/environment_energy
  society_culture: adapters/deepseek_experts_8Classes/society_culture
  misc: adapters/deepseek_experts_8Classes/misc

### Evaluation

In [2]:
import pandas as pd
SUPER_LABELS = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_8.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())
df_all.to_csv("Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv", sep="\t", index=False)

Super-Domain-Verteilung:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

In [2]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_8Classes",
    expert_root="adapters/Llama_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/Llama_test_predictions_with_experts_8.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🌍 Routing-only: 100%|██████████| 1267/1267 [09:42<00:00,  2.17it/s]

Predicted domain distribution (router):
domain_pred_router
economy                506
politics_government    201
health_social          162
law_rights             139
foreign_security       114
society_culture         65
environment_energy      57
misc                    23
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: economy:   2%|▏         | 10/506 [01:46<1:23:56, 10.15s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 Expert: economy: 100%|██████████| 506/506 [1:49:37<00:00, 13.00s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: health_social: 100%|██████████| 162/162 [26:20<00:00,  9.76s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 114/114 [17:38<00:00,  9.29s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_rights: 100%|██████████| 139/139 [24:28<00:00, 10.57s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: politics_government: 100%|██████████| 201/201 [29:42<00:00,  8.87s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy: 100%|██████████| 57/57 [07:53<00:00,  8.30s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 65/65 [26:24<00:00, 24.38s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 23/23 [03:53<00:00, 10.16s/it]

Sample rows with predictions:
                                           statement   super_domain  \
0  Building a wall on the U.S . Mexico border wil...     law_rights
1  Wisconsin is on pace to double the number of l...        economy
2  Says John McCain has done nothing to help the ...  health_social
3  Suzanne Bonamici supports a plan that will cut...  health_social
4  When asked by a reporter whether hes at the ce...     law_rights

     domain_pred  label verdict_pred
0     law_rights   True         True
1        economy  False         True
2  health_social  False        False
3  health_social   True         True
4        economy  False         True

🌍 Domain routing accuracy: 0.740
Confusion matrix (rows=true, cols=pred):
[[393  28   2   7  29   3   8   3]
 [ 15 108   3  13   1   0   3   0]
 [  8   3  95   9   2   2   2   1]
 [  7  13   5 106  11   1   2   0]
 [ 55   4   6   3 143  10   8   4]
 [  8   0   1   0   5  39   1   2]
 [  7   3   2   1   6   0  41   1]
 [ 13   3   0   0   4   2   0  12]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.632

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.67      0.69      0.68       714
       False       0.58      0.56      0.57       553

    accuracy                           0.63      1267
   macro avg       0.63      0.62      0.62      1267
weighted avg       0.63      0.63      0.63      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[492 222]
 [244 309]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 473 acc=0.653
health_social          n= 143 acc=0.650
foreign_security       n= 122 acc=0.672
law_rights             n= 145 acc=0.614
politics_government    n= 233 acc=0.635
environment_energy     n=  56 acc=0.607
society_culture        n=  61 acc=0.443
misc                   n=  34 acc=0.559

💾 Saved predictions to: Results/Llama_test_predictions_with_experts_8.csv

In [ ]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_8Classes",
    expert_root="adapters/gemma_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/gemma_test_predictions_with_experts_8.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

In [8]:
evaluate_predictions("Results/gemma_test_predictions_with_experts_8.csv")

==============================
✅ Verdict Evaluation (overall)
==============================
Samples: 1267
Verdict Accuracy: 0.577

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.61      0.69      0.65       714
       False       0.52      0.43      0.47       553

    accuracy                           0.58      1267
   macro avg       0.56      0.56      0.56      1267
weighted avg       0.57      0.58      0.57      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[492 222]
 [314 239]]

==================================
🌍 Domain Routing Evaluation
==================================
Routing samples: 1267
Domain-Routing Accuracy: 0.720
Domain-Routing Confusion Matrix (rows=true, cols=pred):
[[388  31   2  13  17  13   8   1]
 [  8 115   3  14   0   0   3   0]
 [  4   5  92  15   2   2   2   0]
 [  6   7   5 117   7   1   2   0]
 [ 59   9   6  15 111  14  17   2]
 [  8   1   0   0   2  42   3   0]
 [  7   3   3   5   3   2  38   0]
 [ 15   1   2   1   2   2   2   9]]
Domain label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

=================================================
📊 Per-Domain Verdict Accuracy (by true super_domain)
=================================================
economy                n= 473 acc=0.548
health_social          n= 143 acc=0.636
foreign_security       n= 122 acc=0.631
law_rights             n= 145 acc=0.628
politics_government    n= 233 acc=0.584
environment_energy     n=  56 acc=0.446
society_culture        n=  61 acc=0.492
misc                   n=  34 acc=0.647

In [1]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_8Classes",
    expert_root="adapters/deepseek_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/deepseek_test_predictions_with_experts_8.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [09:18<00:00,  2.27it/s]

Predicted domain distribution (router):
domain_pred_router
economy                482
politics_government    225
health_social          163
law_rights             146
foreign_security       120
society_culture         59
environment_energy      53
misc                    19
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Expert: economy:   2%|▏         | 10/482 [01:07<52:44,  6.70s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 Expert: economy: 100%|██████████| 482/482 [54:30<00:00,  6.79s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: health_social: 100%|██████████| 163/163 [17:34<00:00,  6.47s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 120/120 [13:30<00:00,  6.75s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_rights: 100%|██████████| 146/146 [17:30<00:00,  7.20s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: politics_government: 100%|██████████| 225/225 [23:46<00:00,  6.34s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy: 100%|██████████| 53/53 [05:43<00:00,  6.49s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 59/59 [07:10<00:00,  7.30s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 19/19 [03:57<00:00, 12.48s/it]

Sample rows with predictions:
                                           statement   super_domain  \
0  Building a wall on the U.S . Mexico border wil...     law_rights
1  Wisconsin is on pace to double the number of l...        economy
2  Says John McCain has done nothing to help the ...  health_social
3  Suzanne Bonamici supports a plan that will cut...  health_social
4  When asked by a reporter whether hes at the ce...     law_rights

           domain_pred  label verdict_pred
0           law_rights   True         True
1              economy  False         True
2        health_social  False         True
3        health_social   True         True
4  politics_government  False         True

🌍 Domain routing accuracy: 0.744
Confusion matrix (rows=true, cols=pred):
[[388  27   1   9  30   6   8   4]
 [  8 118   3  10   2   0   2   0]
 [  6   3  94  10   5   0   4   0]
 [  2   9  10 107  14   0   3   0]
 [ 43   3   8   6 155  10   7   1]
 [ 11   0   1   0   4  36   1   3]
 [  9   1   2   4  11   0  34   0]
 [ 15   2   1   0   4   1   0  11]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.610

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.95      0.73       714
       False       0.73      0.17      0.28       553

    accuracy                           0.61      1267
   macro avg       0.66      0.56      0.51      1267
weighted avg       0.65      0.61      0.53      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[678  36]
 [458  95]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 473 acc=0.634
health_social          n= 143 acc=0.629
foreign_security       n= 122 acc=0.590
law_rights             n= 145 acc=0.538
politics_government    n= 233 acc=0.605
environment_energy     n=  56 acc=0.554
society_culture        n=  61 acc=0.607
misc                   n=  34 acc=0.706

💾 Saved predictions to: Results/deepseek_test_predictions_with_experts_8.csv

## 6 Superlabels

In [1]:
domain_to_super_5 = {
    # ----- 1. socioeconomic_policy -----
    "Alcohol": "socioeconomic_policy",
    "agriculture": "socioeconomic_policy",
    "bankruptcy": "socioeconomic_policy",
    "corporations": "socioeconomic_policy",
    "consumer-safety": "socioeconomic_policy",
    "debt": "socioeconomic_policy",
    "deficit": "socioeconomic_policy",
    "economy": "socioeconomic_policy",
    "financial-regulation": "socioeconomic_policy",
    "gas-prices": "socioeconomic_policy",
    "gambling": "socioeconomic_policy",
    "housing": "socioeconomic_policy",
    "income": "socioeconomic_policy",
    "infrastructure": "socioeconomic_policy",
    "job-accomplishments": "socioeconomic_policy",
    "jobs": "socioeconomic_policy",
    "labor": "socioeconomic_policy",
    "market-regulation": "socioeconomic_policy",
    "medicaid": "socioeconomic_policy",
    "pensions": "socioeconomic_policy",
    "poverty": "socioeconomic_policy",
    "retirement": "socioeconomic_policy",
    "small-business": "socioeconomic_policy",
    "social-security": "socioeconomic_policy",
    "stimulus": "socioeconomic_policy",
    "taxes": "socioeconomic_policy",
    "tourism": "socioeconomic_policy",
    "trade": "socioeconomic_policy",
    "unions": "socioeconomic_policy",
    "wealth": "socioeconomic_policy",
    "workers": "socioeconomic_policy",
    "food": "socioeconomic_policy",

    # health_social domains → socioeconomic_policy
    "health-care": "socioeconomic_policy",
    "medicare": "socioeconomic_policy",
    "public-health": "socioeconomic_policy",
    "food-safety": "socioeconomic_policy",
    "drugs": "socioeconomic_policy",
    "marijuana": "socioeconomic_policy",
    "ebola": "socioeconomic_policy",
    "hunger": "socioeconomic_policy",
    "disability": "socioeconomic_policy",
    "women": "socioeconomic_policy",
    "families": "socioeconomic_policy",
    "sexuality": "socioeconomic_policy",
    "veterans": "socioeconomic_policy",
    "children": "socioeconomic_policy",
    "autism": "socioeconomic_policy",
    "homeless": "socioeconomic_policy",

    # ----- 2. foreign_security -----
    "afghanistan": "foreign_security",
    "foreign-policy": "foreign_security",
    "iraq": "foreign_security",
    "israel": "foreign_security",
    "china": "foreign_security",
    "military": "foreign_security",
    "homeland-security": "foreign_security",
    "terrorism": "foreign_security",
    "nuclear": "foreign_security",
    "patriotism": "foreign_security",
    "natural-disasters": "foreign_security",
    "public-safety": "foreign_security",

    # ----- 3. governance_law -----
    "abortion": "governance_law",
    "civil-rights": "governance_law",
    "crime": "governance_law",
    "criminal-justice": "governance_law",
    "guns": "governance_law",
    "legal-issues": "governance_law",
    "privacy": "governance_law",
    "human-rights": "governance_law",
    "supreme-court": "governance_law",
    "kagan-nomination": "governance_law",
    "sotomayor-nomination": "governance_law",
    "islam": "governance_law",
    "immigration": "governance_law",

    "bipartisanship": "governance_law",
    "bush-administration": "governance_law",
    "campaign-advertising": "governance_law",
    "campaign-finance": "governance_law",
    "candidates-biography": "governance_law",
    "congress": "governance_law",
    "congressional-rules": "governance_law",
    "corrections-and-updates": "governance_law",
    "county-government": "governance_law",
    "county-budget": "governance_law",
    "city-government": "governance_law",
    "city-budget": "governance_law",
    "debates": "governance_law",
    "elections": "governance_law",
    "ethics": "governance_law",
    "fake-news": "governance_law",
    "government-efficiency": "governance_law",
    "government-regulation": "governance_law",
    "message-machine": "governance_law",
    "message-machine-2012": "governance_law",
    "message-machine-2014": "governance_law",
    "new-hampshire-2012": "governance_law",
    "occupy-wall-street": "governance_law",
    "politifacts-top-promises": "governance_law",
    "polls": "governance_law",
    "public-service": "governance_law",
    "redistricting": "governance_law",
    "transparency": "governance_law",
    "states": "governance_law",
    "state-budget": "governance_law",
    "state-finances": "governance_law",
    "voting-record": "governance_law",

    # ----- 4. environment_science -----
    "cap-and-trade": "environment_science",
    "climate-change": "environment_science",
    "environment": "environment_science",
    "energy": "environment_science",
    "oil-spill": "environment_science",
    "water": "environment_science",
    "weather": "environment_science",
    "transportation": "environment_science",
    "urban": "environment_science",
    "recreation": "environment_science",

    # frühere misc → environment_science
    "space": "environment_science",
    "technology": "environment_science",

    # ----- 5. society_culture -----
    "education": "society_culture",
    "gays-and-lesbians": "society_culture",
    "diversity": "society_culture",
    "religion": "society_culture",
    "marriage": "society_culture",
    "population": "society_culture",
    "pop-culture": "society_culture",
    "sports": "society_culture",
    "nightlife": "society_culture",
    "history": "society_culture",

    # ----- misc bleibt misc (Medien & irrelevante Kategorien) -----
    "abc-news-week": "misc",
    "pundits": "misc",
    "obama-birth-certificate": "misc",
    "10-news-tampa-bay": "misc",
    "after-the-fact": "misc",
    "lottery": "misc",
}

### Train Domain Routing Model

In [13]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_5,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "meta-llama/Llama-3.1-8B-Instruct"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/llama-liar-statement-domain-lora_5Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
socioeconomic_policy    5211
governance_law          2974
foreign_security         971
society_culture          467
environment_science      428
misc                     189
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 151

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

✅ LoRA adapter & tokenizer saved to: adapters/llama-liar-statement-domain-lora_5Classes
Test set size: 1267
True label distribution (test):
super_domain_true
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Routing statements: 100%|██████████| 1267/1267 [09:52<00:00,  2.14it/s]

Predicted label distribution (test):
super_domain_pred
socioeconomic_policy    638
governance_law          373
foreign_security        111
society_culture          76
environment_science      55
misc                     14
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.796

Classification report (per superlabel):
                      precision    recall  f1-score   support

socioeconomic_policy       0.85      0.88      0.86       616
    foreign_security       0.84      0.76      0.80       122
      governance_law       0.76      0.75      0.76       378
 environment_science       0.67      0.65      0.66        57
     society_culture       0.57      0.70      0.63        61
                misc       0.64      0.27      0.38        33

            accuracy                           0.80      1267
           macro avg       0.72      0.67      0.68      1267
        weighted avg       0.80      0.80      0.79      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']
[[542   2  53   4  13   2]
 [  9  93  14   2   4   0]
 [ 57  11 284  10  14   2]
 [  8   2   7  37   2   1]
 [  6   3   9   0  43   0]
 [ 16   0   6   2   0   9]]

In [14]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_5,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "google/gemma-7b-it"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/gemma-liar-statement-domain-lora_5Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
socioeconomic_policy    5211
governance_law          2974
foreign_security         971
society_culture          467
environment_science      428
misc                     189
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 133

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

✅ LoRA adapter & tokenizer saved to: adapters/gemma-liar-statement-domain-lora_5Classes
Test set size: 1267
True label distribution (test):
super_domain_true
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [04:27<00:00,  4.74it/s]

Predicted label distribution (test):
super_domain_pred
socioeconomic_policy    589
governance_law          387
foreign_security        121
society_culture          80
environment_science      80
misc                     10
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.770

Classification report (per superlabel):
                      precision    recall  f1-score   support

socioeconomic_policy       0.87      0.84      0.85       616
    foreign_security       0.81      0.80      0.81       122
      governance_law       0.72      0.73      0.72       378
 environment_science       0.53      0.74      0.61        57
     society_culture       0.46      0.61      0.52        61
                misc       0.60      0.18      0.28        33

            accuracy                           0.77      1267
           macro avg       0.66      0.65      0.63      1267
        weighted avg       0.78      0.77      0.77      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']
[[515   2  72  11  15   1]
 [  5  98  12   4   3   0]
 [ 45  14 277  17  23   2]
 [  6   1   5  42   2   1]
 [  6   5  10   3  37   0]
 [ 12   1  11   3   0   6]]

In [15]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_5,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "deepseek-ai/deepseek-llm-7b-base"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/deepseek-liar-statement-domain-lora_5Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
socioeconomic_policy    5211
governance_law          2974
foreign_security         971
society_culture          467
environment_science      428
misc                     189
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 140

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

The model is already on multiple devices. Skipping the move to device specified in `args`.

✅ LoRA adapter & tokenizer saved to: adapters/deepseek-liar-statement-domain-lora_5Classes
Test set size: 1267
True label distribution (test):
super_domain_true
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [09:08<00:00,  2.31it/s]

Predicted label distribution (test):
super_domain_pred
socioeconomic_policy    632
governance_law          376
foreign_security        126
society_culture          61
environment_science      61
misc                     11
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.780

Classification report (per superlabel):
                      precision    recall  f1-score   support

socioeconomic_policy       0.84      0.86      0.85       616
    foreign_security       0.79      0.82      0.81       122
      governance_law       0.73      0.73      0.73       378
 environment_science       0.64      0.68      0.66        57
     society_culture       0.56      0.56      0.56        61
                misc       0.82      0.27      0.41        33

            accuracy                           0.78      1267
           macro avg       0.73      0.65      0.67      1267
        weighted avg       0.78      0.78      0.78      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']
[[531   5  63   7   9   1]
 [  8 100  11   0   3   0]
 [ 62  16 275  11  13   1]
 [  7   1   8  39   2   0]
 [  9   4  13   1  34   0]
 [ 15   0   6   3   0   9]]

### Train-Experts

In [2]:
import pandas as pd
SUPER_LABELS = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_5.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())

Super-Domain-Verteilung:
super_domain
socioeconomic_policy    5211
governance_law          2974
foreign_security         971
society_culture          467
environment_science      428
misc                     189
Name: count, dtype: int64

In [3]:
df_all.to_csv("Results/preprocessed_train_cleaned_binary_with_super_domain_5.csv", sep="\t", index=False)

In [4]:
import pandas as pd

data_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_5.csv"

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# Sicherstellen, dass wir nur sinnvolle Zeilen haben
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Gesamtverteilung super_domain:")
print(df_all["super_domain"].value_counts())

SUPER_LABELS = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

# Pro Domain ein DataFrame
domain_dfs = {
    domain: df_all[df_all["super_domain"] == domain].reset_index(drop=True)
    for domain in SUPER_LABELS
}

for dom, df_dom in domain_dfs.items():
    print(f"\nDomain: {dom} -> {len(df_dom)} Beispiele")

Gesamtverteilung super_domain:
super_domain
socioeconomic_policy    5211
governance_law          2974
foreign_security         971
society_culture          467
environment_science      428
misc                     189
Name: count, dtype: int64

Domain: socioeconomic_policy -> 5211 Beispiele

Domain: foreign_security -> 971 Beispiele

Domain: governance_law -> 2974 Beispiele

Domain: environment_science -> 428 Beispiele

Domain: society_culture -> 467 Beispiele

Domain: misc -> 189 Beispiele

In [5]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_5.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ],
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/Llama_experts_5Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

2026-02-02 06:19:59.986569: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

=== Training expert for domain: socioeconomic_policy ===
Samples: 5211

Map:   0%|          | 0/5211 [00:00<?, ? examples/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/1956 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'socioeconomic_policy' saved to adapters/Llama_experts_5Classes/socioeconomic_policy

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/Llama_experts_5Classes/foreign_security

=== Training expert for domain: governance_law ===
Samples: 2974

Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/1116 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'governance_law' saved to adapters/Llama_experts_5Classes/governance_law

=== Training expert for domain: environment_science ===
Samples: 428

Map:   0%|          | 0/428 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/162 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_science' saved to adapters/Llama_experts_5Classes/environment_science

=== Training expert for domain: society_culture ===
Samples: 467

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/Llama_experts_5Classes/society_culture

=== Training expert for domain: misc ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/Llama_experts_5Classes/misc

Fertig! Modelle gespeichert unter:
  socioeconomic_policy: adapters/Llama_experts_5Classes/socioeconomic_policy
  foreign_security: adapters/Llama_experts_5Classes/foreign_security
  governance_law: adapters/Llama_experts_5Classes/governance_law
  environment_science: adapters/Llama_experts_5Classes/environment_science
  society_culture: adapters/Llama_experts_5Classes/society_culture
  misc: adapters/Llama_experts_5Classes/misc

In [6]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_5.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ],
    base_model_id="google/gemma-7b-it",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/gemma_experts_5Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: socioeconomic_policy ===
Samples: 5211

Map:   0%|          | 0/5211 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/1956 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'socioeconomic_policy' saved to adapters/gemma_experts_5Classes/socioeconomic_policy

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/gemma_experts_5Classes/foreign_security

=== Training expert for domain: governance_law ===
Samples: 2974

Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/1116 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'governance_law' saved to adapters/gemma_experts_5Classes/governance_law

=== Training expert for domain: environment_science ===
Samples: 428

Map:   0%|          | 0/428 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/162 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_science' saved to adapters/gemma_experts_5Classes/environment_science

=== Training expert for domain: society_culture ===
Samples: 467

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/gemma_experts_5Classes/society_culture

=== Training expert for domain: misc ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/gemma_experts_5Classes/misc

Fertig! Modelle gespeichert unter:
  socioeconomic_policy: adapters/gemma_experts_5Classes/socioeconomic_policy
  foreign_security: adapters/gemma_experts_5Classes/foreign_security
  governance_law: adapters/gemma_experts_5Classes/governance_law
  environment_science: adapters/gemma_experts_5Classes/environment_science
  society_culture: adapters/gemma_experts_5Classes/society_culture
  misc: adapters/gemma_experts_5Classes/misc

In [7]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_5.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
    ],
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/deepseek_experts_5Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: socioeconomic_policy ===
Samples: 5211

Map:   0%|          | 0/5211 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/1956 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'socioeconomic_policy' saved to adapters/deepseek_experts_5Classes/socioeconomic_policy

=== Training expert for domain: foreign_security ===
Samples: 971

Map:   0%|          | 0/971 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/366 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_security' saved to adapters/deepseek_experts_5Classes/foreign_security

=== Training expert for domain: governance_law ===
Samples: 2974

Map:   0%|          | 0/2974 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/1116 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'governance_law' saved to adapters/deepseek_experts_5Classes/governance_law

=== Training expert for domain: environment_science ===
Samples: 428

Map:   0%|          | 0/428 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/162 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_science' saved to adapters/deepseek_experts_5Classes/environment_science

=== Training expert for domain: society_culture ===
Samples: 467

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'society_culture' saved to adapters/deepseek_experts_5Classes/society_culture

=== Training expert for domain: misc ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'misc' saved to adapters/deepseek_experts_5Classes/misc

Fertig! Modelle gespeichert unter:
  socioeconomic_policy: adapters/deepseek_experts_5Classes/socioeconomic_policy
  foreign_security: adapters/deepseek_experts_5Classes/foreign_security
  governance_law: adapters/deepseek_experts_5Classes/governance_law
  environment_science: adapters/deepseek_experts_5Classes/environment_science
  society_culture: adapters/deepseek_experts_5Classes/society_culture
  misc: adapters/deepseek_experts_5Classes/misc

### Evaluation

In [2]:
import pandas as pd
SUPER_LABELS = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_5.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())
df_all.to_csv("Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv", sep="\t", index=False)

Super-Domain-Verteilung:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

In [ ]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_5Classes",
    expert_root="adapters/Llama_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/Llama_test_predictions_with_experts_5.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🌍 Routing-only: 100%|██████████| 1267/1267 [10:13<00:00,  2.07it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    699
governance_law          330
foreign_security        106
society_culture          64
environment_science      54
misc                     14
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: socioeconomic_policy:   1%|▏         | 10/699 [04:16<5:04:34, 26.52s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 Expert: socioeconomic_policy: 100%|██████████| 699/699 [5:34:59<00:00, 28.75s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 106/106 [19:10<00:00, 10.85s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: governance_law:   1%|          | 4/330 [01:22<1:58:04, 21.73s/it]

In [ ]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_5Classes",
    expert_root="adapters/gemma_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/gemma_test_predictions_with_experts_5.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [05:31<00:00,  3.82it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    594
governance_law          376
foreign_security        119
society_culture          83
environment_science      83
misc                     12
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Expert: socioeconomic_policy:   0%|          | 1/594 [00:48<7:56:51, 48.25s/it]

In [6]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_5Classes",
    expert_root="adapters/deepseek_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/deepseek_test_predictions_with_experts_5.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [09:52<00:00,  2.14it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    640
governance_law          394
foreign_security        117
environment_science      58
society_culture          49
misc                      9
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: socioeconomic_policy: 100%|██████████| 640/640 [1:15:13<00:00,  7.05s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 117/117 [14:00<00:00,  7.18s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: governance_law: 100%|██████████| 394/394 [44:55<00:00,  6.84s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_science: 100%|██████████| 58/58 [06:54<00:00,  7.14s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 49/49 [09:23<00:00, 11.51s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 9/9 [00:58<00:00,  6.53s/it]

Sample rows with predictions:
                                           statement          super_domain  \
0  Building a wall on the U.S . Mexico border wil...        governance_law
1  Wisconsin is on pace to double the number of l...  socioeconomic_policy
2  Says John McCain has done nothing to help the ...  socioeconomic_policy
3  Suzanne Bonamici supports a plan that will cut...  socioeconomic_policy
4  When asked by a reporter whether hes at the ce...        governance_law

            domain_pred  label verdict_pred
0        governance_law   True         True
1  socioeconomic_policy  False         True
2  socioeconomic_policy  False        False
3  socioeconomic_policy   True        False
4        governance_law  False        False

🌍 Domain routing accuracy: 0.788
Confusion matrix (rows=true, cols=pred):
[[538   2  63   7   6   0]
 [  8  99  12   0   3   0]
 [ 54  11 290   9  10   4]
 [  8   1   7  39   2   0]
 [  9   4  18   1  28   1]
 [ 23   0   4   2   0   4]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.661

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.65      0.87      0.74       714
       False       0.70      0.40      0.50       553

    accuracy                           0.66      1267
   macro avg       0.67      0.63      0.62      1267
weighted avg       0.67      0.66      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[618  96]
 [334 219]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 616 acc=0.680
foreign_security       n= 122 acc=0.590
governance_law         n= 378 acc=0.653
environment_science    n=  57 acc=0.579
society_culture        n=  61 acc=0.689
misc                   n=  33 acc=0.727

💾 Saved predictions to: Results/deepseek_test_predictions_with_experts_5.csv

## 13 Superlabels

In [8]:
domain_to_super_12 = {

    # ----- 1. macro_econ -----
    "economy": "macro_econ",
    "deficit": "macro_econ",
    "debt": "macro_econ",
    "stimulus": "macro_econ",
    "taxes": "macro_econ",
    "trade": "macro_econ",

    # ----- 2. jobs_labor -----
    "jobs": "jobs_labor",
    "job-accomplishments": "jobs_labor",
    "labor": "jobs_labor",
    "unions": "jobs_labor",
    "workers": "jobs_labor",
    "income": "jobs_labor",

    # ----- 3. business_finance -----
    "corporations": "business_finance",
    "bankruptcy": "business_finance",
    "financial-regulation": "business_finance",
    "market-regulation": "business_finance",
    "small-business": "business_finance",

    # ----- 4. cost_of_living_housing -----
    "housing": "cost_of_living_housing",
    "gas-prices": "cost_of_living_housing",
    "poverty": "cost_of_living_housing",
    "wealth": "cost_of_living_housing",
    "retirement": "cost_of_living_housing",
    "pensions": "cost_of_living_housing",
    "social-security": "cost_of_living_housing",
    "tourism": "cost_of_living_housing",

    # ----- 5. healthcare_policy -----
    "health-care": "healthcare_policy",
    "medicare": "healthcare_policy",
    "medicaid": "healthcare_policy",
    "public-health": "healthcare_policy",

    # ----- 6. public_health_crises -----
    "ebola": "public_health_crises",
    "natural-disasters": "public_health_crises",
    "public-safety": "public_health_crises",
    "food-safety": "public_health_crises",
    "consumer-safety": "public_health_crises",

    # ----- 7. substances_gambling -----
    "drugs": "substances_gambling",
    "marijuana": "substances_gambling",
    "Alcohol": "substances_gambling",
    "gambling": "substances_gambling",
    "lottery": "substances_gambling",

    # ----- 8. family_demographics -----
    "women": "family_demographics",
    "families": "family_demographics",
    "children": "family_demographics",
    "veterans": "family_demographics",
    "disability": "family_demographics",
    "autism": "family_demographics",
    "homeless": "family_demographics",
    "hunger": "family_demographics",
    "population": "family_demographics",
    "food": "family_demographics",

    # ----- 9. law_crime_rights -----
    "crime": "law_crime_rights",
    "criminal-justice": "law_crime_rights",
    "guns": "law_crime_rights",
    "abortion": "law_crime_rights",
    "civil-rights": "law_crime_rights",
    "human-rights": "law_crime_rights",
    "privacy": "law_crime_rights",
    "immigration": "law_crime_rights",
    "islam": "law_crime_rights",

    # ----- 10. institutions_elections -----
    "congress": "institutions_elections",
    "congressional-rules": "institutions_elections",
    "elections": "institutions_elections",
    "polls": "institutions_elections",
    "debates": "institutions_elections",
    "campaign-finance": "institutions_elections",
    "campaign-advertising": "institutions_elections",
    "redistricting": "institutions_elections",
    "voting-record": "institutions_elections",
    "candidates-biography": "institutions_elections",
    "ethics": "institutions_elections",
    "transparency": "institutions_elections",
    "bipartisanship": "institutions_elections",
    "government-regulation": "institutions_elections",
    "government-efficiency": "institutions_elections",
    "public-service": "institutions_elections",
    "states": "institutions_elections",
    "state-budget": "institutions_elections",
    "state-finances": "institutions_elections",
    "county-government": "institutions_elections",
    "county-budget": "institutions_elections",
    "city-government": "institutions_elections",
    "city-budget": "institutions_elections",
    "bush-administration": "institutions_elections",

    # ----- 11. foreign_affairs_security -----
    "foreign-policy": "foreign_affairs_security",
    "afghanistan": "foreign_affairs_security",
    "iraq": "foreign_affairs_security",
    "israel": "foreign_affairs_security",
    "china": "foreign_affairs_security",
    "military": "foreign_affairs_security",
    "terrorism": "foreign_affairs_security",
    "homeland-security": "foreign_affairs_security",
    "nuclear": "foreign_affairs_security",
    "patriotism": "foreign_affairs_security",

    # ----- 12. environment_energy_infra -----
    "climate-change": "environment_energy_infra",
    "cap-and-trade": "environment_energy_infra",
    "environment": "environment_energy_infra",
    "energy": "environment_energy_infra",
    "oil-spill": "environment_energy_infra",
    "water": "environment_energy_infra",
    "weather": "environment_energy_infra",
    "transportation": "environment_energy_infra",
    "urban": "environment_energy_infra",
    "infrastructure": "environment_energy_infra",
    "recreation": "environment_energy_infra",

    # ----- media / meta (optional separate handling) -----
    "abc-news-week": "media_meta",
    "pundits": "media_meta",
    "after-the-fact": "media_meta",
    "corrections-and-updates": "media_meta",
    "fake-news": "media_meta",
    "message-machine": "media_meta",
    "message-machine-2012": "media_meta",
    "message-machine-2014": "media_meta",
    "new-hampshire-2012": "media_meta",
    "occupy-wall-street": "media_meta",
    "politifacts-top-promises": "media_meta",
    "10-news-tampa-bay": "media_meta",
    "obama-birth-certificate": "media_meta",
    "technology": "media_meta",
    "space": "media_meta",
    "history": "media_meta",
    "education": "media_meta",
    "religion": "media_meta",
    "marriage": "media_meta",
    "gays-and-lesbians": "media_meta",
    "diversity": "media_meta",
    "pop-culture": "media_meta",
    "sports": "media_meta",
    "nightlife": "media_meta",
}

### Train Domain Routing Model

In [12]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_12,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "meta-llama/Llama-3.1-8B-Instruct"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/llama-liar-statement-domain-lora_12Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
macro_econ                  2606
institutions_elections      1798
law_crime_rights            1245
healthcare_policy           1087
jobs_labor                   764
foreign_affairs_security     651
media_meta                   571
environment_energy_infra     468
family_demographics          317
cost_of_living_housing       295
business_finance             189
public_health_crises         139
substances_gambling          110
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 197

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

The model is already on multiple devices. Skipping the move to device specified in `args`.

✅ LoRA adapter & tokenizer saved to: adapters/llama-liar-statement-domain-lora_12Classes
Test set size: 1267
True label distribution (test):
super_domain_true
macro_econ                  316
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [09:59<00:00,  2.11it/s]

Predicted label distribution (test):
super_domain_pred
macro_econ                  368
institutions_elections      223
law_crime_rights            145
healthcare_policy           130
foreign_affairs_security     88
media_meta                   85
environment_energy_infra     66
jobs_labor                   59
family_demographics          37
cost_of_living_housing       22
business_finance             20
substances_gambling          16
public_health_crises          8
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.677

Classification report (per superlabel):
                          precision    recall  f1-score   support

              macro_econ       0.71      0.83      0.77       316
              jobs_labor       0.61      0.34      0.43       107
        business_finance       0.35      0.30      0.33        23
  cost_of_living_housing       0.64      0.32      0.42        44
       healthcare_policy       0.75      0.86      0.80       114
    public_health_crises       0.50      0.29      0.36        14
     substances_gambling       0.38      0.46      0.41        13
     family_demographics       0.32      0.43      0.37        28
        law_crime_rights       0.71      0.79      0.75       131
  institutions_elections       0.70      0.61      0.65       256
foreign_affairs_security       0.76      0.83      0.79        81
environment_energy_infra       0.64      0.69      0.66        61
              media_meta       0.60      0.65      0.62        79

                accuracy                           0.68      1267
               macro avg       0.59      0.57      0.57      1267
            weighted avg       0.67      0.68      0.67      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']
[[262  11   0   5   6   0   1   3   3  13   1   7   4]
 [ 34  36   2   0   4   0   1   0   3  22   0   0   5]
 [  9   0   7   0   3   0   1   0   1   2   0   0   0]
 [ 14   0   1  14   6   0   0   3   0   3   0   2   1]
 [  4   3   0   0  98   0   2   1   2   1   2   0   1]
 [  0   0   0   0   0   4   1   0   6   1   1   1   0]
 [  0   0   0   0   4   0   6   0   2   0   0   0   1]
 [  1   0   0   3   1   0   0  12   8   1   0   0   2]
 [  0   1   0   0   2   1   1   7 103   9   4   0   3]
 [ 30   6   7   0   4   1   2   4  10 156  11  14  11]
 [  1   0   0   0   2   0   0   1   4   3  67   0   3]
 [  4   2   3   0   0   2   0   1   1   3   0  42   3]
 [  9   0   0   0   0   0   1   5   2   9   2   0  51]]

In [14]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_12,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "google/gemma-7b-it"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/gemma-liar-statement-domain-lora_12Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
macro_econ                  2606
institutions_elections      1798
law_crime_rights            1245
healthcare_policy           1087
jobs_labor                   764
foreign_affairs_security     651
media_meta                   571
environment_energy_infra     468
family_demographics          317
cost_of_living_housing       295
business_finance             189
public_health_crises         139
substances_gambling          110
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 188

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

✅ LoRA adapter & tokenizer saved to: adapters/gemma-liar-statement-domain-lora_12Classes
Test set size: 1267
True label distribution (test):
super_domain_true
macro_econ                  316
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [05:32<00:00,  3.81it/s]

Predicted label distribution (test):
super_domain_pred
macro_econ                  272
institutions_elections      198
law_crime_rights            148
healthcare_policy           123
jobs_labor                  120
media_meta                  104
foreign_affairs_security     79
environment_energy_infra     72
cost_of_living_housing       54
family_demographics          42
business_finance             30
public_health_crises         17
substances_gambling           8
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.658

Classification report (per superlabel):
                          precision    recall  f1-score   support

              macro_econ       0.79      0.68      0.73       316
              jobs_labor       0.50      0.56      0.53       107
        business_finance       0.30      0.39      0.34        23
  cost_of_living_housing       0.48      0.59      0.53        44
       healthcare_policy       0.80      0.86      0.83       114
    public_health_crises       0.18      0.21      0.19        14
     substances_gambling       0.62      0.38      0.48        13
     family_demographics       0.31      0.46      0.37        28
        law_crime_rights       0.69      0.78      0.73       131
  institutions_elections       0.76      0.59      0.66       256
foreign_affairs_security       0.73      0.72      0.72        81
environment_energy_infra       0.58      0.69      0.63        61
              media_meta       0.51      0.67      0.58        79

                accuracy                           0.66      1267
               macro avg       0.56      0.58      0.56      1267
            weighted avg       0.68      0.66      0.66      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']
[[215  35   5   8   9   1   1   4   3  13   1  12   9]
 [ 13  60   3   3   2   2   1   1   3  12   0   1   6]
 [  5   2   9   1   1   0   1   1   1   2   0   0   0]
 [  7   0   0  26   4   0   0   4   0   2   0   1   0]
 [  2   2   1   1  98   1   0   2   3   1   1   0   2]
 [  0   0   1   0   1   3   0   1   6   0   1   1   0]
 [  1   0   0   1   3   0   5   0   2   0   0   0   1]
 [  1   0   0   4   1   0   0  13   6   1   0   0   2]
 [  1   1   0   0   1   7   0   7 102   4   4   1   3]
 [ 15  17   9   7   2   1   0   2  12 150  12  11  18]
 [  3   0   0   0   1   0   0   2   6   2  58   2   7]
 [  4   3   2   1   0   2   0   0   0   4   0  42   3]
 [  5   0   0   2   0   0   0   5   4   7   2   1  53]]

In [15]:
from train_domain_expert_domain_config import DomainConfig
from train_domain_expert_domain_classifier import train_domain_classifier, evaluate_on_testset


domain_config = DomainConfig(
    domain_to_super=domain_to_super_12,
    # Falls du die Reihenfolge explizit festlegen willst:
    super_labels=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]
)

# ========= 2) Pfade & Modell-ID =========

base_model_id = "deepseek-ai/deepseek-llm-7b-base"
train_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"
test_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"
output_dir = "adapters/deepseek-liar-statement-domain-lora_12Classes"

# ========= 3) Training starten =========

if __name__ == "__main__":
    # Train
    train_domain_classifier(
        train_path=train_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        output_dir=output_dir,
        num_train_epochs=3,
        learning_rate=5e-4,
        per_device_train_batch_size=4,
        max_length=256,
    )

    # Eval
    evaluate_on_testset(
        test_path=test_path,
        domain_config=domain_config,
        base_model_id=base_model_id,
        lora_dir=output_dir,
    )

Super label distribution (train):
super_domain
macro_econ                  2606
institutions_elections      1798
law_crime_rights            1245
healthcare_policy           1087
jobs_labor                   764
foreign_affairs_security     651
media_meta                   571
environment_energy_infra     468
family_demographics          317
cost_of_living_housing       295
business_finance             189
public_health_crises         139
substances_gambling          110
Name: count, dtype: int64

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Example tokenized sample keys: dict_keys(['input_ids', 'attention_mask'])
Input length: 196

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

The model is already on multiple devices. Skipping the move to device specified in `args`.

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

✅ LoRA adapter & tokenizer saved to: adapters/deepseek-liar-statement-domain-lora_12Classes
Test set size: 1267
True label distribution (test):
super_domain_true
macro_econ                  316
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🧠 Routing statements: 100%|██████████| 1267/1267 [09:15<00:00,  2.28it/s]

Predicted label distribution (test):
super_domain_pred
macro_econ                  345
institutions_elections      261
law_crime_rights            142
healthcare_policy           131
foreign_affairs_security     84
jobs_labor                   79
media_meta                   71
environment_energy_infra     66
family_demographics          32
substances_gambling          19
cost_of_living_housing       19
business_finance             12
public_health_crises          6
Name: count, dtype: int64

Accuracy (super_domain) on test set: 0.686

Classification report (per superlabel):
                          precision    recall  f1-score   support

              macro_econ       0.72      0.79      0.76       316
              jobs_labor       0.53      0.39      0.45       107
        business_finance       0.42      0.22      0.29        23
  cost_of_living_housing       0.58      0.25      0.35        44
       healthcare_policy       0.76      0.87      0.81       114
    public_health_crises       0.50      0.21      0.30        14
     substances_gambling       0.53      0.77      0.62        13
     family_demographics       0.38      0.43      0.40        28
        law_crime_rights       0.72      0.78      0.75       131
  institutions_elections       0.71      0.72      0.72       256
foreign_affairs_security       0.77      0.80      0.79        81
environment_energy_infra       0.62      0.67      0.65        61
              media_meta       0.62      0.56      0.59        79

                accuracy                           0.69      1267
               macro avg       0.60      0.57      0.57      1267
            weighted avg       0.68      0.69      0.68      1267

Confusion matrix (rows=true, cols=pred):
Labels order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']
[[250  18   2   4   7   0   1   2   4  17   1   6   4]
 [ 30  42   0   0   5   0   1   1   4  20   0   2   2]
 [  9   2   5   0   2   0   1   0   1   3   0   0   0]
 [ 13   1   1  11   8   0   0   4   0   4   0   2   0]
 [  4   0   1   0  99   0   2   1   3   1   2   0   1]
 [  0   1   0   0   0   3   1   0   6   0   1   2   0]
 [  0   0   0   0   1   0  10   0   1   0   0   0   1]
 [  0   0   0   3   1   0   0  12   7   3   0   0   2]
 [  1   2   0   0   3   3   2   3 102   8   4   1   2]
 [ 21   9   1   1   3   0   0   3   5 185   8  11   9]
 [  3   0   0   0   1   0   0   1   5   3  65   0   3]
 [  5   3   2   0   1   0   0   1   0   5   0  41   3]
 [  9   1   0   0   0   0   1   4   4  12   3   1  44]]

### Train-Experts

In [16]:
import pandas as pd
SUPER_LABELS = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_12.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../2_Finetuning_Masterthesis/LIAR/preprocessed_train_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())

Super-Domain-Verteilung:
super_domain
macro_econ                  2361
institutions_elections      1798
law_crime_rights            1245
healthcare_policy           1087
jobs_labor                   764
foreign_affairs_security     651
media_meta                   571
environment_energy_infra     468
family_demographics          317
cost_of_living_housing       295
misc                         245
business_finance             189
public_health_crises         139
substances_gambling          110
Name: count, dtype: int64

In [17]:
df_all.to_csv("Results/preprocessed_train_cleaned_binary_with_super_domain_12.csv", sep="\t", index=False)

In [18]:
import pandas as pd

data_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_12.csv"

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# Sicherstellen, dass wir nur sinnvolle Zeilen haben
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Gesamtverteilung super_domain:")
print(df_all["super_domain"].value_counts())

SUPER_LABELS = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
]

# Pro Domain ein DataFrame
domain_dfs = {
    domain: df_all[df_all["super_domain"] == domain].reset_index(drop=True)
    for domain in SUPER_LABELS
}

for dom, df_dom in domain_dfs.items():
    print(f"\nDomain: {dom} -> {len(df_dom)} Beispiele")

Gesamtverteilung super_domain:
super_domain
macro_econ                  2361
institutions_elections      1798
law_crime_rights            1245
healthcare_policy           1087
jobs_labor                   764
foreign_affairs_security     651
media_meta                   571
environment_energy_infra     468
family_demographics          317
cost_of_living_housing       295
misc                         245
business_finance             189
public_health_crises         139
substances_gambling          110
Name: count, dtype: int64

Domain: macro_econ -> 2361 Beispiele

Domain: jobs_labor -> 764 Beispiele

Domain: business_finance -> 189 Beispiele

Domain: cost_of_living_housing -> 295 Beispiele

Domain: healthcare_policy -> 1087 Beispiele

Domain: public_health_crises -> 139 Beispiele

Domain: substances_gambling -> 110 Beispiele

Domain: family_demographics -> 317 Beispiele

Domain: law_crime_rights -> 1245 Beispiele

Domain: institutions_elections -> 1798 Beispiele

Domain: foreign_affairs_security -> 651 Beispiele

Domain: environment_energy_infra -> 468 Beispiele

Domain: media_meta -> 571 Beispiele

In [19]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_12.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ],
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/Llama_experts_12Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: macro_econ ===
Samples: 2361

Map:   0%|          | 0/2361 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/888 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'macro_econ' saved to adapters/Llama_experts_12Classes/macro_econ

=== Training expert for domain: jobs_labor ===
Samples: 764

Map:   0%|          | 0/764 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/288 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'jobs_labor' saved to adapters/Llama_experts_12Classes/jobs_labor

=== Training expert for domain: business_finance ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'business_finance' saved to adapters/Llama_experts_12Classes/business_finance

=== Training expert for domain: cost_of_living_housing ===
Samples: 295

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/111 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'cost_of_living_housing' saved to adapters/Llama_experts_12Classes/cost_of_living_housing

=== Training expert for domain: healthcare_policy ===
Samples: 1087

Map:   0%|          | 0/1087 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/408 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'healthcare_policy' saved to adapters/Llama_experts_12Classes/healthcare_policy

=== Training expert for domain: public_health_crises ===
Samples: 139

Map:   0%|          | 0/139 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/54 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'public_health_crises' saved to adapters/Llama_experts_12Classes/public_health_crises

=== Training expert for domain: substances_gambling ===
Samples: 110

Map:   0%|          | 0/110 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/42 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'substances_gambling' saved to adapters/Llama_experts_12Classes/substances_gambling

=== Training expert for domain: family_demographics ===
Samples: 317

Map:   0%|          | 0/317 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/120 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'family_demographics' saved to adapters/Llama_experts_12Classes/family_demographics

=== Training expert for domain: law_crime_rights ===
Samples: 1245

Map:   0%|          | 0/1245 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/468 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_crime_rights' saved to adapters/Llama_experts_12Classes/law_crime_rights

=== Training expert for domain: institutions_elections ===
Samples: 1798

Map:   0%|          | 0/1798 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/675 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'institutions_elections' saved to adapters/Llama_experts_12Classes/institutions_elections

=== Training expert for domain: foreign_affairs_security ===
Samples: 651

Map:   0%|          | 0/651 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/246 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_affairs_security' saved to adapters/Llama_experts_12Classes/foreign_affairs_security

=== Training expert for domain: environment_energy_infra ===
Samples: 468

Map:   0%|          | 0/468 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy_infra' saved to adapters/Llama_experts_12Classes/environment_energy_infra

=== Training expert for domain: media_meta ===
Samples: 571

Map:   0%|          | 0/571 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 20,971,520 || all params: 8,051,232,768 || trainable%: 0.2605

🚀 Training:   0%|          | 0/216 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'media_meta' saved to adapters/Llama_experts_12Classes/media_meta

Fertig! Modelle gespeichert unter:
  macro_econ: adapters/Llama_experts_12Classes/macro_econ
  jobs_labor: adapters/Llama_experts_12Classes/jobs_labor
  business_finance: adapters/Llama_experts_12Classes/business_finance
  cost_of_living_housing: adapters/Llama_experts_12Classes/cost_of_living_housing
  healthcare_policy: adapters/Llama_experts_12Classes/healthcare_policy
  public_health_crises: adapters/Llama_experts_12Classes/public_health_crises
  substances_gambling: adapters/Llama_experts_12Classes/substances_gambling
  family_demographics: adapters/Llama_experts_12Classes/family_demographics
  law_crime_rights: adapters/Llama_experts_12Classes/law_crime_rights
  institutions_elections: adapters/Llama_experts_12Classes/institutions_elections
  foreign_affairs_security: adapters/Llama_experts_12Classes/foreign_affairs_security
  environment_energy_infra: adapters/Llama_experts_12Classes/environment_energy_infra
  media_meta: adapters/Llama_experts_12Classes/media_meta

In [20]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_12.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ],
    base_model_id="google/gemma-7b-it",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/gemma_experts_12Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: macro_econ ===
Samples: 2361

Map:   0%|          | 0/2361 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/888 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'macro_econ' saved to adapters/gemma_experts_12Classes/macro_econ

=== Training expert for domain: jobs_labor ===
Samples: 764

Map:   0%|          | 0/764 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/288 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'jobs_labor' saved to adapters/gemma_experts_12Classes/jobs_labor

=== Training expert for domain: business_finance ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'business_finance' saved to adapters/gemma_experts_12Classes/business_finance

=== Training expert for domain: cost_of_living_housing ===
Samples: 295

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/111 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'cost_of_living_housing' saved to adapters/gemma_experts_12Classes/cost_of_living_housing

=== Training expert for domain: healthcare_policy ===
Samples: 1087

Map:   0%|          | 0/1087 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/408 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'healthcare_policy' saved to adapters/gemma_experts_12Classes/healthcare_policy

=== Training expert for domain: public_health_crises ===
Samples: 139

Map:   0%|          | 0/139 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/54 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'public_health_crises' saved to adapters/gemma_experts_12Classes/public_health_crises

=== Training expert for domain: substances_gambling ===
Samples: 110

Map:   0%|          | 0/110 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/42 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'substances_gambling' saved to adapters/gemma_experts_12Classes/substances_gambling

=== Training expert for domain: family_demographics ===
Samples: 317

Map:   0%|          | 0/317 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/120 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'family_demographics' saved to adapters/gemma_experts_12Classes/family_demographics

=== Training expert for domain: law_crime_rights ===
Samples: 1245

Map:   0%|          | 0/1245 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/468 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_crime_rights' saved to adapters/gemma_experts_12Classes/law_crime_rights

=== Training expert for domain: institutions_elections ===
Samples: 1798

Map:   0%|          | 0/1798 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/675 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'institutions_elections' saved to adapters/gemma_experts_12Classes/institutions_elections

=== Training expert for domain: foreign_affairs_security ===
Samples: 651

Map:   0%|          | 0/651 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/246 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_affairs_security' saved to adapters/gemma_experts_12Classes/foreign_affairs_security

=== Training expert for domain: environment_energy_infra ===
Samples: 468

Map:   0%|          | 0/468 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy_infra' saved to adapters/gemma_experts_12Classes/environment_energy_infra

=== Training expert for domain: media_meta ===
Samples: 571

Map:   0%|          | 0/571 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

trainable params: 25,001,984 || all params: 8,562,682,880 || trainable%: 0.2920

🚀 Training:   0%|          | 0/216 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'media_meta' saved to adapters/gemma_experts_12Classes/media_meta

Fertig! Modelle gespeichert unter:
  macro_econ: adapters/gemma_experts_12Classes/macro_econ
  jobs_labor: adapters/gemma_experts_12Classes/jobs_labor
  business_finance: adapters/gemma_experts_12Classes/business_finance
  cost_of_living_housing: adapters/gemma_experts_12Classes/cost_of_living_housing
  healthcare_policy: adapters/gemma_experts_12Classes/healthcare_policy
  public_health_crises: adapters/gemma_experts_12Classes/public_health_crises
  substances_gambling: adapters/gemma_experts_12Classes/substances_gambling
  family_demographics: adapters/gemma_experts_12Classes/family_demographics
  law_crime_rights: adapters/gemma_experts_12Classes/law_crime_rights
  institutions_elections: adapters/gemma_experts_12Classes/institutions_elections
  foreign_affairs_security: adapters/gemma_experts_12Classes/foreign_affairs_security
  environment_energy_infra: adapters/gemma_experts_12Classes/environment_energy_infra
  media_meta: adapters/gemma_experts_12Classes/media_meta

In [21]:
# run_train_experts.py (oder Notebook-Zelle)
import sys, os
import pandas as pd

# falls du in Jupyter bist:
sys.path.append(os.getcwd())

from train_expert_expert_config import ExpertConfig
from train_expert_expert_trainer import train_all_experts

# 1) Trainingsdaten laden – EIN gemeinsamer DataFrame
train_path = "Results/preprocessed_train_cleaned_binary_with_super_domain_12.csv"

df_train = pd.read_csv(
    train_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# 2) Konfiguration der Experten (Superdomains + Spaltennamen)
config = ExpertConfig(
    super_domains=[
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ],
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    text_column="statement",
    label_column="label",
    domain_column="super_domain",
    max_length=256,
    num_train_epochs=3,
    learning_rate=5e-4,
    per_device_train_batch_size=4,
)

# 3) Output-Root – dort bekommt jede Domain seinen eigenen Unterordner
output_root = "adapters/deepseek_experts_12Classes"

saved_paths = train_all_experts(
    df=df_train,
    config=config,
    output_root=output_root,
)

print("\nFertig! Modelle gespeichert unter:")
for dom, p in saved_paths.items():
    print(f"  {dom}: {p}")

=== Training expert for domain: macro_econ ===
Samples: 2361

Map:   0%|          | 0/2361 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/888 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'macro_econ' saved to adapters/deepseek_experts_12Classes/macro_econ

=== Training expert for domain: jobs_labor ===
Samples: 764

Map:   0%|          | 0/764 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/288 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'jobs_labor' saved to adapters/deepseek_experts_12Classes/jobs_labor

=== Training expert for domain: business_finance ===
Samples: 189

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/72 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'business_finance' saved to adapters/deepseek_experts_12Classes/business_finance

=== Training expert for domain: cost_of_living_housing ===
Samples: 295

Map:   0%|          | 0/295 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/111 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'cost_of_living_housing' saved to adapters/deepseek_experts_12Classes/cost_of_living_housing

=== Training expert for domain: healthcare_policy ===
Samples: 1087

Map:   0%|          | 0/1087 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/408 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'healthcare_policy' saved to adapters/deepseek_experts_12Classes/healthcare_policy

=== Training expert for domain: public_health_crises ===
Samples: 139

Map:   0%|          | 0/139 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/54 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'public_health_crises' saved to adapters/deepseek_experts_12Classes/public_health_crises

=== Training expert for domain: substances_gambling ===
Samples: 110

Map:   0%|          | 0/110 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/42 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'substances_gambling' saved to adapters/deepseek_experts_12Classes/substances_gambling

=== Training expert for domain: family_demographics ===
Samples: 317

Map:   0%|          | 0/317 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/120 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'family_demographics' saved to adapters/deepseek_experts_12Classes/family_demographics

=== Training expert for domain: law_crime_rights ===
Samples: 1245

Map:   0%|          | 0/1245 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/468 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'law_crime_rights' saved to adapters/deepseek_experts_12Classes/law_crime_rights

=== Training expert for domain: institutions_elections ===
Samples: 1798

Map:   0%|          | 0/1798 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/675 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'institutions_elections' saved to adapters/deepseek_experts_12Classes/institutions_elections

=== Training expert for domain: foreign_affairs_security ===
Samples: 651

Map:   0%|          | 0/651 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/246 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'foreign_affairs_security' saved to adapters/deepseek_experts_12Classes/foreign_affairs_security

=== Training expert for domain: environment_energy_infra ===
Samples: 468

Map:   0%|          | 0/468 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/177 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'environment_energy_infra' saved to adapters/deepseek_experts_12Classes/environment_energy_infra

=== Training expert for domain: media_meta ===
Samples: 571

Map:   0%|          | 0/571 [00:00<?, ? examples/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 18,739,200 || all params: 6,929,104,896 || trainable%: 0.2704

🚀 Training:   0%|          | 0/216 [00:00<?, ?it/s]

✔️ Expert-LoRA for 'media_meta' saved to adapters/deepseek_experts_12Classes/media_meta

Fertig! Modelle gespeichert unter:
  macro_econ: adapters/deepseek_experts_12Classes/macro_econ
  jobs_labor: adapters/deepseek_experts_12Classes/jobs_labor
  business_finance: adapters/deepseek_experts_12Classes/business_finance
  cost_of_living_housing: adapters/deepseek_experts_12Classes/cost_of_living_housing
  healthcare_policy: adapters/deepseek_experts_12Classes/healthcare_policy
  public_health_crises: adapters/deepseek_experts_12Classes/public_health_crises
  substances_gambling: adapters/deepseek_experts_12Classes/substances_gambling
  family_demographics: adapters/deepseek_experts_12Classes/family_demographics
  law_crime_rights: adapters/deepseek_experts_12Classes/law_crime_rights
  institutions_elections: adapters/deepseek_experts_12Classes/institutions_elections
  foreign_affairs_security: adapters/deepseek_experts_12Classes/foreign_affairs_security
  environment_energy_infra: adapters/deepseek_experts_12Classes/environment_energy_infra
  media_meta: adapters/deepseek_experts_12Classes/media_meta

### Evaluation

In [9]:
import pandas as pd
SUPER_LABELS = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
]
def map_subjects_to_super(subjects_str: str) -> str:
    """
    Map LIAR 'subjects' (comma-separated topics) to exactly one super label.
    """
    if not isinstance(subjects_str, str) or not subjects_str.strip():
        return "misc"

    domains = [s.strip() for s in subjects_str.split(",") if s.strip()]
    super_labels = {domain_to_super_12.get(d, "misc") for d in domains}

    # priorisierte Reihenfolge: erstes vorkommendes Label aus SUPER_LABELS
    for label in SUPER_LABELS:
        if label in super_labels:
            return label
    return "misc"

data_path = "../1_Basics_Masterthesis/LIAR/preprocessed_test_cleaned_binary.csv"  # anpassen falls nötig

df_all = pd.read_csv(
    data_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# super_domain aus subjects erzeugen
df_all["super_domain"] = df_all["subjects"].apply(map_subjects_to_super)

# Aufräumen
df_all = df_all.dropna(subset=["statement", "label", "super_domain"])
df_all = df_all[df_all["statement"].str.strip() != ""]
df_all = df_all[df_all["label"].isin(["True", "False"])]

print("Super-Domain-Verteilung:")
print(df_all["super_domain"].value_counts())
df_all.to_csv("Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv", sep="\t", index=False)

Super-Domain-Verteilung:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

In [10]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_12Classes",
    expert_root="adapters/Llama_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/Llama_test_predictions_with_experts_12.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [10:34<00:00,  2.00it/s]

Predicted domain distribution (router):
domain_pred_router
macro_econ                  352
institutions_elections      249
healthcare_policy           133
law_crime_rights            129
foreign_affairs_security     90
media_meta                   83
jobs_labor                   67
environment_energy_infra     67
family_demographics          32
cost_of_living_housing       23
substances_gambling          16
business_finance             14
public_health_crises         12
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: macro_econ: 100%|██████████| 352/352 [1:06:03<00:00, 11.26s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: jobs_labor: 100%|██████████| 67/67 [12:10<00:00, 10.91s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: business_finance: 100%|██████████| 14/14 [02:02<00:00,  8.72s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: cost_of_living_housing: 100%|██████████| 23/23 [04:06<00:00, 10.74s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: healthcare_policy: 100%|██████████| 133/133 [18:48<00:00,  8.49s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: public_health_crises: 100%|██████████| 12/12 [01:47<00:00,  8.98s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: substances_gambling: 100%|██████████| 16/16 [06:00<00:00, 22.52s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: family_demographics: 100%|██████████| 32/32 [05:09<00:00,  9.69s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_crime_rights: 100%|██████████| 129/129 [30:27<00:00, 14.17s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: institutions_elections: 100%|██████████| 249/249 [1:26:00<00:00, 20.72s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_affairs_security: 100%|██████████| 90/90 [14:41<00:00,  9.79s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy_infra: 100%|██████████| 67/67 [14:58<00:00, 13.41s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: media_meta: 100%|██████████| 83/83 [12:34<00:00,  9.08s/it]

Sample rows with predictions:
                                           statement            super_domain  \
0  Building a wall on the U.S . Mexico border wil...        law_crime_rights
1  Wisconsin is on pace to double the number of l...              jobs_labor
2  Says John McCain has done nothing to help the ...     family_demographics
3  Suzanne Bonamici supports a plan that will cut...       healthcare_policy
4  When asked by a reporter whether hes at the ce...  institutions_elections

              domain_pred  label verdict_pred
0        law_crime_rights   True         True
1              jobs_labor  False         True
2     family_demographics  False        False
3       healthcare_policy   True        False
4  institutions_elections  False         True

🌍 Domain routing accuracy: 0.689
Confusion matrix (rows=true, cols=pred):
[[232  14   0   4   8   0   1   2   0  10   1   5   2]
 [ 31  41   1   0   4   2   1   0   1  23   0   0   3]
 [  8   0   5   0   2   0   1   0   1   6   0   0   0]
 [ 13   1   1  15   6   0   0   2   0   3   0   2   1]
 [  2   2   0   0 100   0   2   0   4   1   1   1   1]
 [  0   0   0   0   0   4   1   0   6   1   1   1   0]
 [  0   0   0   0   3   0   7   0   2   0   0   0   1]
 [  2   0   0   3   1   0   0  12   7   1   0   0   2]
 [  0   2   0   0   3   3   1   8  95  10   5   1   3]
 [ 25   5   4   0   4   1   1   2   5 173  11  14  11]
 [  1   0   0   0   2   0   0   1   3   2  69   0   3]
 [  3   2   3   0   0   2   0   0   1   5   0  42   3]
 [  8   0   0   0   0   0   1   4   2  10   2   0  52]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.635

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.68      0.68       714
       False       0.58      0.58      0.58       553

    accuracy                           0.64      1267
   macro avg       0.63      0.63      0.63      1267
weighted avg       0.64      0.64      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[483 231]
 [231 322]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 279 acc=0.638
jobs_labor             n= 107 acc=0.626
business_finance       n=  23 acc=0.652
cost_of_living_housing n=  44 acc=0.636
healthcare_policy      n= 114 acc=0.649
public_health_crises   n=  14 acc=0.857
substances_gambling    n=  13 acc=0.538
family_demographics    n=  28 acc=0.536
law_crime_rights       n= 131 acc=0.733
institutions_elections n= 256 acc=0.559
foreign_affairs_security n=  81 acc=0.667
environment_energy_infra n=  61 acc=0.590
media_meta             n=  79 acc=0.722

💾 Saved predictions to: Results/Llama_test_predictions_with_experts_12.csv

In [ ]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_12Classes",
    expert_root="adapters/gemma_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/gemma_test_predictions_with_experts_12.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [05:32<00:00,  3.81it/s]

Predicted domain distribution (router):
domain_pred_router
macro_econ                  274
institutions_elections      200
law_crime_rights            144
healthcare_policy           123
jobs_labor                  116
media_meta                  104
foreign_affairs_security     84
environment_energy_infra     73
cost_of_living_housing       48
family_demographics          40
business_finance             34
public_health_crises         17
substances_gambling          10
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: macro_econ: 100%|██████████| 274/274 [1:47:30<00:00, 23.54s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: jobs_labor:   2%|▏         | 2/116 [00:59<51:49, 27.28s/it]

In [ ]:
from multiagent_pipeline import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_12Classes",
    expert_root="adapters/deepseek_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/deepseek_test_predictions_with_experts_12.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [09:18<00:00,  2.27it/s]

Predicted domain distribution (router):
domain_pred_router
macro_econ                  352
institutions_elections      242
law_crime_rights            145
healthcare_policy           136
foreign_affairs_security     85
media_meta                   80
jobs_labor                   72
environment_energy_infra     71
family_demographics          29
substances_gambling          18
cost_of_living_housing       18
business_finance             13
public_health_crises          6
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: macro_econ:   1%|▏         | 5/352 [00:35<39:37,  6.85s/it]

## Evalutation on Ground Truth Labels

In [1]:
import importlib
import evaluate_experts_all
importlib.reload(evaluate_experts_all)
evaluate_experts_all.main()

2026-02-28 09:39:34.117794: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

######################################################################
  Experts: backbone=llama  k=5
  Root: ./adapters/Llama_experts_5Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: socioeconomic_policy  |  n=616
  ============================================================
  Label distribution: {'True': 348, 'False': 268}

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 socioeconomic_policy:   0%|          | 0/616 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
llama k=5 socioeconomic_policy: 100%|██████████| 616/616 [01:32<00:00,  6.64it/s]

  Accuracy: 0.6494
              precision    recall  f1-score   support

        True       0.67      0.74      0.70       348
       False       0.61      0.53      0.57       268

    accuracy                           0.65       616
   macro avg       0.64      0.64      0.64       616
weighted avg       0.65      0.65      0.65       616

  Confusion matrix [True, False]:
[[258  90]
 [126 142]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 foreign_security: 100%|██████████| 122/122 [00:31<00:00,  3.91it/s]

  Accuracy: 0.6885
              precision    recall  f1-score   support

        True       0.71      0.71      0.71        65
       False       0.67      0.67      0.67        57

    accuracy                           0.69       122
   macro avg       0.69      0.69      0.69       122
weighted avg       0.69      0.69      0.69       122

  Confusion matrix [True, False]:
[[46 19]
 [19 38]]

  ============================================================
  Domain: governance_law  |  n=378
  ============================================================
  Label distribution: {'True': 212, 'False': 166}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 governance_law: 100%|██████████| 378/378 [01:28<00:00,  4.28it/s]

  Accuracy: 0.7037
              precision    recall  f1-score   support

        True       0.76      0.70      0.73       212
       False       0.65      0.71      0.68       166

    accuracy                           0.70       378
   macro avg       0.70      0.70      0.70       378
weighted avg       0.71      0.70      0.70       378

  Confusion matrix [True, False]:
[[148  64]
 [ 48 118]]

  ============================================================
  Domain: environment_science  |  n=57
  ============================================================
  Label distribution: {'True': 30, 'False': 27}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 environment_science: 100%|██████████| 57/57 [00:12<00:00,  4.50it/s]

  Accuracy: 0.6140
              precision    recall  f1-score   support

        True       0.62      0.70      0.66        30
       False       0.61      0.52      0.56        27

    accuracy                           0.61        57
   macro avg       0.61      0.61      0.61        57
weighted avg       0.61      0.61      0.61        57

  Confusion matrix [True, False]:
[[21  9]
 [13 14]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 society_culture: 100%|██████████| 61/61 [00:14<00:00,  4.32it/s]

  Accuracy: 0.6557
              precision    recall  f1-score   support

        True       0.71      0.73      0.72        37
       False       0.57      0.54      0.55        24

    accuracy                           0.66        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.65      0.66      0.65        61

  Confusion matrix [True, False]:
[[27 10]
 [11 13]]

  ============================================================
  Domain: misc  |  n=33
  ============================================================
  Label distribution: {'True': 22, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=5 misc: 100%|██████████| 33/33 [00:04<00:00,  7.96it/s]

  Accuracy: 0.6667
              precision    recall  f1-score   support

        True       0.67      1.00      0.80        22
       False       0.00      0.00      0.00        11

    accuracy                           0.67        33
   macro avg       0.33      0.50      0.40        33
weighted avg       0.44      0.67      0.53        33

  Confusion matrix [True, False]:
[[22  0]
 [11  0]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=LLAMA  k=5  |  total_samples=1267

Overall accuracy: 0.669

Overall classification report:
              precision    recall  f1-score   support

        True       0.70      0.73      0.71       714
       False       0.63      0.59      0.61       553

    accuracy                           0.67      1267
   macro avg       0.66      0.66      0.66      1267
weighted avg       0.67      0.67      0.67      1267

Overall confusion matrix (True, False):
[[522 192]
 [228 325]]

Per-domain accuracy summary:
  socioeconomic_policy      n= 616  acc=0.649
  foreign_security          n= 122  acc=0.689
  governance_law            n= 378  acc=0.704
  environment_science       n=  57  acc=0.614
  society_culture           n=  61  acc=0.656
  misc                      n=  33  acc=0.667
============================================================
  💾 Saved: Results/expert_eval_llama_k5.csv


######################################################################
  Experts: backbone=llama  k=8
  Root: ./adapters/Llama_experts_8Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: economy  |  n=473
  ============================================================
  Label distribution: {'True': 266, 'False': 207}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 economy: 100%|██████████| 473/473 [01:12<00:00,  6.49it/s]

  Accuracy: 0.6617
              precision    recall  f1-score   support

        True       0.69      0.73      0.71       266
       False       0.62      0.57      0.60       207

    accuracy                           0.66       473
   macro avg       0.66      0.65      0.65       473
weighted avg       0.66      0.66      0.66       473

  Confusion matrix [True, False]:
[[195  71]
 [ 89 118]]

  ============================================================
  Domain: health_social  |  n=143
  ============================================================
  Label distribution: {'True': 82, 'False': 61}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 health_social: 100%|██████████| 143/143 [00:34<00:00,  4.19it/s]

  Accuracy: 0.6503
              precision    recall  f1-score   support

        True       0.77      0.56      0.65        82
       False       0.57      0.77      0.65        61

    accuracy                           0.65       143
   macro avg       0.67      0.67      0.65       143
weighted avg       0.68      0.65      0.65       143

  Confusion matrix [True, False]:
[[46 36]
 [14 47]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 foreign_security: 100%|██████████| 122/122 [00:31<00:00,  3.91it/s]

  Accuracy: 0.6885
              precision    recall  f1-score   support

        True       0.71      0.71      0.71        65
       False       0.67      0.67      0.67        57

    accuracy                           0.69       122
   macro avg       0.69      0.69      0.69       122
weighted avg       0.69      0.69      0.69       122

  Confusion matrix [True, False]:
[[46 19]
 [19 38]]

  ============================================================
  Domain: law_rights  |  n=145
  ============================================================
  Label distribution: {'True': 75, 'False': 70}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 law_rights: 100%|██████████| 145/145 [00:18<00:00,  7.72it/s]

  Accuracy: 0.6483
              precision    recall  f1-score   support

        True       0.65      0.69      0.67        75
       False       0.65      0.60      0.62        70

    accuracy                           0.65       145
   macro avg       0.65      0.65      0.65       145
weighted avg       0.65      0.65      0.65       145

  Confusion matrix [True, False]:
[[52 23]
 [28 42]]

  ============================================================
  Domain: politics_government  |  n=233
  ============================================================
  Label distribution: {'True': 137, 'False': 96}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 politics_government: 100%|██████████| 233/233 [00:55<00:00,  4.20it/s]

  Accuracy: 0.6824
              precision    recall  f1-score   support

        True       0.68      0.86      0.76       137
       False       0.68      0.43      0.53        96

    accuracy                           0.68       233
   macro avg       0.68      0.64      0.64       233
weighted avg       0.68      0.68      0.66       233

  Confusion matrix [True, False]:
[[118  19]
 [ 55  41]]

  ============================================================
  Domain: environment_energy  |  n=56
  ============================================================
  Label distribution: {'True': 29, 'False': 27}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 environment_energy: 100%|██████████| 56/56 [00:07<00:00,  7.45it/s]

  Accuracy: 0.5714
              precision    recall  f1-score   support

        True       0.56      0.86      0.68        29
       False       0.64      0.26      0.37        27

    accuracy                           0.57        56
   macro avg       0.60      0.56      0.52        56
weighted avg       0.59      0.57      0.53        56

  Confusion matrix [True, False]:
[[25  4]
 [20  7]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 society_culture: 100%|██████████| 61/61 [00:07<00:00,  7.94it/s]

  Accuracy: 0.6066
              precision    recall  f1-score   support

        True       0.67      0.70      0.68        37
       False       0.50      0.46      0.48        24

    accuracy                           0.61        61
   macro avg       0.58      0.58      0.58        61
weighted avg       0.60      0.61      0.60        61

  Confusion matrix [True, False]:
[[26 11]
 [13 11]]

  ============================================================
  Domain: misc  |  n=34
  ============================================================
  Label distribution: {'True': 23, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=8 misc: 100%|██████████| 34/34 [00:04<00:00,  8.30it/s]

  Accuracy: 0.7059
              precision    recall  f1-score   support

        True       0.81      0.74      0.77        23
       False       0.54      0.64      0.58        11

    accuracy                           0.71        34
   macro avg       0.67      0.69      0.68        34
weighted avg       0.72      0.71      0.71        34

  Confusion matrix [True, False]:
[[17  6]
 [ 4  7]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=LLAMA  k=8  |  total_samples=1267

Overall accuracy: 0.660

Overall classification report:
              precision    recall  f1-score   support

        True       0.68      0.74      0.71       714
       False       0.62      0.56      0.59       553

    accuracy                           0.66      1267
   macro avg       0.65      0.65      0.65      1267
weighted avg       0.66      0.66      0.66      1267

Overall confusion matrix (True, False):
[[525 189]
 [242 311]]

Per-domain accuracy summary:
  economy                   n= 473  acc=0.662
  health_social             n= 143  acc=0.650
  foreign_security          n= 122  acc=0.689
  law_rights                n= 145  acc=0.648
  politics_government       n= 233  acc=0.682
  environment_energy        n=  56  acc=0.571
  society_culture           n=  61  acc=0.607
  misc                      n=  34  acc=0.706
============================================================
  💾 Saved: Results/expert_eval_llama_k8.csv


######################################################################
  Experts: backbone=llama  k=12
  Root: ./adapters/Llama_experts_12Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: macro_econ  |  n=279
  ============================================================
  Label distribution: {'True': 162, 'False': 117}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 macro_econ: 100%|██████████| 279/279 [01:01<00:00,  4.52it/s]

  Accuracy: 0.6559
              precision    recall  f1-score   support

        True       0.71      0.69      0.70       162
       False       0.59      0.62      0.60       117

    accuracy                           0.66       279
   macro avg       0.65      0.65      0.65       279
weighted avg       0.66      0.66      0.66       279

  Confusion matrix [True, False]:
[[111  51]
 [ 45  72]]

  ============================================================
  Domain: jobs_labor  |  n=107
  ============================================================
  Label distribution: {'True': 57, 'False': 50}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 jobs_labor: 100%|██████████| 107/107 [00:13<00:00,  7.91it/s]

  Accuracy: 0.6075
              precision    recall  f1-score   support

        True       0.61      0.74      0.67        57
       False       0.61      0.46      0.52        50

    accuracy                           0.61       107
   macro avg       0.61      0.60      0.59       107
weighted avg       0.61      0.61      0.60       107

  Confusion matrix [True, False]:
[[42 15]
 [27 23]]

  ============================================================
  Domain: business_finance  |  n=23
  ============================================================
  Label distribution: {'True': 12, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 business_finance: 100%|██████████| 23/23 [00:05<00:00,  4.29it/s]

  Accuracy: 0.8696
              precision    recall  f1-score   support

        True       0.80      1.00      0.89        12
       False       1.00      0.73      0.84        11

    accuracy                           0.87        23
   macro avg       0.90      0.86      0.87        23
weighted avg       0.90      0.87      0.87        23

  Confusion matrix [True, False]:
[[12  0]
 [ 3  8]]

  ============================================================
  Domain: cost_of_living_housing  |  n=44
  ============================================================
  Label distribution: {'True': 23, 'False': 21}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 cost_of_living_housing: 100%|██████████| 44/44 [00:05<00:00,  7.86it/s]

  Accuracy: 0.5682
              precision    recall  f1-score   support

        True       0.55      1.00      0.71        23
       False       1.00      0.10      0.17        21

    accuracy                           0.57        44
   macro avg       0.77      0.55      0.44        44
weighted avg       0.76      0.57      0.45        44

  Confusion matrix [True, False]:
[[23  0]
 [19  2]]

  ============================================================
  Domain: healthcare_policy  |  n=114
  ============================================================
  Label distribution: {'True': 60, 'False': 54}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 healthcare_policy: 100%|██████████| 114/114 [00:13<00:00,  8.22it/s]

  Accuracy: 0.6404
              precision    recall  f1-score   support

        True       0.65      0.68      0.67        60
       False       0.63      0.59      0.61        54

    accuracy                           0.64       114
   macro avg       0.64      0.64      0.64       114
weighted avg       0.64      0.64      0.64       114

  Confusion matrix [True, False]:
[[41 19]
 [22 32]]

  ============================================================
  Domain: public_health_crises  |  n=14
  ============================================================
  Label distribution: {'True': 8, 'False': 6}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 public_health_crises: 100%|██████████| 14/14 [00:01<00:00,  7.04it/s]

  Accuracy: 0.5714
              precision    recall  f1-score   support

        True       0.57      1.00      0.73         8
       False       0.00      0.00      0.00         6

    accuracy                           0.57        14
   macro avg       0.29      0.50      0.36        14
weighted avg       0.33      0.57      0.42        14

  Confusion matrix [True, False]:
[[8 0]
 [6 0]]

  ============================================================
  Domain: substances_gambling  |  n=13
  ============================================================
  Label distribution: {'True': 10, 'False': 3}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 substances_gambling: 100%|██████████| 13/13 [00:01<00:00,  8.16it/s]

  Accuracy: 0.7692
              precision    recall  f1-score   support

        True       0.77      1.00      0.87        10
       False       0.00      0.00      0.00         3

    accuracy                           0.77        13
   macro avg       0.38      0.50      0.43        13
weighted avg       0.59      0.77      0.67        13

  Confusion matrix [True, False]:
[[10  0]
 [ 3  0]]

  ============================================================
  Domain: family_demographics  |  n=28
  ============================================================
  Label distribution: {'True': 18, 'False': 10}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 family_demographics: 100%|██████████| 28/28 [00:04<00:00,  6.34it/s]

  Accuracy: 0.7500
              precision    recall  f1-score   support

        True       0.92      0.67      0.77        18
       False       0.60      0.90      0.72        10

    accuracy                           0.75        28
   macro avg       0.76      0.78      0.75        28
weighted avg       0.81      0.75      0.75        28

  Confusion matrix [True, False]:
[[12  6]
 [ 1  9]]

  ============================================================
  Domain: law_crime_rights  |  n=131
  ============================================================
  Label distribution: {'True': 72, 'False': 59}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 law_crime_rights: 100%|██████████| 131/131 [00:15<00:00,  8.27it/s]

  Accuracy: 0.7328
              precision    recall  f1-score   support

        True       0.78      0.72      0.75        72
       False       0.69      0.75      0.72        59

    accuracy                           0.73       131
   macro avg       0.73      0.73      0.73       131
weighted avg       0.74      0.73      0.73       131

  Confusion matrix [True, False]:
[[52 20]
 [15 44]]

  ============================================================
  Domain: institutions_elections  |  n=256
  ============================================================
  Label distribution: {'True': 145, 'False': 111}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 institutions_elections: 100%|██████████| 256/256 [01:00<00:00,  4.25it/s]

  Accuracy: 0.6797
              precision    recall  f1-score   support

        True       0.70      0.75      0.73       145
       False       0.64      0.59      0.61       111

    accuracy                           0.68       256
   macro avg       0.67      0.67      0.67       256
weighted avg       0.68      0.68      0.68       256

  Confusion matrix [True, False]:
[[109  36]
 [ 46  65]]

  ============================================================
  Domain: foreign_affairs_security  |  n=81
  ============================================================
  Label distribution: {'True': 46, 'False': 35}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 foreign_affairs_security: 100%|██████████| 81/81 [00:19<00:00,  4.26it/s]

  Accuracy: 0.6543
              precision    recall  f1-score   support

        True       0.72      0.63      0.67        46
       False       0.59      0.69      0.63        35

    accuracy                           0.65        81
   macro avg       0.66      0.66      0.65        81
weighted avg       0.66      0.65      0.66        81

  Confusion matrix [True, False]:
[[29 17]
 [11 24]]

  ============================================================
  Domain: environment_energy_infra  |  n=61
  ============================================================
  Label distribution: {'False': 31, 'True': 30}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 environment_energy_infra: 100%|██████████| 61/61 [00:13<00:00,  4.60it/s]

  Accuracy: 0.5902
              precision    recall  f1-score   support

        True       0.55      0.90      0.68        30
       False       0.75      0.29      0.42        31

    accuracy                           0.59        61
   macro avg       0.65      0.60      0.55        61
weighted avg       0.65      0.59      0.55        61

  Confusion matrix [True, False]:
[[27  3]
 [22  9]]

  ============================================================
  Domain: media_meta  |  n=79
  ============================================================
  Label distribution: {'True': 46, 'False': 33}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

llama k=12 media_meta: 100%|██████████| 79/79 [00:15<00:00,  5.16it/s]

  Accuracy: 0.6329
              precision    recall  f1-score   support

        True       0.67      0.72      0.69        46
       False       0.57      0.52      0.54        33

    accuracy                           0.63        79
   macro avg       0.62      0.62      0.62        79
weighted avg       0.63      0.63      0.63        79

  Confusion matrix [True, False]:
[[33 13]
 [16 17]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=LLAMA  k=12  |  total_samples=1230

Overall accuracy: 0.662

Overall classification report:
              precision    recall  f1-score   support

        True       0.68      0.74      0.71       689
       False       0.63      0.56      0.59       541

    accuracy                           0.66      1230
   macro avg       0.66      0.65      0.65      1230
weighted avg       0.66      0.66      0.66      1230

Overall confusion matrix (True, False):
[[509 180]
 [236 305]]

Per-domain accuracy summary:
  macro_econ                n= 279  acc=0.656
  jobs_labor                n= 107  acc=0.608
  business_finance          n=  23  acc=0.870
  cost_of_living_housing    n=  44  acc=0.568
  healthcare_policy         n= 114  acc=0.640
  public_health_crises      n=  14  acc=0.571
  substances_gambling       n=  13  acc=0.769
  family_demographics       n=  28  acc=0.750
  law_crime_rights          n= 131  acc=0.733
  institutions_elections    n= 256  acc=0.680
  foreign_affairs_security  n=  81  acc=0.654
  environment_energy_infra  n=  61  acc=0.590
  media_meta                n=  79  acc=0.633
============================================================
  💾 Saved: Results/expert_eval_llama_k12.csv


######################################################################
  Experts: backbone=gemma  k=5
  Root: ./adapters/gemma_experts_5Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: socioeconomic_policy  |  n=616
  ============================================================
  Label distribution: {'True': 348, 'False': 268}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 socioeconomic_policy: 100%|██████████| 616/616 [02:13<00:00,  4.61it/s]

  Accuracy: 0.6266
              precision    recall  f1-score   support

        True       0.61      0.92      0.74       348
       False       0.71      0.24      0.36       268

    accuracy                           0.63       616
   macro avg       0.66      0.58      0.55       616
weighted avg       0.65      0.63      0.57       616

  Confusion matrix [True, False]:
[[321  27]
 [203  65]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 foreign_security: 100%|██████████| 122/122 [00:28<00:00,  4.26it/s]

  Accuracy: 0.6639
              precision    recall  f1-score   support

        True       0.63      0.88      0.74        65
       False       0.75      0.42      0.54        57

    accuracy                           0.66       122
   macro avg       0.69      0.65      0.64       122
weighted avg       0.69      0.66      0.64       122

  Confusion matrix [True, False]:
[[57  8]
 [33 24]]

  ============================================================
  Domain: governance_law  |  n=378
  ============================================================
  Label distribution: {'True': 212, 'False': 166}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 governance_law: 100%|██████████| 378/378 [01:33<00:00,  4.02it/s]

  Accuracy: 0.6534
              precision    recall  f1-score   support

        True       0.63      0.91      0.75       212
       False       0.73      0.33      0.46       166

    accuracy                           0.65       378
   macro avg       0.68      0.62      0.60       378
weighted avg       0.68      0.65      0.62       378

  Confusion matrix [True, False]:
[[192  20]
 [111  55]]

  ============================================================
  Domain: environment_science  |  n=57
  ============================================================
  Label distribution: {'True': 30, 'False': 27}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 environment_science: 100%|██████████| 57/57 [00:12<00:00,  4.42it/s]

  Accuracy: 0.5789
              precision    recall  f1-score   support

        True       0.57      0.80      0.67        30
       False       0.60      0.33      0.43        27

    accuracy                           0.58        57
   macro avg       0.59      0.57      0.55        57
weighted avg       0.58      0.58      0.55        57

  Confusion matrix [True, False]:
[[24  6]
 [18  9]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 society_culture: 100%|██████████| 61/61 [00:15<00:00,  3.89it/s]

  Accuracy: 0.5738
              precision    recall  f1-score   support

        True       0.60      0.89      0.72        37
       False       0.33      0.08      0.13        24

    accuracy                           0.57        61
   macro avg       0.47      0.49      0.43        61
weighted avg       0.50      0.57      0.49        61

  Confusion matrix [True, False]:
[[33  4]
 [22  2]]

  ============================================================
  Domain: misc  |  n=33
  ============================================================
  Label distribution: {'True': 22, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=5 misc: 100%|██████████| 33/33 [00:10<00:00,  3.15it/s]

  Accuracy: 0.6061
              precision    recall  f1-score   support

        True       0.67      0.82      0.73        22
       False       0.33      0.18      0.24        11

    accuracy                           0.61        33
   macro avg       0.50      0.50      0.48        33
weighted avg       0.56      0.61      0.57        33

  Confusion matrix [True, False]:
[[18  4]
 [ 9  2]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=GEMMA  k=5  |  total_samples=1267

Overall accuracy: 0.633

Overall classification report:
              precision    recall  f1-score   support

        True       0.62      0.90      0.74       714
       False       0.69      0.28      0.40       553

    accuracy                           0.63      1267
   macro avg       0.66      0.59      0.57      1267
weighted avg       0.65      0.63      0.59      1267

Overall confusion matrix (True, False):
[[645  69]
 [396 157]]

Per-domain accuracy summary:
  socioeconomic_policy      n= 616  acc=0.627
  foreign_security          n= 122  acc=0.664
  governance_law            n= 378  acc=0.653
  environment_science       n=  57  acc=0.579
  society_culture           n=  61  acc=0.574
  misc                      n=  33  acc=0.606
============================================================
  💾 Saved: Results/expert_eval_gemma_k5.csv


######################################################################
  Experts: backbone=gemma  k=8
  Root: ./adapters/gemma_experts_8Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: economy  |  n=473
  ============================================================
  Label distribution: {'True': 266, 'False': 207}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 economy: 100%|██████████| 473/473 [01:46<00:00,  4.44it/s]

  Accuracy: 0.6279
              precision    recall  f1-score   support

        True       0.61      0.92      0.74       266
       False       0.72      0.25      0.37       207

    accuracy                           0.63       473
   macro avg       0.67      0.59      0.55       473
weighted avg       0.66      0.63      0.57       473

  Confusion matrix [True, False]:
[[246  20]
 [156  51]]

  ============================================================
  Domain: health_social  |  n=143
  ============================================================
  Label distribution: {'True': 82, 'False': 61}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 health_social: 100%|██████████| 143/143 [00:34<00:00,  4.13it/s]

  Accuracy: 0.6783
              precision    recall  f1-score   support

        True       0.67      0.88      0.76        82
       False       0.71      0.41      0.52        61

    accuracy                           0.68       143
   macro avg       0.69      0.64      0.64       143
weighted avg       0.69      0.68      0.66       143

  Confusion matrix [True, False]:
[[72 10]
 [36 25]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 foreign_security: 100%|██████████| 122/122 [00:27<00:00,  4.46it/s]

  Accuracy: 0.6393
              precision    recall  f1-score   support

        True       0.61      0.91      0.73        65
       False       0.76      0.33      0.46        57

    accuracy                           0.64       122
   macro avg       0.68      0.62      0.60       122
weighted avg       0.68      0.64      0.60       122

  Confusion matrix [True, False]:
[[59  6]
 [38 19]]

  ============================================================
  Domain: law_rights  |  n=145
  ============================================================
  Label distribution: {'True': 75, 'False': 70}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 law_rights: 100%|██████████| 145/145 [00:34<00:00,  4.21it/s]

  Accuracy: 0.6138
              precision    recall  f1-score   support

        True       0.60      0.79      0.68        75
       False       0.65      0.43      0.52        70

    accuracy                           0.61       145
   macro avg       0.62      0.61      0.60       145
weighted avg       0.62      0.61      0.60       145

  Confusion matrix [True, False]:
[[59 16]
 [40 30]]

  ============================================================
  Domain: politics_government  |  n=233
  ============================================================
  Label distribution: {'True': 137, 'False': 96}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 politics_government: 100%|██████████| 233/233 [00:51<00:00,  4.50it/s]

  Accuracy: 0.6352
              precision    recall  f1-score   support

        True       0.64      0.86      0.74       137
       False       0.61      0.31      0.41        96

    accuracy                           0.64       233
   macro avg       0.63      0.59      0.57       233
weighted avg       0.63      0.64      0.60       233

  Confusion matrix [True, False]:
[[118  19]
 [ 66  30]]

  ============================================================
  Domain: environment_energy  |  n=56
  ============================================================
  Label distribution: {'True': 29, 'False': 27}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 environment_energy: 100%|██████████| 56/56 [00:15<00:00,  3.59it/s]

  Accuracy: 0.5000
              precision    recall  f1-score   support

        True       0.51      0.93      0.66        29
       False       0.33      0.04      0.07        27

    accuracy                           0.50        56
   macro avg       0.42      0.48      0.36        56
weighted avg       0.42      0.50      0.37        56

  Confusion matrix [True, False]:
[[27  2]
 [26  1]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 society_culture: 100%|██████████| 61/61 [00:14<00:00,  4.32it/s]

  Accuracy: 0.5738
              precision    recall  f1-score   support

        True       0.61      0.84      0.70        37
       False       0.40      0.17      0.24        24

    accuracy                           0.57        61
   macro avg       0.50      0.50      0.47        61
weighted avg       0.53      0.57      0.52        61

  Confusion matrix [True, False]:
[[31  6]
 [20  4]]

  ============================================================
  Domain: misc  |  n=34
  ============================================================
  Label distribution: {'True': 23, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=8 misc: 100%|██████████| 34/34 [00:07<00:00,  4.65it/s]

  Accuracy: 0.6176
              precision    recall  f1-score   support

        True       0.68      0.83      0.75        23
       False       0.33      0.18      0.24        11

    accuracy                           0.62        34
   macro avg       0.51      0.50      0.49        34
weighted avg       0.57      0.62      0.58        34

  Confusion matrix [True, False]:
[[19  4]
 [ 9  2]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=GEMMA  k=8  |  total_samples=1267

Overall accuracy: 0.626

Overall classification report:
              precision    recall  f1-score   support

        True       0.62      0.88      0.73       714
       False       0.66      0.29      0.41       553

    accuracy                           0.63      1267
   macro avg       0.64      0.59      0.57      1267
weighted avg       0.64      0.63      0.59      1267

Overall confusion matrix (True, False):
[[631  83]
 [391 162]]

Per-domain accuracy summary:
  economy                   n= 473  acc=0.628
  health_social             n= 143  acc=0.678
  foreign_security          n= 122  acc=0.639
  law_rights                n= 145  acc=0.614
  politics_government       n= 233  acc=0.635
  environment_energy        n=  56  acc=0.500
  society_culture           n=  61  acc=0.574
  misc                      n=  34  acc=0.618
============================================================
  💾 Saved: Results/expert_eval_gemma_k8.csv


######################################################################
  Experts: backbone=gemma  k=12
  Root: ./adapters/gemma_experts_12Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: macro_econ  |  n=279
  ============================================================
  Label distribution: {'True': 162, 'False': 117}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 macro_econ: 100%|██████████| 279/279 [01:00<00:00,  4.60it/s]

  Accuracy: 0.6452
              precision    recall  f1-score   support

        True       0.64      0.90      0.75       162
       False       0.67      0.30      0.41       117

    accuracy                           0.65       279
   macro avg       0.66      0.60      0.58       279
weighted avg       0.65      0.65      0.61       279

  Confusion matrix [True, False]:
[[145  17]
 [ 82  35]]

  ============================================================
  Domain: jobs_labor  |  n=107
  ============================================================
  Label distribution: {'True': 57, 'False': 50}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 jobs_labor: 100%|██████████| 107/107 [00:22<00:00,  4.72it/s]

  Accuracy: 0.6262
              precision    recall  f1-score   support

        True       0.59      0.96      0.73        57
       False       0.86      0.24      0.38        50

    accuracy                           0.63       107
   macro avg       0.72      0.60      0.55       107
weighted avg       0.72      0.63      0.57       107

  Confusion matrix [True, False]:
[[55  2]
 [38 12]]

  ============================================================
  Domain: business_finance  |  n=23
  ============================================================
  Label distribution: {'True': 12, 'False': 11}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 business_finance: 100%|██████████| 23/23 [00:07<00:00,  2.95it/s]

  Accuracy: 0.5217
              precision    recall  f1-score   support

        True       0.52      0.92      0.67        12
       False       0.50      0.09      0.15        11

    accuracy                           0.52        23
   macro avg       0.51      0.50      0.41        23
weighted avg       0.51      0.52      0.42        23

  Confusion matrix [True, False]:
[[11  1]
 [10  1]]

  ============================================================
  Domain: cost_of_living_housing  |  n=44
  ============================================================
  Label distribution: {'True': 23, 'False': 21}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 cost_of_living_housing: 100%|██████████| 44/44 [00:11<00:00,  3.87it/s]

  Accuracy: 0.6364
              precision    recall  f1-score   support

        True       0.59      1.00      0.74        23
       False       1.00      0.24      0.38        21

    accuracy                           0.64        44
   macro avg       0.79      0.62      0.56        44
weighted avg       0.79      0.64      0.57        44

  Confusion matrix [True, False]:
[[23  0]
 [16  5]]

  ============================================================
  Domain: healthcare_policy  |  n=114
  ============================================================
  Label distribution: {'True': 60, 'False': 54}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 healthcare_policy: 100%|██████████| 114/114 [00:24<00:00,  4.68it/s]

  Accuracy: 0.6140
              precision    recall  f1-score   support

        True       0.59      0.90      0.71        60
       False       0.73      0.30      0.42        54

    accuracy                           0.61       114
   macro avg       0.66      0.60      0.57       114
weighted avg       0.65      0.61      0.57       114

  Confusion matrix [True, False]:
[[54  6]
 [38 16]]

  ============================================================
  Domain: public_health_crises  |  n=14
  ============================================================
  Label distribution: {'True': 8, 'False': 6}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 public_health_crises: 100%|██████████| 14/14 [00:02<00:00,  4.68it/s]

  Accuracy: 0.5714
              precision    recall  f1-score   support

        True       0.57      1.00      0.73         8
       False       0.00      0.00      0.00         6

    accuracy                           0.57        14
   macro avg       0.29      0.50      0.36        14
weighted avg       0.33      0.57      0.42        14

  Confusion matrix [True, False]:
[[8 0]
 [6 0]]

  ============================================================
  Domain: substances_gambling  |  n=13
  ============================================================
  Label distribution: {'True': 10, 'False': 3}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 substances_gambling: 100%|██████████| 13/13 [00:02<00:00,  4.65it/s]

  Accuracy: 0.6154
              precision    recall  f1-score   support

        True       0.73      0.80      0.76        10
       False       0.00      0.00      0.00         3

    accuracy                           0.62        13
   macro avg       0.36      0.40      0.38        13
weighted avg       0.56      0.62      0.59        13

  Confusion matrix [True, False]:
[[8 2]
 [3 0]]

  ============================================================
  Domain: family_demographics  |  n=28
  ============================================================
  Label distribution: {'True': 18, 'False': 10}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 family_demographics: 100%|██████████| 28/28 [00:05<00:00,  4.68it/s]

  Accuracy: 0.6071
              precision    recall  f1-score   support

        True       0.63      0.94      0.76        18
       False       0.00      0.00      0.00        10

    accuracy                           0.61        28
   macro avg       0.31      0.47      0.38        28
weighted avg       0.40      0.61      0.49        28

  Confusion matrix [True, False]:
[[17  1]
 [10  0]]

  ============================================================
  Domain: law_crime_rights  |  n=131
  ============================================================
  Label distribution: {'True': 72, 'False': 59}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 law_crime_rights: 100%|██████████| 131/131 [00:28<00:00,  4.52it/s]

  Accuracy: 0.6641
              precision    recall  f1-score   support

        True       0.65      0.83      0.73        72
       False       0.69      0.46      0.55        59

    accuracy                           0.66       131
   macro avg       0.67      0.65      0.64       131
weighted avg       0.67      0.66      0.65       131

  Confusion matrix [True, False]:
[[60 12]
 [32 27]]

  ============================================================
  Domain: institutions_elections  |  n=256
  ============================================================
  Label distribution: {'True': 145, 'False': 111}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 institutions_elections: 100%|██████████| 256/256 [00:55<00:00,  4.60it/s]

  Accuracy: 0.6328
              precision    recall  f1-score   support

        True       0.62      0.90      0.73       145
       False       0.68      0.29      0.41       111

    accuracy                           0.63       256
   macro avg       0.65      0.59      0.57       256
weighted avg       0.65      0.63      0.59       256

  Confusion matrix [True, False]:
[[130  15]
 [ 79  32]]

  ============================================================
  Domain: foreign_affairs_security  |  n=81
  ============================================================
  Label distribution: {'True': 46, 'False': 35}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 foreign_affairs_security: 100%|██████████| 81/81 [00:21<00:00,  3.78it/s]

  Accuracy: 0.5679
              precision    recall  f1-score   support

        True       0.61      0.65      0.63        46
       False       0.50      0.46      0.48        35

    accuracy                           0.57        81
   macro avg       0.56      0.55      0.55        81
weighted avg       0.56      0.57      0.57        81

  Confusion matrix [True, False]:
[[30 16]
 [19 16]]

  ============================================================
  Domain: environment_energy_infra  |  n=61
  ============================================================
  Label distribution: {'False': 31, 'True': 30}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 environment_energy_infra: 100%|██████████| 61/61 [00:13<00:00,  4.69it/s]

  Accuracy: 0.5410
              precision    recall  f1-score   support

        True       0.52      0.87      0.65        30
       False       0.64      0.23      0.33        31

    accuracy                           0.54        61
   macro avg       0.58      0.55      0.49        61
weighted avg       0.58      0.54      0.49        61

  Confusion matrix [True, False]:
[[26  4]
 [24  7]]

  ============================================================
  Domain: media_meta  |  n=79
  ============================================================
  Label distribution: {'True': 46, 'False': 33}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

gemma k=12 media_meta: 100%|██████████| 79/79 [00:20<00:00,  3.92it/s]

  Accuracy: 0.5823
              precision    recall  f1-score   support

        True       0.61      0.80      0.69        46
       False       0.50      0.27      0.35        33

    accuracy                           0.58        79
   macro avg       0.55      0.54      0.52        79
weighted avg       0.56      0.58      0.55        79

  Confusion matrix [True, False]:
[[37  9]
 [24  9]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=GEMMA  k=12  |  total_samples=1230

Overall accuracy: 0.621

Overall classification report:
              precision    recall  f1-score   support

        True       0.61      0.88      0.72       689
       False       0.65      0.30      0.41       541

    accuracy                           0.62      1230
   macro avg       0.63      0.59      0.56      1230
weighted avg       0.63      0.62      0.58      1230

Overall confusion matrix (True, False):
[[604  85]
 [381 160]]

Per-domain accuracy summary:
  macro_econ                n= 279  acc=0.645
  jobs_labor                n= 107  acc=0.626
  business_finance          n=  23  acc=0.522
  cost_of_living_housing    n=  44  acc=0.636
  healthcare_policy         n= 114  acc=0.614
  public_health_crises      n=  14  acc=0.571
  substances_gambling       n=  13  acc=0.615
  family_demographics       n=  28  acc=0.607
  law_crime_rights          n= 131  acc=0.664
  institutions_elections    n= 256  acc=0.633
  foreign_affairs_security  n=  81  acc=0.568
  environment_energy_infra  n=  61  acc=0.541
  media_meta                n=  79  acc=0.582
============================================================
  💾 Saved: Results/expert_eval_gemma_k12.csv


######################################################################
  Experts: backbone=deepseek  k=5
  Root: ./adapters/deepseek_experts_5Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: socioeconomic_policy  |  n=616
  ============================================================
  Label distribution: {'True': 348, 'False': 268}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 socioeconomic_policy: 100%|██████████| 616/616 [02:19<00:00,  4.43it/s]

  Accuracy: 0.6737
              precision    recall  f1-score   support

        True       0.65      0.89      0.76       348
       False       0.74      0.39      0.51       268

    accuracy                           0.67       616
   macro avg       0.70      0.64      0.63       616
weighted avg       0.69      0.67      0.65       616

  Confusion matrix [True, False]:
[[311  37]
 [164 104]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 foreign_security: 100%|██████████| 122/122 [00:29<00:00,  4.15it/s]

  Accuracy: 0.6148
              precision    recall  f1-score   support

        True       0.58      0.98      0.73        65
       False       0.92      0.19      0.32        57

    accuracy                           0.61       122
   macro avg       0.75      0.59      0.53       122
weighted avg       0.74      0.61      0.54       122

  Confusion matrix [True, False]:
[[64  1]
 [46 11]]

  ============================================================
  Domain: governance_law  |  n=378
  ============================================================
  Label distribution: {'True': 212, 'False': 166}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 governance_law: 100%|██████████| 378/378 [01:26<00:00,  4.35it/s]

  Accuracy: 0.6746
              precision    recall  f1-score   support

        True       0.71      0.71      0.71       212
       False       0.63      0.63      0.63       166

    accuracy                           0.67       378
   macro avg       0.67      0.67      0.67       378
weighted avg       0.67      0.67      0.67       378

  Confusion matrix [True, False]:
[[150  62]
 [ 61 105]]

  ============================================================
  Domain: environment_science  |  n=57
  ============================================================
  Label distribution: {'True': 30, 'False': 27}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 environment_science: 100%|██████████| 57/57 [00:13<00:00,  4.35it/s]

  Accuracy: 0.5263
              precision    recall  f1-score   support

        True       0.53      1.00      0.69        30
       False       0.00      0.00      0.00        27

    accuracy                           0.53        57
   macro avg       0.26      0.50      0.34        57
weighted avg       0.28      0.53      0.36        57

  Confusion matrix [True, False]:
[[30  0]
 [27  0]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 society_culture: 100%|██████████| 61/61 [00:13<00:00,  4.43it/s]

  Accuracy: 0.6066
              precision    recall  f1-score   support

        True       0.61      1.00      0.76        37
       False       0.00      0.00      0.00        24

    accuracy                           0.61        61
   macro avg       0.30      0.50      0.38        61
weighted avg       0.37      0.61      0.46        61

  Confusion matrix [True, False]:
[[37  0]
 [24  0]]

  ============================================================
  Domain: misc  |  n=33
  ============================================================
  Label distribution: {'True': 22, 'False': 11}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=5 misc: 100%|██████████| 33/33 [00:07<00:00,  4.18it/s]

  Accuracy: 0.6667
              precision    recall  f1-score   support

        True       0.67      1.00      0.80        22
       False       0.00      0.00      0.00        11

    accuracy                           0.67        33
   macro avg       0.33      0.50      0.40        33
weighted avg       0.44      0.67      0.53        33

  Confusion matrix [True, False]:
[[22  0]
 [11  0]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=DEEPSEEK  k=5  |  total_samples=1267

Overall accuracy: 0.658

Overall classification report:
              precision    recall  f1-score   support

        True       0.65      0.86      0.74       714
       False       0.69      0.40      0.50       553

    accuracy                           0.66      1267
   macro avg       0.67      0.63      0.62      1267
weighted avg       0.67      0.66      0.64      1267

Overall confusion matrix (True, False):
[[614 100]
 [333 220]]

Per-domain accuracy summary:
  socioeconomic_policy      n= 616  acc=0.674
  foreign_security          n= 122  acc=0.615
  governance_law            n= 378  acc=0.675
  environment_science       n=  57  acc=0.526
  society_culture           n=  61  acc=0.607
  misc                      n=  33  acc=0.667
============================================================
  💾 Saved: Results/expert_eval_deepseek_k5.csv


######################################################################
  Experts: backbone=deepseek  k=8
  Root: ./adapters/deepseek_experts_8Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: economy  |  n=473
  ============================================================
  Label distribution: {'True': 266, 'False': 207}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 economy: 100%|██████████| 473/473 [01:48<00:00,  4.35it/s]

  Accuracy: 0.6765
              precision    recall  f1-score   support

        True       0.66      0.86      0.75       266
       False       0.71      0.44      0.55       207

    accuracy                           0.68       473
   macro avg       0.69      0.65      0.65       473
weighted avg       0.68      0.68      0.66       473

  Confusion matrix [True, False]:
[[228  38]
 [115  92]]

  ============================================================
  Domain: health_social  |  n=143
  ============================================================
  Label distribution: {'True': 82, 'False': 61}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 health_social: 100%|██████████| 143/143 [00:32<00:00,  4.37it/s]

  Accuracy: 0.6923
              precision    recall  f1-score   support

        True       0.68      0.87      0.76        82
       False       0.72      0.46      0.56        61

    accuracy                           0.69       143
   macro avg       0.70      0.66      0.66       143
weighted avg       0.70      0.69      0.68       143

  Confusion matrix [True, False]:
[[71 11]
 [33 28]]

  ============================================================
  Domain: foreign_security  |  n=122
  ============================================================
  Label distribution: {'True': 65, 'False': 57}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 foreign_security: 100%|██████████| 122/122 [00:28<00:00,  4.32it/s]

  Accuracy: 0.6148
              precision    recall  f1-score   support

        True       0.58      0.98      0.73        65
       False       0.92      0.19      0.32        57

    accuracy                           0.61       122
   macro avg       0.75      0.59      0.53       122
weighted avg       0.74      0.61      0.54       122

  Confusion matrix [True, False]:
[[64  1]
 [46 11]]

  ============================================================
  Domain: law_rights  |  n=145
  ============================================================
  Label distribution: {'True': 75, 'False': 70}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 law_rights: 100%|██████████| 145/145 [00:31<00:00,  4.55it/s]

  Accuracy: 0.5655
              precision    recall  f1-score   support

        True       0.54      0.97      0.70        75
       False       0.82      0.13      0.22        70

    accuracy                           0.57       145
   macro avg       0.68      0.55      0.46       145
weighted avg       0.68      0.57      0.47       145

  Confusion matrix [True, False]:
[[73  2]
 [61  9]]

  ============================================================
  Domain: politics_government  |  n=233
  ============================================================
  Label distribution: {'True': 137, 'False': 96}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 politics_government: 100%|██████████| 233/233 [00:52<00:00,  4.48it/s]

  Accuracy: 0.5966
              precision    recall  f1-score   support

        True       0.59      1.00      0.74       137
       False       1.00      0.02      0.04        96

    accuracy                           0.60       233
   macro avg       0.80      0.51      0.39       233
weighted avg       0.76      0.60      0.45       233

  Confusion matrix [True, False]:
[[137   0]
 [ 94   2]]

  ============================================================
  Domain: environment_energy  |  n=56
  ============================================================
  Label distribution: {'True': 29, 'False': 27}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 environment_energy: 100%|██████████| 56/56 [00:12<00:00,  4.36it/s]

  Accuracy: 0.5179
              precision    recall  f1-score   support

        True       0.52      1.00      0.68        29
       False       0.00      0.00      0.00        27

    accuracy                           0.52        56
   macro avg       0.26      0.50      0.34        56
weighted avg       0.27      0.52      0.35        56

  Confusion matrix [True, False]:
[[29  0]
 [27  0]]

  ============================================================
  Domain: society_culture  |  n=61
  ============================================================
  Label distribution: {'True': 37, 'False': 24}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 society_culture: 100%|██████████| 61/61 [00:13<00:00,  4.61it/s]

  Accuracy: 0.6066
              precision    recall  f1-score   support

        True       0.61      1.00      0.76        37
       False       0.00      0.00      0.00        24

    accuracy                           0.61        61
   macro avg       0.30      0.50      0.38        61
weighted avg       0.37      0.61      0.46        61

  Confusion matrix [True, False]:
[[37  0]
 [24  0]]

  ============================================================
  Domain: misc  |  n=34
  ============================================================
  Label distribution: {'True': 23, 'False': 11}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=8 misc: 100%|██████████| 34/34 [00:07<00:00,  4.42it/s]

  Accuracy: 0.6765
              precision    recall  f1-score   support

        True       0.68      1.00      0.81        23
       False       0.00      0.00      0.00        11

    accuracy                           0.68        34
   macro avg       0.34      0.50      0.40        34
weighted avg       0.46      0.68      0.55        34

  Confusion matrix [True, False]:
[[23  0]
 [11  0]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=DEEPSEEK  k=8  |  total_samples=1267

Overall accuracy: 0.635

Overall classification report:
              precision    recall  f1-score   support

        True       0.62      0.93      0.74       714
       False       0.73      0.26      0.38       553

    accuracy                           0.63      1267
   macro avg       0.67      0.59      0.56      1267
weighted avg       0.67      0.63      0.58      1267

Overall confusion matrix (True, False):
[[662  52]
 [411 142]]

Per-domain accuracy summary:
  economy                   n= 473  acc=0.676
  health_social             n= 143  acc=0.692
  foreign_security          n= 122  acc=0.615
  law_rights                n= 145  acc=0.566
  politics_government       n= 233  acc=0.597
  environment_energy        n=  56  acc=0.518
  society_culture           n=  61  acc=0.607
  misc                      n=  34  acc=0.676
============================================================
  💾 Saved: Results/expert_eval_deepseek_k8.csv


######################################################################
  Experts: backbone=deepseek  k=12
  Root: ./adapters/deepseek_experts_12Classes
######################################################################
  Full test set size: 1267

  ============================================================
  Domain: macro_econ  |  n=279
  ============================================================
  Label distribution: {'True': 162, 'False': 117}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 macro_econ: 100%|██████████| 279/279 [01:02<00:00,  4.46it/s]

  Accuracy: 0.6631
              precision    recall  f1-score   support

        True       0.66      0.88      0.75       162
       False       0.69      0.36      0.47       117

    accuracy                           0.66       279
   macro avg       0.67      0.62      0.61       279
weighted avg       0.67      0.66      0.63       279

  Confusion matrix [True, False]:
[[143  19]
 [ 75  42]]

  ============================================================
  Domain: jobs_labor  |  n=107
  ============================================================
  Label distribution: {'True': 57, 'False': 50}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 jobs_labor: 100%|██████████| 107/107 [00:24<00:00,  4.40it/s]

  Accuracy: 0.5327
              precision    recall  f1-score   support

        True       0.53      1.00      0.70        57
       False       0.00      0.00      0.00        50

    accuracy                           0.53       107
   macro avg       0.27      0.50      0.35       107
weighted avg       0.28      0.53      0.37       107

  Confusion matrix [True, False]:
[[57  0]
 [50  0]]

  ============================================================
  Domain: business_finance  |  n=23
  ============================================================
  Label distribution: {'True': 12, 'False': 11}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 business_finance: 100%|██████████| 23/23 [00:05<00:00,  4.40it/s]

  Accuracy: 0.5217
              precision    recall  f1-score   support

        True       0.52      1.00      0.69        12
       False       0.00      0.00      0.00        11

    accuracy                           0.52        23
   macro avg       0.26      0.50      0.34        23
weighted avg       0.27      0.52      0.36        23

  Confusion matrix [True, False]:
[[12  0]
 [11  0]]

  ============================================================
  Domain: cost_of_living_housing  |  n=44
  ============================================================
  Label distribution: {'True': 23, 'False': 21}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 cost_of_living_housing: 100%|██████████| 44/44 [00:10<00:00,  4.15it/s]

  Accuracy: 0.5227
              precision    recall  f1-score   support

        True       0.52      1.00      0.69        23
       False       0.00      0.00      0.00        21

    accuracy                           0.52        44
   macro avg       0.26      0.50      0.34        44
weighted avg       0.27      0.52      0.36        44

  Confusion matrix [True, False]:
[[23  0]
 [21  0]]

  ============================================================
  Domain: healthcare_policy  |  n=114
  ============================================================
  Label distribution: {'True': 60, 'False': 54}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 healthcare_policy: 100%|██████████| 114/114 [00:24<00:00,  4.60it/s]

  Accuracy: 0.6667
              precision    recall  f1-score   support

        True       0.63      0.87      0.73        60
       False       0.75      0.44      0.56        54

    accuracy                           0.67       114
   macro avg       0.69      0.66      0.65       114
weighted avg       0.69      0.67      0.65       114

  Confusion matrix [True, False]:
[[52  8]
 [30 24]]

  ============================================================
  Domain: public_health_crises  |  n=14
  ============================================================
  Label distribution: {'True': 8, 'False': 6}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 public_health_crises: 100%|██████████| 14/14 [00:03<00:00,  4.60it/s]

  Accuracy: 0.5714
              precision    recall  f1-score   support

        True       0.57      1.00      0.73         8
       False       0.00      0.00      0.00         6

    accuracy                           0.57        14
   macro avg       0.29      0.50      0.36        14
weighted avg       0.33      0.57      0.42        14

  Confusion matrix [True, False]:
[[8 0]
 [6 0]]

  ============================================================
  Domain: substances_gambling  |  n=13
  ============================================================
  Label distribution: {'True': 10, 'False': 3}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 substances_gambling: 100%|██████████| 13/13 [00:02<00:00,  4.41it/s]

  Accuracy: 0.3077
              precision    recall  f1-score   support

        True       0.67      0.20      0.31        10
       False       0.20      0.67      0.31         3

    accuracy                           0.31        13
   macro avg       0.43      0.43      0.31        13
weighted avg       0.56      0.31      0.31        13

  Confusion matrix [True, False]:
[[2 8]
 [1 2]]

  ============================================================
  Domain: family_demographics  |  n=28
  ============================================================
  Label distribution: {'True': 18, 'False': 10}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 family_demographics: 100%|██████████| 28/28 [00:06<00:00,  4.58it/s]

  Accuracy: 0.6429
              precision    recall  f1-score   support

        True       0.64      1.00      0.78        18
       False       0.00      0.00      0.00        10

    accuracy                           0.64        28
   macro avg       0.32      0.50      0.39        28
weighted avg       0.41      0.64      0.50        28

  Confusion matrix [True, False]:
[[18  0]
 [10  0]]

  ============================================================
  Domain: law_crime_rights  |  n=131
  ============================================================
  Label distribution: {'True': 72, 'False': 59}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 law_crime_rights: 100%|██████████| 131/131 [00:30<00:00,  4.31it/s]

  Accuracy: 0.6718
              precision    recall  f1-score   support

        True       0.64      0.92      0.75        72
       False       0.79      0.37      0.51        59

    accuracy                           0.67       131
   macro avg       0.71      0.64      0.63       131
weighted avg       0.71      0.67      0.64       131

  Confusion matrix [True, False]:
[[66  6]
 [37 22]]

  ============================================================
  Domain: institutions_elections  |  n=256
  ============================================================
  Label distribution: {'True': 145, 'False': 111}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 institutions_elections: 100%|██████████| 256/256 [00:55<00:00,  4.58it/s]

  Accuracy: 0.6289
              precision    recall  f1-score   support

        True       0.61      0.98      0.75       145
       False       0.86      0.17      0.29       111

    accuracy                           0.63       256
   macro avg       0.74      0.58      0.52       256
weighted avg       0.72      0.63      0.55       256

  Confusion matrix [True, False]:
[[142   3]
 [ 92  19]]

  ============================================================
  Domain: foreign_affairs_security  |  n=81
  ============================================================
  Label distribution: {'True': 46, 'False': 35}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 foreign_affairs_security: 100%|██████████| 81/81 [00:18<00:00,  4.34it/s]

  Accuracy: 0.5679
              precision    recall  f1-score   support

        True       0.57      1.00      0.72        46
       False       0.00      0.00      0.00        35

    accuracy                           0.57        81
   macro avg       0.28      0.50      0.36        81
weighted avg       0.32      0.57      0.41        81

  Confusion matrix [True, False]:
[[46  0]
 [35  0]]

  ============================================================
  Domain: environment_energy_infra  |  n=61
  ============================================================
  Label distribution: {'False': 31, 'True': 30}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 environment_energy_infra: 100%|██████████| 61/61 [00:13<00:00,  4.43it/s]

  Accuracy: 0.4918
              precision    recall  f1-score   support

        True       0.49      1.00      0.66        30
       False       0.00      0.00      0.00        31

    accuracy                           0.49        61
   macro avg       0.25      0.50      0.33        61
weighted avg       0.24      0.49      0.32        61

  Confusion matrix [True, False]:
[[30  0]
 [31  0]]

  ============================================================
  Domain: media_meta  |  n=79
  ============================================================
  Label distribution: {'True': 46, 'False': 33}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

deepseek k=12 media_meta: 100%|██████████| 79/79 [00:17<00:00,  4.45it/s]

  Accuracy: 0.5823
              precision    recall  f1-score   support

        True       0.59      0.93      0.72        46
       False       0.50      0.09      0.15        33

    accuracy                           0.58        79
   macro avg       0.54      0.51      0.44        79
weighted avg       0.55      0.58      0.49        79

  Confusion matrix [True, False]:
[[43  3]
 [30  3]]

============================================================
===== Gesamt-Performance über alle Domains =====
Backbone=DEEPSEEK  k=12  |  total_samples=1230

Overall accuracy: 0.613

Overall classification report:
              precision    recall  f1-score   support

        True       0.60      0.93      0.73       689
       False       0.70      0.21      0.32       541

    accuracy                           0.61      1230
   macro avg       0.65      0.57      0.52      1230
weighted avg       0.65      0.61      0.55      1230

Overall confusion matrix (True, False):
[[642  47]
 [429 112]]

Per-domain accuracy summary:
  macro_econ                n= 279  acc=0.663
  jobs_labor                n= 107  acc=0.533
  business_finance          n=  23  acc=0.522
  cost_of_living_housing    n=  44  acc=0.523
  healthcare_policy         n= 114  acc=0.667
  public_health_crises      n=  14  acc=0.571
  substances_gambling       n=  13  acc=0.308
  family_demographics       n=  28  acc=0.643
  law_crime_rights          n= 131  acc=0.672
  institutions_elections    n= 256  acc=0.629
  foreign_affairs_security  n=  81  acc=0.568
  environment_energy_infra  n=  61  acc=0.492
  media_meta                n=  79  acc=0.582
============================================================
  💾 Saved: Results/expert_eval_deepseek_k12.csv


======================================================================
FULL SUMMARY — per (backbone, k)
======================================================================
backbone  k  n_eval  accuracy  macro_f1
   llama  5    1267    0.6685    0.6603
   llama  8    1267    0.6598    0.6498
   llama 12    1230    0.6618    0.6522
   gemma  5    1267    0.6330    0.5691
   gemma  8    1267    0.6259    0.5665
   gemma 12    1230    0.6211    0.5644
deepseek  5    1267    0.6582    0.6217
deepseek  8    1267    0.6346    0.5605
deepseek 12    1230    0.6130    0.5248


BACKBONE-LEVEL SUMMARY (mean across k=5,8,12)
backbone  total_samples  mean_accuracy  mean_macro_f1
deepseek           3764         0.6353         0.5690
   gemma           3764         0.6267         0.5667
   llama           3764         0.6634         0.6541

💾 All summaries saved to Results/

## Conclusion

In [1]:
from evaluate_domainrouter import evaluate_all_verbose

SUPER_LABELS_5 = [        
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
        ]
SUPER_LABELS_8 = [        
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
        ]
SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]

summary = evaluate_all_verbose(
    folder="Results",
    super_labels_by_k={5: SUPER_LABELS_5, 8: SUPER_LABELS_8, 12: SUPER_LABELS_12},
)
summary

====================================================================================================
Llama_test_predictions_with_experts_12.csv   |   model=llama   |   k=12
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  352
institutions_elections      249
healthcare_policy           133
law_crime_rights            129
foreign_affairs_security     90
media_meta                   83
jobs_labor                   67
environment_energy_infra     67
family_demographics          32
cost_of_living_housing       23
substances_gambling          16
business_finance             14
public_health_crises         12
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.689
Confusion matrix (rows=true, cols=pred):
[[232  14   0   4   8   0   1   2   0  10   1   5   2]
 [ 31  41   1   0   4   2   1   0   1  23   0   0   3]
 [  8   0   5   0   2   0   1   0   1   6   0   0   0]
 [ 13   1   1  15   6   0   0   2   0   3   0   2   1]
 [  2   2   0   0 100   0   2   0   4   1   1   1   1]
 [  0   0   0   0   0   4   1   0   6   1   1   1   0]
 [  0   0   0   0   3   0   7   0   2   0   0   0   1]
 [  2   0   0   3   1   0   0  12   7   1   0   0   2]
 [  0   2   0   0   3   3   1   8  95  10   5   1   3]
 [ 25   5   4   0   4   1   1   2   5 173  11  14  11]
 [  1   0   0   0   2   0   0   1   3   2  69   0   3]
 [  3   2   3   0   0   2   0   0   1   5   0  42   3]
 [  8   0   0   0   0   0   1   4   2  10   2   0  52]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.635

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.68      0.68       714
       False       0.58      0.58      0.58       553

    accuracy                           0.64      1267
   macro avg       0.63      0.63      0.63      1267
weighted avg       0.64      0.64      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[483 231]
 [231 322]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 279 acc=0.638
jobs_labor             n= 107 acc=0.626
business_finance       n=  23 acc=0.652
cost_of_living_housing n=  44 acc=0.636
healthcare_policy      n= 114 acc=0.649
public_health_crises   n=  14 acc=0.857
substances_gambling    n=  13 acc=0.538
family_demographics    n=  28 acc=0.536
law_crime_rights       n= 131 acc=0.733
institutions_elections n= 256 acc=0.559
foreign_affairs_security n=  81 acc=0.667
environment_energy_infra n=  61 acc=0.590
media_meta             n=  79 acc=0.722

====================================================================================================
Llama_test_predictions_with_experts_5.csv   |   model=llama   |   k=5
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    699
governance_law          330
foreign_security        106
society_culture          64
environment_science      54
misc                     14
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.766
Confusion matrix (rows=true, cols=pred):
[[547   3  48   5  11   2]
 [ 16  91  11   2   2   0]
 [ 95   8 251   9  13   2]
 [ 13   0   5  36   2   1]
 [ 12   4   9   0  36   0]
 [ 16   0   6   2   0   9]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.543

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.73      0.30      0.43       714
       False       0.49      0.86      0.62       553

    accuracy                           0.54      1267
   macro avg       0.61      0.58      0.52      1267
weighted avg       0.62      0.54      0.51      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[215 499]
 [ 80 473]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 616 acc=0.503
foreign_security       n= 122 acc=0.680
governance_law         n= 378 acc=0.534
environment_science    n=  57 acc=0.614
society_culture        n=  61 acc=0.607
misc                   n=  33 acc=0.636

====================================================================================================
Llama_test_predictions_with_experts_8.csv   |   model=llama   |   k=8
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
economy                506
politics_government    201
health_social          162
law_rights             139
foreign_security       114
society_culture         65
environment_energy      57
misc                    23
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.740
Confusion matrix (rows=true, cols=pred):
[[393  28   2   7  29   3   8   3]
 [ 15 108   3  13   1   0   3   0]
 [  8   3  95   9   2   2   2   1]
 [  7  13   5 106  11   1   2   0]
 [ 55   4   6   3 143  10   8   4]
 [  8   0   1   0   5  39   1   2]
 [  7   3   2   1   6   0  41   1]
 [ 13   3   0   0   4   2   0  12]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.632

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.67      0.69      0.68       714
       False       0.58      0.56      0.57       553

    accuracy                           0.63      1267
   macro avg       0.63      0.62      0.62      1267
weighted avg       0.63      0.63      0.63      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[492 222]
 [244 309]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 473 acc=0.653
health_social          n= 143 acc=0.650
foreign_security       n= 122 acc=0.672
law_rights             n= 145 acc=0.614
politics_government    n= 233 acc=0.635
environment_energy     n=  56 acc=0.607
society_culture        n=  61 acc=0.443
misc                   n=  34 acc=0.559

====================================================================================================
deepseek_test_predictions_with_experts_12.csv   |   model=deepseek   |   k=12
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  352
institutions_elections      242
law_crime_rights            145
healthcare_policy           136
foreign_affairs_security     85
media_meta                   80
jobs_labor                   72
environment_energy_infra     71
family_demographics          29
substances_gambling          18
cost_of_living_housing       18
business_finance             13
public_health_crises          6
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.680
Confusion matrix (rows=true, cols=pred):
[[228  16   2   3   7   0   1   2   1   9   1   5   4]
 [ 33  37   0   1   5   1   1   1   3  20   0   2   3]
 [  9   2   4   0   3   0   1   0   1   2   0   1   0]
 [ 14   1   1  10   8   0   0   4   0   4   0   2   0]
 [  3   0   1   0 101   0   2   1   3   1   1   0   1]
 [  0   1   0   0   0   3   1   0   6   0   1   2   0]
 [  0   0   0   0   2   0   9   0   1   0   0   0   1]
 [  1   0   0   3   1   0   0  11   8   1   0   0   3]
 [  1   2   0   0   3   2   2   3 103   7   4   2   2]
 [ 22   8   2   0   3   0   0   3   7 176  10  13  12]
 [  4   0   0   0   0   0   0   1   5   3  65   0   3]
 [  4   3   3   0   1   0   0   1   0   4   0  42   3]
 [ 10   1   0   0   0   0   1   2   4   9   3   1  48]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.609

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.92      0.73       714
       False       0.67      0.21      0.32       553

    accuracy                           0.61      1267
   macro avg       0.64      0.56      0.52      1267
weighted avg       0.63      0.61      0.55      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[658  56]
 [439 114]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 279 acc=0.602
jobs_labor             n= 107 acc=0.542
business_finance       n=  23 acc=0.565
cost_of_living_housing n=  44 acc=0.568
healthcare_policy      n= 114 acc=0.675
public_health_crises   n=  14 acc=0.714
substances_gambling    n=  13 acc=0.769
family_demographics    n=  28 acc=0.714
law_crime_rights       n= 131 acc=0.672
institutions_elections n= 256 acc=0.586
foreign_affairs_security n=  81 acc=0.642
environment_energy_infra n=  61 acc=0.508
media_meta             n=  79 acc=0.557

====================================================================================================
deepseek_test_predictions_with_experts_5.csv   |   model=deepseek   |   k=5
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    640
governance_law          394
foreign_security        117
environment_science      58
society_culture          49
misc                      9
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.788
Confusion matrix (rows=true, cols=pred):
[[538   2  63   7   6   0]
 [  8  99  12   0   3   0]
 [ 54  11 290   9  10   4]
 [  8   1   7  39   2   0]
 [  9   4  18   1  28   1]
 [ 23   0   4   2   0   4]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.661

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.65      0.87      0.74       714
       False       0.70      0.40      0.50       553

    accuracy                           0.66      1267
   macro avg       0.67      0.63      0.62      1267
weighted avg       0.67      0.66      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[618  96]
 [334 219]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 616 acc=0.680
foreign_security       n= 122 acc=0.590
governance_law         n= 378 acc=0.653
environment_science    n=  57 acc=0.579
society_culture        n=  61 acc=0.689
misc                   n=  33 acc=0.727

====================================================================================================
deepseek_test_predictions_with_experts_8.csv   |   model=deepseek   |   k=8
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
economy                482
politics_government    225
health_social          163
law_rights             146
foreign_security       120
society_culture         59
environment_energy      53
misc                    19
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.744
Confusion matrix (rows=true, cols=pred):
[[388  27   1   9  30   6   8   4]
 [  8 118   3  10   2   0   2   0]
 [  6   3  94  10   5   0   4   0]
 [  2   9  10 107  14   0   3   0]
 [ 43   3   8   6 155  10   7   1]
 [ 11   0   1   0   4  36   1   3]
 [  9   1   2   4  11   0  34   0]
 [ 15   2   1   0   4   1   0  11]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.610

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.95      0.73       714
       False       0.73      0.17      0.28       553

    accuracy                           0.61      1267
   macro avg       0.66      0.56      0.51      1267
weighted avg       0.65      0.61      0.53      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[678  36]
 [458  95]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 473 acc=0.634
health_social          n= 143 acc=0.629
foreign_security       n= 122 acc=0.590
law_rights             n= 145 acc=0.538
politics_government    n= 233 acc=0.605
environment_energy     n=  56 acc=0.554
society_culture        n=  61 acc=0.607
misc                   n=  34 acc=0.706

====================================================================================================
gemma_test_predictions_with_experts_12.csv   |   model=gemma   |   k=12
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  274
institutions_elections      200
law_crime_rights            144
healthcare_policy           123
jobs_labor                  116
media_meta                  104
foreign_affairs_security     84
environment_energy_infra     73
cost_of_living_housing       48
family_demographics          40
business_finance             34
public_health_crises         17
substances_gambling          10
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.642
Confusion matrix (rows=true, cols=pred):
[[194  36   5   5   8   0   1   4   2   7   1   9   7]
 [ 14  54   3   4   2   1   1   1   4  15   0   2   6]
 [  5   2   7   1   2   0   1   1   1   2   0   1   0]
 [  8   0   1  22   5   0   0   4   0   3   0   1   0]
 [  4   2   3   0  96   1   2   2   2   0   1   0   1]
 [  0   0   0   0   1   3   0   1   6   0   1   2   0]
 [  1   0   0   1   3   0   5   0   2   0   0   0   1]
 [  0   0   0   4   1   1   0  12   6   1   0   0   3]
 [  1   2   1   0   1   6   0   8  99   5   5   1   2]
 [ 14  17  11   4   2   2   0   2  12 146  13  10  23]
 [  3   0   0   0   1   0   0   2   4   3  60   2   6]
 [  5   1   3   1   0   2   0   0   0   5   0  41   3]
 [  6   0   0   3   0   0   0   2   3   9   3   2  51]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.593

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.62      0.72      0.67       714
       False       0.54      0.42      0.48       553

    accuracy                           0.59      1267
   macro avg       0.58      0.57      0.57      1267
weighted avg       0.59      0.59      0.58      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[516 198]
 [318 235]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 279 acc=0.602
jobs_labor             n= 107 acc=0.551
business_finance       n=  23 acc=0.435
cost_of_living_housing n=  44 acc=0.682
healthcare_policy      n= 114 acc=0.614
public_health_crises   n=  14 acc=0.643
substances_gambling    n=  13 acc=0.538
family_demographics    n=  28 acc=0.536
law_crime_rights       n= 131 acc=0.595
institutions_elections n= 256 acc=0.625
foreign_affairs_security n=  81 acc=0.593
environment_energy_infra n=  61 acc=0.557
media_meta             n=  79 acc=0.506

====================================================================================================
gemma_test_predictions_with_experts_5.csv   |   model=gemma   |   k=5
====================================================================================================
Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    594
governance_law          376
foreign_security        119
society_culture          83
environment_science      83
misc                     12
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.769
Confusion matrix (rows=true, cols=pred):
[[518   3  66  12  16   1]
 [  8  94  13   5   2   0]
 [ 42  15 275  18  25   3]
 [  6   1   5  42   2   1]
 [  6   5   9   3  38   0]
 [ 14   1   8   3   0   7]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.489

Classification report (True/False):
              precision    recall  f1-score   support


,file,model,k,mode,n_eval,accuracy,precision_true,recall_true,f1_true,confusion_matrix,domain_acc,n_domain_eval,domain_confusion_matrix
4,deepseek_test_predictions_with_experts_5.csv,deepseek,5,deepseek_k5,1267,0.660616,0.649160,0.865546,0.741897,[[618 96]\n [334 219]],0.787687,1267,[[538 2 63 7 6 0]\n [ 8 99 12 0 ...
5,deepseek_test_predictions_with_experts_8.csv,deepseek,8,deepseek_k8,1267,0.610103,0.596831,0.949580,0.732973,[[678 36]\n [458 95]],0.744278,1267,[[388 27 1 9 30 6 8 4]\n [ 8 118 ...
3,deepseek_test_predictions_with_experts_12.csv,deepseek,12,deepseek_k12,1267,0.609313,0.599818,0.921569,0.726670,[[658 56]\n [439 114]],0.680488,1230,[[228 16 2 3 7 0 1 2 1 9 1 ...
7,gemma_test_predictions_with_experts_5.csv,gemma,5,gemma_k5,1267,0.488556,0.585052,0.317927,0.411978,[[227 487]\n [161 392]],0.768745,1267,[[518 3 66 12 16 1]\n [ 8 94 13 5 ...
8,gemma_test_predictions_with_experts_8.csv,gemma,8,gemma_k8,1267,0.576953,0.610422,0.689076,0.647368,[[492 222]\n [314 239]],0.719811,1267,[[388 31 2 13 17 13 8 1]\n [ 8 115 ...
6,gemma_test_predictions_with_experts_12.csv,gemma,12,gemma_k12,1267,0.592739,0.618705,0.722689,0.666667,[[516 198]\n [318 235]],0.642276,1230,[[194 36 5 5 8 0 1 4 2 7 1 ...
1,Llama_test_predictions_with_experts_5.csv,llama,5,llama_k5,1267,0.543015,0.728814,0.301120,0.426165,[[215 499]\n [ 80 473]],0.765588,1267,[[547 3 48 5 11 2]\n [ 16 91 11 2 ...
2,Llama_test_predictions_with_experts_8.csv,llama,8,llama_k8,1267,0.632202,0.668478,0.689076,0.678621,[[492 222]\n [244 309]],0.739542,1267,[[393 28 2 7 29 3 8 3]\n [ 15 108 ...
0,Llama_test_predictions_with_experts_12.csv,llama,12,llama_k12,1267,0.635359,0.676471,0.676471,0.676471,[[483 231]\n [231 322]],0.688618,1230,[[232 14 0 4 8 0 1 2 0 10 1 ...

# Domainrouting + Checkability

### 5 Superlabels

In [4]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_5Classes",
    expert_root="adapters/Llama_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/Llama_test_predictions_with_experts_5_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🔎 Checkability:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🔎 Checkability: 100%|██████████| 1267/1267 [07:40<00:00,  2.75it/s]

Checkability categories:
checkability_category
fact_checkable              1100
opinion_or_ambiguous         122
non_claim                     42
sensitive_selfharm             2
needs_additional_context       1
Name: count, dtype: int64

✅ fact_checkable: 1100 | excluded: 167

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1100/1100 [09:23<00:00,  1.95it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    614
governance_law          292
foreign_security         88
society_culture          53
environment_science      42
misc                     11
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: socioeconomic_policy:   2%|▏         | 10/614 [04:22<4:35:04, 27.33s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 Expert: socioeconomic_policy: 100%|██████████| 614/614 [4:16:35<00:00, 25.07s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 88/88 [13:45<00:00,  9.39s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: governance_law: 100%|██████████| 292/292 [1:44:47<00:00, 21.53s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_science: 100%|██████████| 42/42 [07:53<00:00, 11.29s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 53/53 [10:26<00:00, 11.82s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 11/11 [01:43<00:00,  9.37s/it]

Sample rows with predictions (evaluated subset):
                                           statement          super_domain  \
0  Building a wall on the U.S . Mexico border wil...        governance_law
1  Wisconsin is on pace to double the number of l...  socioeconomic_policy
3  Suzanne Bonamici supports a plan that will cut...  socioeconomic_policy
4  When asked by a reporter whether hes at the ce...        governance_law
5  Over the past five years the federal governmen...  socioeconomic_policy

            domain_pred  label verdict_pred checkability_category
0  socioeconomic_policy   True        False        fact_checkable
1  socioeconomic_policy  False        False        fact_checkable
3  socioeconomic_policy   True        False        fact_checkable
4        governance_law  False         True        fact_checkable
5  socioeconomic_policy   True        False        fact_checkable

🌍 Domain routing accuracy: 0.770
Confusion matrix (rows=true, cols=pred):
[[487   3  45   4   9   2]
 [  9  74  10   2   2   0]
 [ 82   8 221   6  10   2]
 [  9   0   4  28   1   1]
 [ 12   3   9   0  31   0]
 [ 15   0   3   2   0   6]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.543

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.75      0.33      0.46       648
       False       0.47      0.84      0.60       452

    accuracy                           0.54      1100
   macro avg       0.61      0.59      0.53      1100
weighted avg       0.64      0.54      0.52      1100

Confusion matrix [rows=true, cols=pred] (True, False):
[[216 432]
 [ 71 381]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 550 acc=0.502
foreign_security       n=  97 acc=0.722
governance_law         n= 329 acc=0.520
environment_science    n=  43 acc=0.651
society_culture        n=  55 acc=0.600
misc                   n=  26 acc=0.731

💾 Saved predictions to: Results/Llama_test_predictions_with_experts_5_checkability.csv

In [5]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_5Classes",
    expert_root="adapters/gemma_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/gemma_test_predictions_with_experts_5_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [33:17<00:00,  1.58s/it]

Checkability categories:
checkability_category
fact_checkable              535
needs_additional_context    383
opinion_or_ambiguous        279
non_claim                    68
sensitive_selfharm            2
Name: count, dtype: int64

✅ fact_checkable: 535 | excluded: 732

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 535/535 [02:01<00:00,  4.40it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    278
governance_law          151
society_culture          39
environment_science      36
foreign_security         26
misc                      5
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Expert: socioeconomic_policy: 100%|██████████| 278/278 [3:01:59<00:00, 39.28s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 26/26 [08:25<00:00, 19.44s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: governance_law: 100%|██████████| 151/151 [1:08:30<00:00, 27.22s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_science: 100%|██████████| 36/36 [14:59<00:00, 25.00s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 39/39 [14:34<00:00, 22.43s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 5/5 [01:37<00:00, 19.53s/it]

Sample rows with predictions (evaluated subset):
                                           statement          super_domain  \
1  Wisconsin is on pace to double the number of l...  socioeconomic_policy
4  When asked by a reporter whether hes at the ce...        governance_law
5  Over the past five years the federal governmen...  socioeconomic_policy
6  Says that Tennessee law requires that schools ...  socioeconomic_policy
9  We know that more than half of Hillary Clinton...      foreign_security

            domain_pred  label verdict_pred checkability_category
1  socioeconomic_policy  False        False        fact_checkable
4        governance_law  False         True        fact_checkable
5  socioeconomic_policy   True        False        fact_checkable
6  socioeconomic_policy   True        False        fact_checkable
9        governance_law  False         True        fact_checkable

🌍 Domain routing accuracy: 0.776
Confusion matrix (rows=true, cols=pred):
[[246   2  28   6   6   0]
 [  3  16   6   2   1   0]
 [ 21   4 108   6  10   2]
 [  1   1   1  21   1   0]
 [  2   2   4   0  21   0]
 [  5   1   4   1   0   3]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.434

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.66      0.31      0.42       357
       False       0.33      0.68      0.44       178

    accuracy                           0.43       535
   macro avg       0.50      0.50      0.43       535
weighted avg       0.55      0.43      0.43       535

Confusion matrix [rows=true, cols=pred] (True, False):
[[111 246]
 [ 57 121]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 288 acc=0.351
foreign_security       n=  28 acc=0.679
governance_law         n= 151 acc=0.477
environment_science    n=  25 acc=0.480
society_culture        n=  29 acc=0.690
misc                   n=  14 acc=0.571

💾 Saved predictions to: Results/gemma_test_predictions_with_experts_5_checkability.csv

In [11]:
from multiagent_pipeline_checkability_deepseek import run_full_pipeline

SUPER_LABELS_5 = [
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_5Classes",
    expert_root="adapters/deepseek_experts_5Classes",
    super_labels=SUPER_LABELS_5,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_5.csv",
    out_path="Results/deepseek_test_predictions_with_experts_5_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
socioeconomic_policy    616
governance_law          378
foreign_security        122
society_culture          61
environment_science      57
misc                     33
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [1:03:51<00:00,  3.02s/it]

Checkability categories:
checkability_category
fact_checkable          1263
opinion_or_ambiguous       2
non_claim                  2
Name: count, dtype: int64

✅ fact_checkable: 1263 | excluded: 4

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1263/1263 [09:33<00:00,  2.20it/s]

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    637
governance_law          394
foreign_security        117
environment_science      57
society_culture          49
misc                      9
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: socioeconomic_policy: 100%|██████████| 637/637 [1:13:40<00:00,  6.94s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 117/117 [13:45<00:00,  7.06s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: governance_law: 100%|██████████| 394/394 [44:25<00:00,  6.76s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_science: 100%|██████████| 57/57 [06:34<00:00,  6.93s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 49/49 [09:14<00:00, 11.32s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 9/9 [00:57<00:00,  6.38s/it]

Sample rows with predictions (evaluated subset):
                                           statement          super_domain  \
0  Building a wall on the U.S . Mexico border wil...        governance_law
1  Wisconsin is on pace to double the number of l...  socioeconomic_policy
2  Says John McCain has done nothing to help the ...  socioeconomic_policy
3  Suzanne Bonamici supports a plan that will cut...  socioeconomic_policy
4  When asked by a reporter whether hes at the ce...        governance_law

            domain_pred  label verdict_pred checkability_category
0        governance_law   True         True        fact_checkable
1  socioeconomic_policy  False         True        fact_checkable
2  socioeconomic_policy  False        False        fact_checkable
3  socioeconomic_policy   True        False        fact_checkable
4        governance_law  False        False        fact_checkable

🌍 Domain routing accuracy: 0.787
Confusion matrix (rows=true, cols=pred):
[[535   2  63   7   6   0]
 [  8  99  12   0   3   0]
 [ 54  11 290   9  10   4]
 [  8   1   7  38   2   0]
 [  9   4  18   1  28   1]
 [ 23   0   4   2   0   4]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.661

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.65      0.87      0.74       712
       False       0.70      0.40      0.50       551

    accuracy                           0.66      1263
   macro avg       0.67      0.63      0.62      1263
weighted avg       0.67      0.66      0.64      1263

Confusion matrix [rows=true, cols=pred] (True, False):
[[617  95]
 [333 218]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 613 acc=0.680
foreign_security       n= 122 acc=0.590
governance_law         n= 378 acc=0.653
environment_science    n=  56 acc=0.589
society_culture        n=  61 acc=0.689
misc                   n=  33 acc=0.727

💾 Saved predictions to: Results/deepseek_test_predictions_with_experts_5_checkability_regular.csv

### 8 Superlabels

In [1]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_8Classes",
    expert_root="adapters/Llama_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/Llama_test_predictions_with_experts_8_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🔎 Checkability:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🔎 Checkability: 100%|██████████| 1267/1267 [07:12<00:00,  2.93it/s]

Checkability categories:
checkability_category
fact_checkable              1100
opinion_or_ambiguous         122
non_claim                     42
sensitive_selfharm             2
needs_additional_context       1
Name: count, dtype: int64

✅ fact_checkable: 1100 | excluded: 167

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1100/1100 [08:39<00:00,  2.12it/s]

Predicted domain distribution (router):
domain_pred_router
economy                449
politics_government    180
health_social          143
law_rights             124
foreign_security        93
society_culture         52
environment_energy      44
misc                    15
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: economy:   2%|▏         | 10/449 [01:30<57:39,  7.88s/it] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 Expert: economy: 100%|██████████| 449/449 [1:37:42<00:00, 13.06s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: health_social: 100%|██████████| 143/143 [22:43<00:00,  9.53s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 93/93 [14:55<00:00,  9.63s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_rights: 100%|██████████| 124/124 [20:58<00:00, 10.15s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: politics_government: 100%|██████████| 180/180 [26:46<00:00,  8.93s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy: 100%|██████████| 44/44 [06:33<00:00,  8.95s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 52/52 [22:20<00:00, 25.78s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 15/15 [02:32<00:00, 10.18s/it]

Sample rows with predictions (evaluated subset):
                                           statement   super_domain  \
0  Building a wall on the U.S . Mexico border wil...     law_rights
1  Wisconsin is on pace to double the number of l...        economy
3  Suzanne Bonamici supports a plan that will cut...  health_social
4  When asked by a reporter whether hes at the ce...     law_rights
5  Over the past five years the federal governmen...        economy

     domain_pred  label verdict_pred checkability_category
0     law_rights   True         True        fact_checkable
1        economy  False         True        fact_checkable
3  health_social   True         True        fact_checkable
4        economy  False         True        fact_checkable
5        economy   True         True        fact_checkable

🌍 Domain routing accuracy: 0.744
Confusion matrix (rows=true, cols=pred):
[[350  24   2   6  29   2   4   2]
 [ 15  97   3  12   1   0   3   0]
 [  6   2  76   7   1   2   2   1]
 [  4  12   4  95   8   0   1   0]
 [ 48   4   6   3 127   9   6   2]
 [  6   0   1   0   5  29   0   1]
 [  7   3   1   1   6   0  36   1]
 [ 13   1   0   0   3   2   0   8]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.637

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.72      0.70       648
       False       0.56      0.52      0.54       452

    accuracy                           0.64      1100
   macro avg       0.62      0.62      0.62      1100
weighted avg       0.63      0.64      0.63      1100

Confusion matrix [rows=true, cols=pred] (True, False):
[[466 182]
 [217 235]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 419 acc=0.649
health_social          n= 131 acc=0.634
foreign_security       n=  97 acc=0.722
law_rights             n= 124 acc=0.621
politics_government    n= 205 acc=0.644
environment_energy     n=  42 acc=0.619
society_culture        n=  55 acc=0.436
misc                   n=  27 acc=0.630

💾 Saved predictions to: Results/Llama_test_predictions_with_experts_8_checkability.csv

In [2]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_8Classes",
    expert_root="adapters/gemma_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/gemma_test_predictions_with_experts_8_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [34:13<00:00,  1.62s/it]

Checkability categories:
checkability_category
fact_checkable              535
needs_additional_context    383
opinion_or_ambiguous        279
non_claim                    68
sensitive_selfharm            2
Name: count, dtype: int64

✅ fact_checkable: 535 | excluded: 732

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 535/535 [01:37<00:00,  5.47it/s]

Predicted domain distribution (router):
domain_pred_router
economy                236
health_social           77
law_rights              68
politics_government     57
society_culture         35
environment_energy      33
foreign_security        24
misc                     5
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 Expert: economy: 100%|██████████| 236/236 [1:41:17<00:00, 25.75s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: health_social: 100%|██████████| 77/77 [23:10<00:00, 18.05s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_security: 100%|██████████| 24/24 [09:04<00:00, 22.69s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_rights: 100%|██████████| 68/68 [19:52<00:00, 17.53s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: politics_government: 100%|██████████| 57/57 [20:28<00:00, 21.56s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy: 100%|██████████| 33/33 [09:14<00:00, 16.81s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: society_culture: 100%|██████████| 35/35 [19:07<00:00, 32.79s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: misc: 100%|██████████| 5/5 [02:41<00:00, 32.30s/it]

Sample rows with predictions (evaluated subset):
                                           statement      super_domain  \
1  Wisconsin is on pace to double the number of l...           economy
4  When asked by a reporter whether hes at the ce...        law_rights
5  Over the past five years the federal governmen...           economy
6  Says that Tennessee law requires that schools ...           economy
9  We know that more than half of Hillary Clinton...  foreign_security

        domain_pred  label verdict_pred checkability_category
1           economy  False        False        fact_checkable
4           economy  False        False        fact_checkable
5           economy   True         True        fact_checkable
6           economy   True         True        fact_checkable
9  foreign_security  False         True        fact_checkable

🌍 Domain routing accuracy: 0.738
Confusion matrix (rows=true, cols=pred):
[[188  11   2   9   7   4   2   1]
 [  4  53   0   5   0   0   2   0]
 [  0   2  19   4   1   1   1   0]
 [  3   4   1  45   2   0   1   0]
 [ 28   4   0   5  45   7   5   1]
 [  3   1   0   0   0  20   1   0]
 [  2   2   1   0   2   0  22   0]
 [  8   0   1   0   0   1   1   3]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.621

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.70      0.77      0.73       357
       False       0.41      0.33      0.36       178

    accuracy                           0.62       535
   macro avg       0.55      0.55      0.55       535
weighted avg       0.60      0.62      0.61       535

Confusion matrix [rows=true, cols=pred] (True, False):
[[274  83]
 [120  58]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 224 acc=0.589
health_social          n=  64 acc=0.672
foreign_security       n=  28 acc=0.750
law_rights             n=  56 acc=0.679
politics_government    n=  95 acc=0.589
environment_energy     n=  25 acc=0.600
society_culture        n=  29 acc=0.586
misc                   n=  14 acc=0.714

💾 Saved predictions to: Results/gemma_test_predictions_with_experts_8_checkability.csv

In [3]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_8Classes",
    expert_root="adapters/deepseek_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/deepseek_test_predictions_with_experts_8_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [1:06:28<00:00,  3.15s/it]

Checkability categories:
checkability_category
opinion_or_ambiguous    1267
Name: count, dtype: int64

✅ fact_checkable: 0 | excluded: 1267

RuntimeError: No fact_checkable samples found. Gate too strict or data issue.

In [2]:
evaluate_predictions("Results/deepseek_test_predictions_with_experts_8.csv")

==============================
✅ Verdict Evaluation (overall)
==============================
Samples: 1267
Verdict Accuracy: 0.610

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.95      0.73       714
       False       0.73      0.17      0.28       553

    accuracy                           0.61      1267
   macro avg       0.66      0.56      0.51      1267
weighted avg       0.65      0.61      0.53      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[678  36]
 [458  95]]

==================================
🌍 Domain Routing Evaluation
==================================
Routing samples: 1267
Domain-Routing Accuracy: 0.744
Domain-Routing Confusion Matrix (rows=true, cols=pred):
[[388  27   1   9  30   6   8   4]
 [  8 118   3  10   2   0   2   0]
 [  6   3  94  10   5   0   4   0]
 [  2   9  10 107  14   0   3   0]
 [ 43   3   8   6 155  10   7   1]
 [ 11   0   1   0   4  36   1   3]
 [  9   1   2   4  11   0  34   0]
 [ 15   2   1   0   4   1   0  11]]
Domain label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

=================================================
📊 Per-Domain Verdict Accuracy (by true super_domain)
=================================================
economy                n= 473 acc=0.634
health_social          n= 143 acc=0.629
foreign_security       n= 122 acc=0.590
law_rights             n= 145 acc=0.538
politics_government    n= 233 acc=0.605
environment_energy     n=  56 acc=0.554
society_culture        n=  61 acc=0.607
misc                   n=  34 acc=0.706

### 12 Superlabels

In [ ]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_12Classes",
    expert_root="adapters/Llama_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/Llama_test_predictions_with_experts_12_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [10]:
from multiagent_pipeline_checkability import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]

df_pred = run_full_pipeline(
    base_model_id="google/gemma-7b-it",
    router_lora_dir="adapters/gemma-liar-statement-domain-lora_12Classes",
    expert_root="adapters/gemma_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/gemma_test_predictions_with_experts_12_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [33:31<00:00,  1.59s/it]

Checkability categories:
checkability_category
fact_checkable              535
needs_additional_context    383
opinion_or_ambiguous        279
non_claim                    68
sensitive_selfharm            2
Name: count, dtype: int64

✅ fact_checkable: 535 | excluded: 732

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 535/535 [02:22<00:00,  3.76it/s]

Predicted domain distribution (router):
domain_pred_router
macro_econ                  130
institutions_elections       78
jobs_labor                   58
healthcare_policy            58
law_crime_rights             56
media_meta                   39
environment_energy_infra     30
cost_of_living_housing       26
family_demographics          19
foreign_affairs_security     16
business_finance             15
substances_gambling           5
public_health_crises          5
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: macro_econ: 100%|██████████| 130/130 [51:08<00:00, 23.60s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: jobs_labor: 100%|██████████| 58/58 [25:03<00:00, 25.92s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: business_finance: 100%|██████████| 15/15 [05:07<00:00, 20.49s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: cost_of_living_housing: 100%|██████████| 26/26 [09:03<00:00, 20.89s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: healthcare_policy: 100%|██████████| 58/58 [16:02<00:00, 16.59s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: public_health_crises: 100%|██████████| 5/5 [01:25<00:00, 17.03s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: substances_gambling: 100%|██████████| 5/5 [01:25<00:00, 17.05s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: family_demographics: 100%|██████████| 19/19 [07:31<00:00, 23.79s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: law_crime_rights: 100%|██████████| 56/56 [21:52<00:00, 23.43s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: institutions_elections: 100%|██████████| 78/78 [26:53<00:00, 20.69s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: foreign_affairs_security: 100%|██████████| 16/16 [04:17<00:00, 16.08s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: environment_energy_infra: 100%|██████████| 30/30 [10:57<00:00, 21.92s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: media_meta: 100%|██████████| 39/39 [23:43<00:00, 36.50s/it]

Sample rows with predictions (evaluated subset):
                                           statement  \
1  Wisconsin is on pace to double the number of l...
4  When asked by a reporter whether hes at the ce...
5  Over the past five years the federal governmen...
6  Says that Tennessee law requires that schools ...
9  We know that more than half of Hillary Clinton...

               super_domain             domain_pred  label verdict_pred  \
1                jobs_labor              jobs_labor  False        False
4    institutions_elections  institutions_elections  False         True
5    cost_of_living_housing  cost_of_living_housing   True         True
6                macro_econ              macro_econ   True         True
9  foreign_affairs_security  institutions_elections  False         True

  checkability_category
1        fact_checkable
4        fact_checkable
5        fact_checkable
6        fact_checkable
9        fact_checkable

🌍 Domain routing accuracy: 0.630
Confusion matrix (rows=true, cols=pred):
[[91 20  1  3  3  0  1  3  0  5  1  2  2]
 [11 26  2  1  1  0  1  0  3  5  0  0  2]
 [ 0  0  3  1  1  0  0  0  1  1  0  1  0]
 [ 3  0  1 11  2  0  0  2  0  1  0  0  0]
 [ 4  1  1  0 45  0  2  1  1  0  0  0  0]
 [ 0  0  0  0  0  1  0  1  2  0  0  2  0]
 [ 1  0  0  1  2  0  1  0  1  0  0  0  0]
 [ 0  0  0  3  1  1  0  4  3  0  0  0  2]
 [ 1  0  1  0  0  2  0  3 40  4  0  0  1]
 [ 6  9  4  2  2  0  0  1  5 53  1  5  8]
 [ 0  0  0  0  1  0  0  1  0  1 13  1  1]
 [ 1  1  2  1  0  1  0  0  0  2  0 18  1]
 [ 3  0  0  2  0  0  0  2  0  5  1  0 22]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.632

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.70      0.78      0.74       357
       False       0.43      0.34      0.38       178

    accuracy                           0.63       535
   macro avg       0.57      0.56      0.56       535
weighted avg       0.61      0.63      0.62       535

Confusion matrix [rows=true, cols=pred] (True, False):
[[277  80]
 [117  61]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 132 acc=0.598
jobs_labor             n=  52 acc=0.538
business_finance       n=   8 acc=0.500
cost_of_living_housing n=  20 acc=0.650
healthcare_policy      n=  55 acc=0.709
public_health_crises   n=   6 acc=0.667
substances_gambling    n=   6 acc=0.667
family_demographics    n=  14 acc=0.786
law_crime_rights       n=  52 acc=0.635
institutions_elections n=  96 acc=0.646
foreign_affairs_security n=  18 acc=0.778
environment_energy_infra n=  27 acc=0.704
media_meta             n=  35 acc=0.543

💾 Saved predictions to: Results/gemma_test_predictions_with_experts_12_checkability.csv

In [ ]:
from multiagent_pipeline_checkability_deepseek import run_full_pipeline

SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]

df_pred = run_full_pipeline(
    base_model_id="deepseek-ai/deepseek-llm-7b-base",
    router_lora_dir="adapters/deepseek-liar-statement-domain-lora_12Classes",
    expert_root="adapters/deepseek_experts_12Classes",
    super_labels=SUPER_LABELS_12,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_12.csv",
    out_path="Results/deepseek_test_predictions_with_experts_12_checkability.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    use_checkability_gate=True,
)

Test set size: 1267
True domain distribution:
super_domain
macro_econ                  279
institutions_elections      256
law_crime_rights            131
healthcare_policy           114
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     61
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

=== Phase 0: Checkability Gate ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🔎 Checkability: 100%|██████████| 1267/1267 [1:03:42<00:00,  3.02s/it]

Checkability categories:
checkability_category
fact_checkable          1263
opinion_or_ambiguous       2
non_claim                  2
Name: count, dtype: int64

✅ fact_checkable: 1263 | excluded: 4

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1263/1263 [09:43<00:00,  2.16it/s]

Predicted domain distribution (router):
domain_pred_router
macro_econ                  351
institutions_elections      242
law_crime_rights            145
healthcare_policy           134
foreign_affairs_security     85
media_meta                   80
jobs_labor                   72
environment_energy_infra     70
family_demographics          29
substances_gambling          18
cost_of_living_housing       18
business_finance             13
public_health_crises          6
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: macro_econ:   4%|▎         | 13/351 [01:29<37:58,  6.74s/it]

## Conclusion

In [1]:
from evaluate_domainrouter_checkability import evaluate_all_verbose

SUPER_LABELS_5 = [        
        "socioeconomic_policy",
        "foreign_security",
        "governance_law",
        "environment_science",
        "society_culture",
        "misc",
        ]
SUPER_LABELS_8 = [        
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
        ]
SUPER_LABELS_12 = [
        "macro_econ",
        "jobs_labor",
        "business_finance",
        "cost_of_living_housing",
        "healthcare_policy",
        "public_health_crises",
        "substances_gambling",
        "family_demographics",
        "law_crime_rights",
        "institutions_elections",
        "foreign_affairs_security",
        "environment_energy_infra",
        "media_meta",
    ]

summary = evaluate_all_verbose(
    folder="Results",
    pattern="*test_predictions_with_experts*_checkability.csv",
    super_labels_by_k={5: SUPER_LABELS_5, 8: SUPER_LABELS_8, 12: SUPER_LABELS_12},
)
summary

====================================================================================================
Llama_test_predictions_with_experts_12_checkability.csv   |   model=llama   |   k=12
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1100
Test set size: 1100
True domain distribution:
super_domain
macro_econ                  247
institutions_elections      225
law_crime_rights            112
healthcare_policy           103
jobs_labor                   96
media_meta                   68
foreign_affairs_security     62
environment_energy_infra     46
cost_of_living_housing       40
misc                         31
family_demographics          26
business_finance             20
public_health_crises         12
substances_gambling          12
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  311
institutions_elections      222
healthcare_policy           118
law_crime_rights            111
foreign_affairs_security     71
media_meta                   67
jobs_labor                   62
environment_energy_infra     52
family_demographics          28
cost_of_living_housing       21
substances_gambling          15
public_health_crises         11
business_finance             11
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.684
Confusion matrix (rows=true, cols=pred):
[[204  14   0   4   7   0   1   2   0   9   1   3   2]
 [ 27  37   1   0   4   2   1   0   1  22   0   0   1]
 [  8   0   4   0   1   0   1   0   1   5   0   0   0]
 [ 12   1   1  13   5   0   0   2   0   3   0   2   1]
 [  2   2   0   0  90   0   2   0   3   1   1   1   1]
 [  0   0   0   0   0   4   1   0   4   1   1   1   0]
 [  0   0   0   0   3   0   6   0   2   0   0   0   1]
 [  2   0   0   3   1   0   0  10   7   1   0   0   2]
 [  0   2   0   0   3   3   1   6  83   6   5   1   2]
 [ 22   4   3   0   3   0   1   2   4 154  10  12  10]
 [  1   0   0   0   1   0   0   1   2   2  52   0   3]
 [  2   2   2   0   0   2   0   0   1   5   0  31   1]
 [  8   0   0   0   0   0   1   4   2   9   1   0  43]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.634

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.71      0.69       648
       False       0.56      0.53      0.54       452

    accuracy                           0.63      1100
   macro avg       0.62      0.62      0.62      1100
weighted avg       0.63      0.63      0.63      1100

Confusion matrix [rows=true, cols=pred] (True, False):
[[457 191]
 [212 240]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 247 acc=0.644
jobs_labor             n=  96 acc=0.635
business_finance       n=  20 acc=0.600
cost_of_living_housing n=  40 acc=0.650
healthcare_policy      n= 103 acc=0.631
public_health_crises   n=  12 acc=0.833
substances_gambling    n=  12 acc=0.583
family_demographics    n=  26 acc=0.500
law_crime_rights       n= 112 acc=0.714
institutions_elections n= 225 acc=0.542
foreign_affairs_security n=  62 acc=0.726
environment_energy_infra n=  46 acc=0.587
media_meta             n=  68 acc=0.735

====================================================================================================
Llama_test_predictions_with_experts_5_checkability.csv   |   model=llama   |   k=5
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1100
Test set size: 1100
True domain distribution:
super_domain
socioeconomic_policy    550
governance_law          329
foreign_security         97
society_culture          55
environment_science      43
misc                     26
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    614
governance_law          292
foreign_security         88
society_culture          53
environment_science      42
misc                     11
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.770
Confusion matrix (rows=true, cols=pred):
[[487   3  45   4   9   2]
 [  9  74  10   2   2   0]
 [ 82   8 221   6  10   2]
 [  9   0   4  28   1   1]
 [ 12   3   9   0  31   0]
 [ 15   0   3   2   0   6]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.543

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.75      0.33      0.46       648
       False       0.47      0.84      0.60       452

    accuracy                           0.54      1100
   macro avg       0.61      0.59      0.53      1100
weighted avg       0.64      0.54      0.52      1100

Confusion matrix [rows=true, cols=pred] (True, False):
[[216 432]
 [ 71 381]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 550 acc=0.502
foreign_security       n=  97 acc=0.722
governance_law         n= 329 acc=0.520
environment_science    n=  43 acc=0.651
society_culture        n=  55 acc=0.600
misc                   n=  26 acc=0.731

====================================================================================================
Llama_test_predictions_with_experts_8_checkability.csv   |   model=llama   |   k=8
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1100
Test set size: 1100
True domain distribution:
super_domain
economy                419
politics_government    205
health_social          131
law_rights             124
foreign_security        97
society_culture         55
environment_energy      42
misc                    27
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
economy                449
politics_government    180
health_social          143
law_rights             124
foreign_security        93
society_culture         52
environment_energy      44
misc                    15
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.744
Confusion matrix (rows=true, cols=pred):
[[350  24   2   6  29   2   4   2]
 [ 15  97   3  12   1   0   3   0]
 [  6   2  76   7   1   2   2   1]
 [  4  12   4  95   8   0   1   0]
 [ 48   4   6   3 127   9   6   2]
 [  6   0   1   0   5  29   0   1]
 [  7   3   1   1   6   0  36   1]
 [ 13   1   0   0   3   2   0   8]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.637

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.72      0.70       648
       False       0.56      0.52      0.54       452

    accuracy                           0.64      1100
   macro avg       0.62      0.62      0.62      1100
weighted avg       0.63      0.64      0.63      1100

Confusion matrix [rows=true, cols=pred] (True, False):
[[466 182]
 [217 235]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 419 acc=0.649
health_social          n= 131 acc=0.634
foreign_security       n=  97 acc=0.722
law_rights             n= 124 acc=0.621
politics_government    n= 205 acc=0.644
environment_energy     n=  42 acc=0.619
society_culture        n=  55 acc=0.436
misc                   n=  27 acc=0.630

====================================================================================================
deepseek_test_predictions_with_experts_12_checkability.csv   |   model=deepseek   |   k=12
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1263
Test set size: 1263
True domain distribution:
super_domain
macro_econ                  278
institutions_elections      256
law_crime_rights            131
healthcare_policy           112
jobs_labor                  107
foreign_affairs_security     81
media_meta                   79
environment_energy_infra     60
cost_of_living_housing       44
misc                         37
family_demographics          28
business_finance             23
public_health_crises         14
substances_gambling          13
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  351
institutions_elections      242
law_crime_rights            145
healthcare_policy           134
foreign_affairs_security     85
media_meta                   80
jobs_labor                   72
environment_energy_infra     70
family_demographics          29
substances_gambling          18
cost_of_living_housing       18
business_finance             13
public_health_crises          6
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.679
Confusion matrix (rows=true, cols=pred):
[[227  16   2   3   7   0   1   2   1   9   1   5   4]
 [ 33  37   0   1   5   1   1   1   3  20   0   2   3]
 [  9   2   4   0   3   0   1   0   1   2   0   1   0]
 [ 14   1   1  10   8   0   0   4   0   4   0   2   0]
 [  3   0   1   0  99   0   2   1   3   1   1   0   1]
 [  0   1   0   0   0   3   1   0   6   0   1   2   0]
 [  0   0   0   0   2   0   9   0   1   0   0   0   1]
 [  1   0   0   3   1   0   0  11   8   1   0   0   3]
 [  1   2   0   0   3   2   2   3 103   7   4   2   2]
 [ 22   8   2   0   3   0   0   3   7 176  10  13  12]
 [  4   0   0   0   0   0   0   1   5   3  65   0   3]
 [  4   3   3   0   1   0   0   1   0   4   0  41   3]
 [ 10   1   0   0   0   0   1   2   4   9   3   1  48]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.609

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.92      0.73       712
       False       0.67      0.21      0.31       551

    accuracy                           0.61      1263
   macro avg       0.63      0.56      0.52      1263
weighted avg       0.63      0.61      0.55      1263

Confusion matrix [rows=true, cols=pred] (True, False):
[[656  56]
 [438 113]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 278 acc=0.601
jobs_labor             n= 107 acc=0.542
business_finance       n=  23 acc=0.565
cost_of_living_housing n=  44 acc=0.568
healthcare_policy      n= 112 acc=0.670
public_health_crises   n=  14 acc=0.714
substances_gambling    n=  13 acc=0.769
family_demographics    n=  28 acc=0.714
law_crime_rights       n= 131 acc=0.672
institutions_elections n= 256 acc=0.586
foreign_affairs_security n=  81 acc=0.642
environment_energy_infra n=  60 acc=0.517
media_meta             n=  79 acc=0.557

====================================================================================================
deepseek_test_predictions_with_experts_5_checkability.csv   |   model=deepseek   |   k=5
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1263
Test set size: 1263
True domain distribution:
super_domain
socioeconomic_policy    613
governance_law          378
foreign_security        122
society_culture          61
environment_science      56
misc                     33
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    637
governance_law          394
foreign_security        117
environment_science      57
society_culture          49
misc                      9
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.787
Confusion matrix (rows=true, cols=pred):
[[535   2  63   7   6   0]
 [  8  99  12   0   3   0]
 [ 54  11 290   9  10   4]
 [  8   1   7  38   2   0]
 [  9   4  18   1  28   1]
 [ 23   0   4   2   0   4]]
Label order: ['socioeconomic_policy', 'foreign_security', 'governance_law', 'environment_science', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.661

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.65      0.87      0.74       712
       False       0.70      0.40      0.50       551

    accuracy                           0.66      1263
   macro avg       0.67      0.63      0.62      1263
weighted avg       0.67      0.66      0.64      1263

Confusion matrix [rows=true, cols=pred] (True, False):
[[617  95]
 [333 218]]

===== Per-domain verdict accuracy (by true domain) =====
socioeconomic_policy   n= 613 acc=0.680
foreign_security       n= 122 acc=0.590
governance_law         n= 378 acc=0.653
environment_science    n=  56 acc=0.589
society_culture        n=  61 acc=0.689
misc                   n=  33 acc=0.727

====================================================================================================
deepseek_test_predictions_with_experts_8_checkability.csv   |   model=deepseek   |   k=8
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 1263
Test set size: 1263
True domain distribution:
super_domain
economy                472
politics_government    233
law_rights             145
health_social          141
foreign_security       122
society_culture         61
environment_energy      55
misc                    34
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
economy                481
politics_government    225
health_social          161
law_rights             146
foreign_security       120
society_culture         59
environment_energy      52
misc                    19
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.743
Confusion matrix (rows=true, cols=pred):
[[387  27   1   9  30   6   8   4]
 [  8 116   3  10   2   0   2   0]
 [  6   3  94  10   5   0   4   0]
 [  2   9  10 107  14   0   3   0]
 [ 43   3   8   6 155  10   7   1]
 [ 11   0   1   0   4  35   1   3]
 [  9   1   2   4  11   0  34   0]
 [ 15   2   1   0   4   1   0  11]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.610

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.60      0.95      0.73       712
       False       0.72      0.17      0.28       551

    accuracy                           0.61      1263
   macro avg       0.66      0.56      0.50      1263
weighted avg       0.65      0.61      0.53      1263

Confusion matrix [rows=true, cols=pred] (True, False):
[[676  36]
 [457  94]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 472 acc=0.633
health_social          n= 141 acc=0.624
foreign_security       n= 122 acc=0.590
law_rights             n= 145 acc=0.538
politics_government    n= 233 acc=0.605
environment_energy     n=  55 acc=0.564
society_culture        n=  61 acc=0.607
misc                   n=  34 acc=0.706

====================================================================================================
gemma_test_predictions_with_experts_12_checkability.csv   |   model=gemma   |   k=12
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 535
Test set size: 535
True domain distribution:
super_domain
macro_econ                  132
institutions_elections       96
healthcare_policy            55
jobs_labor                   52
law_crime_rights             52
media_meta                   35
environment_energy_infra     27
cost_of_living_housing       20
foreign_affairs_security     18
family_demographics          14
misc                         14
business_finance              8
public_health_crises          6
substances_gambling           6
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
macro_econ                  130
institutions_elections       78
jobs_labor                   58
healthcare_policy            58
law_crime_rights             56
media_meta                   39
environment_energy_infra     30
cost_of_living_housing       26
family_demographics          19
foreign_affairs_security     16
business_finance             15
substances_gambling           5
public_health_crises          5
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.630
Confusion matrix (rows=true, cols=pred):
[[91 20  1  3  3  0  1  3  0  5  1  2  2]
 [11 26  2  1  1  0  1  0  3  5  0  0  2]
 [ 0  0  3  1  1  0  0  0  1  1  0  1  0]
 [ 3  0  1 11  2  0  0  2  0  1  0  0  0]
 [ 4  1  1  0 45  0  2  1  1  0  0  0  0]
 [ 0  0  0  0  0  1  0  1  2  0  0  2  0]
 [ 1  0  0  1  2  0  1  0  1  0  0  0  0]
 [ 0  0  0  3  1  1  0  4  3  0  0  0  2]
 [ 1  0  1  0  0  2  0  3 40  4  0  0  1]
 [ 6  9  4  2  2  0  0  1  5 53  1  5  8]
 [ 0  0  0  0  1  0  0  1  0  1 13  1  1]
 [ 1  1  2  1  0  1  0  0  0  2  0 18  1]
 [ 3  0  0  2  0  0  0  2  0  5  1  0 22]]
Label order: ['macro_econ', 'jobs_labor', 'business_finance', 'cost_of_living_housing', 'healthcare_policy', 'public_health_crises', 'substances_gambling', 'family_demographics', 'law_crime_rights', 'institutions_elections', 'foreign_affairs_security', 'environment_energy_infra', 'media_meta']

✅ Verdict accuracy (overall): 0.632

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.70      0.78      0.74       357
       False       0.43      0.34      0.38       178

    accuracy                           0.63       535
   macro avg       0.57      0.56      0.56       535
weighted avg       0.61      0.63      0.62       535

Confusion matrix [rows=true, cols=pred] (True, False):
[[277  80]
 [117  61]]

===== Per-domain verdict accuracy (by true domain) =====
macro_econ             n= 132 acc=0.598
jobs_labor             n=  52 acc=0.538
business_finance       n=   8 acc=0.500
cost_of_living_housing n=  20 acc=0.650
healthcare_policy      n=  55 acc=0.709
public_health_crises   n=   6 acc=0.667
substances_gambling    n=   6 acc=0.667
family_demographics    n=  14 acc=0.786
law_crime_rights       n=  52 acc=0.635
institutions_elections n=  96 acc=0.646
foreign_affairs_security n=  18 acc=0.778
environment_energy_infra n=  27 acc=0.704
media_meta             n=  35 acc=0.543

====================================================================================================
gemma_test_predictions_with_experts_5_checkability.csv   |   model=gemma   |   k=5
====================================================================================================
Filtered by checkability (fact_checkable): 1267 -> 535
Test set size: 535
True domain distribution:
super_domain
socioeconomic_policy    288
governance_law          151
society_culture          29
foreign_security         28
environment_science      25
misc                     14
Name: count, dtype: int64

Predicted domain distribution (router):
domain_pred_router
socioeconomic_policy    278
governance_law          151
society_culture          39
environment_science      36
foreign_security         26
misc                      5
Name: count, dtype: int64

🌍 Domain routing accuracy: 0.776
Confusion matrix (rows=true, cols=pred):
[[246   2  28   6   6   0]
 [  3  16   6   2   1   0]

,file,model,k,mode,n_eval,accuracy,precision_true,recall_true,confusion_matrix,domain_acc,n_domain_eval,domain_confusion_matrix,f1_macro,f1_weighted,f1_true,f1_false
4,deepseek_test_predictions_with_experts_5_check...,deepseek,5,deepseek_k5,1263,0.661124,0.649474,0.866573,[[617 95]\n [333 218]],0.787015,1263,[[535 2 63 7 6 0]\n [ 8 99 12 0 ...,0.623554,0.638714,0.742479,0.504630
5,deepseek_test_predictions_with_experts_8_check...,deepseek,8,deepseek_k8,1263,0.609660,0.596646,0.949438,[[676 36]\n [457 94]],0.743468,1263,[[387 27 1 9 30 6 8 4]\n [ 8 116 ...,0.504428,0.533538,0.732791,0.276065
3,deepseek_test_predictions_with_experts_12_chec...,deepseek,12,deepseek_k12,1263,0.608868,0.599634,0.921348,[[656 56]\n [438 113]],0.679445,1226,[[227 16 2 3 7 0 1 2 1 9 1 ...,0.520178,0.546475,0.726467,0.313889
7,gemma_test_predictions_with_experts_5_checkabi...,gemma,5,gemma_k5,535,0.433645,0.660714,0.310924,[[111 246]\n [ 57 121]],0.775701,535,[[246 2 28 6 6 0]\n [ 3 16 6 2 ...,0.433447,0.429904,0.422857,0.444037
8,gemma_test_predictions_with_experts_8_checkabi...,gemma,8,gemma_k8,535,0.620561,0.695431,0.767507,[[274 83]\n [120 58]],0.738318,535,[[188 11 2 9 7 4 2 1]\n [ 4 53 ...,0.546665,0.607903,0.729694,0.363636
6,gemma_test_predictions_with_experts_12_checkab...,gemma,12,gemma_k12,535,0.631776,0.703046,0.775910,[[277 80]\n [117 61]],0.629559,521,[[91 20 1 3 3 0 1 3 0 5 1 2 2]\n [1...,0.560064,0.619492,0.737683,0.382445
1,Llama_test_predictions_with_experts_5_checkabi...,llama,5,llama_k5,1100,0.542727,0.752613,0.333333,[[216 432]\n [ 71 381]],0.770000,1100,[[487 3 45 4 9 2]\n [ 9 74 10 2 ...,0.532202,0.519699,0.462032,0.602372
2,Llama_test_predictions_with_experts_8_checkabi...,llama,8,llama_k8,1100,0.637273,0.682284,0.719136,[[466 182]\n [217 235]],0.743636,1100,[[350 24 2 6 29 2 4 2]\n [ 15 97 ...,0.620538,0.634737,0.700225,0.540852
0,Llama_test_predictions_with_experts_12_checkab...,llama,12,llama_k12,1100,0.633636,0.683109,0.705247,[[457 191]\n [212 240]],0.683817,1069,[[204 14 0 4 7 0 1 2 0 9 1 ...,0.618801,0.632201,0.694002,0.543601

# test

In [7]:
import argparse
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

SUPER_LABELS = [
    "economy",
    "health_social",
    "foreign_security",
    "law_rights",
    "politics_government",
    "environment_energy",
    "society_culture",
    "misc",
]

def norm_bool_label(x) -> str:
    """Normalisiert Labels robust auf 'True'/'False'."""
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "False"
    s = str(x).strip().strip(".,:;!?)(").lower()
    if s.startswith("true"):
        return "True"
    if s.startswith("false"):
        return "False"
    return "False"


def evaluate_predictions(csv_path: str):
    df = pd.read_csv(csv_path, dtype=str)

    # Required columns
    required = ["label", "verdict_pred"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            f"CSV missing required columns: {missing}\n"
            f"Found columns: {list(df.columns)}"
        )

    # Clean
    df = df.dropna(subset=["label", "verdict_pred"])
    df = df[df["label"].str.strip() != ""]
    df = df[df["verdict_pred"].str.strip() != ""]

    y_true = df["label"].map(norm_bool_label)
    y_pred = df["verdict_pred"].map(norm_bool_label)

    # Overall verdict metrics
    verdict_acc = accuracy_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred, labels=["True", "False"])

    print("\n==============================")
    print("✅ Verdict Evaluation (overall)")
    print("==============================")
    print(f"Samples: {len(df)}")
    print(f"Verdict Accuracy: {verdict_acc:.3f}\n")

    print("Classification report (True/False):")
    print(classification_report(y_true, y_pred, labels=["True", "False"], zero_division=0))

    print("Confusion matrix [rows=true, cols=pred] (True, False):")
    print(cm)

    # Optional: Routing accuracy (if available)
    if "super_domain" in df.columns and "domain_pred" in df.columns:
        df_r = df.dropna(subset=["super_domain", "domain_pred"])
        df_r = df_r[df_r["super_domain"].str.strip() != ""]
        df_r = df_r[df_r["domain_pred"].str.strip() != ""]

        if len(df_r) > 0:
            dom_acc = accuracy_score(df_r["super_domain"], df_r["domain_pred"])
            dom_cm = confusion_matrix(df_r["super_domain"], df_r["domain_pred"], labels=SUPER_LABELS)

            print("\n==================================")
            print("🌍 Domain Routing Evaluation")
            print("==================================")
            print(f"Routing samples: {len(df_r)}")
            print(f"Domain-Routing Accuracy: {dom_acc:.3f}")
            print("Domain-Routing Confusion Matrix (rows=true, cols=pred):")
            print(dom_cm)
            print("Domain label order:", SUPER_LABELS)

    # Optional: Per-domain verdict accuracy
    if "super_domain" in df.columns:
        print("\n=================================================")
        print("📊 Per-Domain Verdict Accuracy (by true super_domain)")
        print("=================================================")

        for dom in SUPER_LABELS:
            df_dom = df[df["super_domain"] == dom]
            if df_dom.empty:
                continue
            yt = df_dom["label"].map(norm_bool_label)
            yp = df_dom["verdict_pred"].map(norm_bool_label)
            acc_dom = accuracy_score(yt, yp)
            print(f"{dom:22s} n={len(df_dom):4d} acc={acc_dom:.3f}")

In [ ]:
from multiagent_pipeline_reassurance import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]

df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_8Classes",
    expert_root="adapters/Llama_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/Llama_test_predictions_with_experts_8_reassurance.csv",
    text_col="statement",
    label_col="label",
    domain_col="super_domain",
    sep="\t",
    max_rows=2000,                  # nur die ersten 100 Zeilen verwenden
    use_self_verification=True,    # Modell wird nach Antwort nochmal gefragt
)

ℹ️  max_rows=2000 → using first 1267 rows of the CSV.
Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [10:41<00:00,  1.98it/s]

Predicted domain distribution (router):
domain_pred_router
economy                506
politics_government    201
health_social          162
law_rights             139
foreign_security       114
society_culture         65
environment_energy      57
misc                    23
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: economy:   1%|          | 4/506 [01:39<3:38:11, 26.08s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says that Tennessee law requires that schools receive half of proceeds - $31 mil...

🧠 Expert: economy:   3%|▎         | 17/506 [06:56<3:30:31, 25.83s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says Charlie Crist voted against raising the minimum wage ....

🧠 Expert: economy:   4%|▍         | 21/506 [09:11<4:53:35, 36.32s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:   4%|▍         | 22/506 [09:47<4:53:06, 36.34s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:   5%|▍         | 25/506 [11:21<4:46:39, 35.76s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:   7%|▋         | 33/506 [14:25<3:23:29, 25.81s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Mitch McConnell opposed legislation to create and protect Kentucky jobs . . . he...

🧠 Expert: economy:   7%|▋         | 35/506 [15:20<3:39:36, 27.98s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: President Obama Sen . Harry Reid and Rep . Nancy Pelosi passed a $1.2 trillion s...

🧠 Expert: economy:   8%|▊         | 39/506 [16:51<3:23:39, 26.17s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: (Barack Obama) says hes going to reduce the long-term debt and deficit by $4 tri...

🧠 Expert: economy:   8%|▊         | 41/506 [18:12<4:15:50, 33.01s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: U.S. Rep . Lloyd Doggett is the most liberal man in the United States Congress ....

🧠 Expert: economy:  10%|▉         | 50/506 [22:00<3:29:39, 27.59s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Tom Suozzi raised taxes by hundreds of millions of dollars as Nassau County exec...

🧠 Expert: economy:  11%|█         | 55/506 [24:12<3:50:42, 30.69s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  12%|█▏        | 60/506 [26:03<3:10:41, 25.65s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: We spend in tax loopholes annually $1.1 trillion . Thats more than we spend on o...

🧠 Expert: economy:  12%|█▏        | 61/506 [26:26<3:03:42, 24.77s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: On the Bush tax cuts ....

🧠 Expert: economy:  13%|█▎        | 65/506 [28:20<3:53:31, 31.77s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  13%|█▎        | 66/506 [29:17<4:48:30, 39.34s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  13%|█▎        | 68/506 [29:59<3:37:08, 29.75s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Mitt Romney left Massachusetts $1 billion in debt ....

🧠 Expert: economy:  14%|█▎        | 69/506 [30:55<4:34:11, 37.65s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  15%|█▍        | 74/506 [33:04<3:53:32, 32.44s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  17%|█▋        | 85/506 [37:14<2:25:11, 20.69s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Property taxes have increased 20 percent under four years of Chris Christie ....

🧠 Expert: economy:  18%|█▊        | 91/506 [39:56<3:40:28, 31.88s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  19%|█▉        | 96/506 [42:21<3:26:49, 30.27s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: There would be tens of thousands of jobs created if President Barack Obama appro...

🧠 Expert: economy:  21%|██        | 105/506 [45:53<3:09:42, 28.38s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: 6400 Ohioans . lost manufacturing jobs in the month of September ....

🧠 Expert: economy:  22%|██▏       | 110/506 [48:07<3:29:26, 31.73s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  23%|██▎       | 115/506 [50:19<2:52:39, 26.50s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Mitt Romney boasts that he is proud to be the only major candidate for president...

🧠 Expert: economy:  23%|██▎       | 118/506 [51:36<2:55:42, 27.17s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: A voucher school that closed after 9 days this year collected $5.4 million in ta...

🧠 Expert: economy:  24%|██▍       | 123/506 [53:44<2:36:45, 24.56s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Weve introduced a bill that includes $12 billion in cuts over the next week ....

🧠 Expert: economy:  25%|██▌       | 129/506 [57:21<3:58:04, 37.89s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  26%|██▌       | 130/506 [57:57<3:53:45, 37.30s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  26%|██▋       | 134/506 [59:44<3:30:12, 33.90s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  27%|██▋       | 136/506 [1:00:34<3:02:29, 29.59s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: McCain still thinks it s okay when women don t earn equal pay for equal work ....

🧠 Expert: economy:  27%|██▋       | 137/506 [1:01:17<3:26:21, 33.55s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: The CBO says that if you raise the minimum wage to $10.10 an hour half a million...

🧠 Expert: economy:  29%|██▉       | 147/506 [1:05:35<2:40:24, 26.81s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  32%|███▏      | 163/506 [1:11:40<2:28:14, 25.93s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: While 9000 state employees were added to the states payroll Oregons revenue fore...

🧠 Expert: economy:  32%|███▏      | 164/506 [1:12:21<2:53:01, 30.35s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  33%|███▎      | 168/506 [1:14:36<3:16:58, 34.97s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says One of the states largest governments made charging this tax one of their t...

🧠 Expert: economy:  36%|███▋      | 184/506 [1:21:33<2:17:05, 25.55s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: All Aboard Florida is a 100 percent private venture . There is no state money in...

🧠 Expert: economy:  37%|███▋      | 186/506 [1:22:43<2:39:00, 29.82s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: In one year (President Obama) provided $90 billion in breaks to the green energy...

🧠 Expert: economy:  37%|███▋      | 187/506 [1:23:25<2:58:32, 33.58s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Hedge fund managers pay less in taxes than nurses and truck drivers ....

🧠 Expert: economy:  38%|███▊      | 191/506 [1:25:12<2:40:26, 30.56s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  38%|███▊      | 192/506 [1:25:53<2:56:17, 33.69s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says Mitt Romneys housing policy is Dont try and stop the foreclosure process . ...

🧠 Expert: economy:  38%|███▊      | 194/506 [1:26:50<2:45:17, 31.79s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  40%|███▉      | 200/506 [1:30:13<3:03:25, 35.97s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  40%|████      | 203/506 [1:31:54<2:57:38, 35.18s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  43%|████▎     | 218/506 [1:38:40<2:23:22, 29.87s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  44%|████▍     | 225/506 [1:41:52<2:38:42, 33.89s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  45%|████▍     | 227/506 [1:43:05<2:45:39, 35.62s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Sixteen [federal] programs exist to fight homelessness and some of them are dupl...

🧠 Expert: economy:  46%|████▌     | 231/506 [1:44:32<1:52:53, 24.63s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says Bill Clinton opposes President Barack Obamas plan to raise taxes on wealthy...

🧠 Expert: economy:  46%|████▌     | 234/506 [1:46:13<2:32:42, 33.69s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  46%|████▋     | 235/506 [1:47:09<3:02:37, 40.43s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  47%|████▋     | 236/506 [1:47:47<2:57:30, 39.45s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  49%|████▉     | 249/506 [1:53:21<1:46:16, 24.81s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: John Boozman supports privatizing Social Security...

🧠 Expert: economy:  49%|████▉     | 250/506 [1:54:17<2:26:16, 34.28s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  50%|████▉     | 252/506 [1:55:40<2:46:08, 39.25s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  53%|█████▎    | 268/506 [2:02:52<2:17:33, 34.68s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  53%|█████▎    | 269/506 [2:03:21<2:09:32, 32.80s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: On supporting right to work legislation in 2015...

🧠 Expert: economy:  54%|█████▎    | 271/506 [2:04:33<2:22:37, 36.42s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  54%|█████▍    | 274/506 [2:05:47<1:56:06, 30.03s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  55%|█████▍    | 276/506 [2:06:45<1:58:03, 30.80s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Before I was state treasurer my Rhode Island business helped create over 1000 jo...

🧠 Expert: economy:  62%|██████▏   | 313/506 [2:21:07<1:28:30, 27.51s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  65%|██████▍   | 328/506 [2:27:31<1:30:38, 30.56s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  65%|██████▌   | 330/506 [2:28:09<1:12:16, 24.64s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: On subsidies for ethanol production ....

🧠 Expert: economy:  66%|██████▌   | 332/506 [2:29:05<1:19:13, 27.32s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  66%|██████▌   | 335/506 [2:30:20<1:17:10, 27.08s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: In the four years before I became governor we increased state debt $5.2 billion ...

🧠 Expert: economy:  67%|██████▋   | 337/506 [2:31:25<1:24:37, 30.05s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Under conservative leadership Congress has reduced the federal deficit by 60 per...

🧠 Expert: economy:  67%|██████▋   | 340/506 [2:33:06<1:31:41, 33.14s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Poor people go to a payday lender . and they pay 300 400 500 percent interest ....

🧠 Expert: economy:  67%|██████▋   | 341/506 [2:33:48<1:38:04, 35.66s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: On the economic crisis the biggest problem in this whole process was the deregul...

🧠 Expert: economy:  68%|██████▊   | 343/506 [2:35:27<1:57:43, 43.33s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  70%|██████▉   | 352/506 [2:39:49<1:29:01, 34.68s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  70%|██████▉   | 353/506 [2:40:28<1:31:45, 35.98s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  71%|███████   | 357/506 [2:42:35<1:30:33, 36.47s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  71%|███████   | 359/506 [2:44:04<1:41:56, 41.61s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  71%|███████▏  | 361/506 [2:45:11<1:31:04, 37.69s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says that during his eight years as Florida governor we created 1.3 million net ...

🧠 Expert: economy:  73%|███████▎  | 371/506 [2:50:16<1:20:14, 35.66s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: On Donald Trumps track record in business...

🧠 Expert: economy:  74%|███████▍  | 374/506 [2:51:45<1:12:30, 32.96s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says Sean Duffy was a no-show as Ashland County District Attorney while he was o...

🧠 Expert: economy:  74%|███████▍  | 375/506 [2:52:05<1:02:54, 28.82s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Put simply less government spending equals more private sector jobs ....

🧠 Expert: economy:  75%|███████▌  | 382/506 [2:55:12<55:20, 26.78s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says that when the Rolling Stones performed in an Austin park they paid $25000 t...

🧠 Expert: economy:  76%|███████▋  | 387/506 [2:57:16<52:07, 26.29s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: State employees are actually going to get a pay raise ....

🧠 Expert: economy:  79%|███████▉  | 401/506 [3:03:09<45:43, 26.13s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Republicans tried to block the deficit commission ....

🧠 Expert: economy:  83%|████████▎ | 418/506 [3:10:38<44:44, 30.51s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Rand Paul wants to end all federal faith-based initiatives and even end the dedu...

🧠 Expert: economy:  83%|████████▎ | 421/506 [3:12:36<56:07, 39.62s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  85%|████████▍ | 430/506 [3:16:27<31:22, 24.77s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says Donald Trumps proposed tax treatment of hedge fund managers makes the curre...

🧠 Expert: economy:  86%|████████▌ | 435/506 [3:19:18<41:55, 35.43s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  86%|████████▋ | 437/506 [3:20:35<42:49, 37.24s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: The largest U.S. companies would owe $620 billion in U.S. taxes on the cash they...

🧠 Expert: economy:  87%|████████▋ | 440/506 [3:22:03<37:40, 34.26s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says Adam Hasner gives the wealthy tax breaks worth $250000 a year but hikes mid...

🧠 Expert: economy:  87%|████████▋ | 441/506 [3:22:40<38:02, 35.12s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: McCain got more money from Airbus U.S. executives than any other politician ....

🧠 Expert: economy:  88%|████████▊ | 443/506 [3:23:57<40:26, 38.51s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  91%|█████████ | 461/506 [3:32:03<22:39, 30.21s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Republicans dont think its a good idea to make the child care tax credit stronge...

🧠 Expert: economy:  92%|█████████▏| 464/506 [3:33:38<20:14, 28.91s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: This is the first time in the history that weve had the raising of a debt limit ...

🧠 Expert: economy:  92%|█████████▏| 467/506 [3:35:21<21:45, 33.47s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Wisconsin was literally broke when Republicans took office in January 2011 ....

🧠 Expert: economy:  93%|█████████▎| 473/506 [3:38:01<16:48, 30.57s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: A rural hospital in Missouri closes every 8 months . The legislatures failure to...

🧠 Expert: economy:  94%|█████████▎| 474/506 [3:38:22<14:47, 27.72s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says Thom Tillis gives tax breaks to yacht and jet owners ....

🧠 Expert: economy:  94%|█████████▍| 475/506 [3:38:59<15:44, 30.48s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  94%|█████████▍| 476/506 [3:39:56<19:13, 38.47s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  96%|█████████▌| 484/506 [3:43:41<12:36, 34.37s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  97%|█████████▋| 493/506 [3:47:37<06:12, 28.62s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: In 2004 20 percent of U.S. households were getting about 75 percent of their inc...

🧠 Expert: economy:  98%|█████████▊| 496/506 [3:48:50<04:36, 27.65s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says the government has gotten the TARP money back plus a profit ....

🧠 Expert: economy:  98%|█████████▊| 498/506 [3:50:02<04:29, 33.74s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy:  99%|█████████▉| 503/506 [3:52:52<01:53, 37.81s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

🧠 Expert: economy: 100%|██████████| 506/506 [3:54:19<00:00, 27.79s/it]

  ⚠️ Self-verification failed, keeping initial verdict. Error: No JSON object found in model output

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 Expert: health_social:   1%|          | 2/162 [00:41<54:27, 20.42s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Suzanne Bonamici supports a plan that will cut choice for Medicare Advantage sen...

🧠 Expert: health_social:   2%|▏         | 3/162 [01:05<58:32, 22.09s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Each year 18000 people die in America because they don t have health care ....

🧠 Expert: health_social:   2%|▏         | 4/162 [01:26<57:48, 21.95s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Active duty males in the military are twice as likely to develop prostate cancer...

🧠 Expert: health_social:   3%|▎         | 5/162 [01:44<52:55, 20.23s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Because of the federal health care law 300000 health plans canceled in Florida ....

🧠 Expert: health_social:   4%|▎         | 6/162 [01:59<48:35, 18.69s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Pre-existing conditions are covered under my (health care) plan ....

🧠 Expert: health_social:   4%|▍         | 7/162 [02:23<52:37, 20.37s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: In 1993 Newt Gingrich first advocated for the individual mandate in health care ...

🧠 Expert: health_social:   5%|▍         | 8/162 [02:47<55:21, 21.57s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Says as a result of the national health care reform the Congressional Budget Off...

🧠 Expert: health_social:   6%|▌         | 10/162 [03:38<1:00:40, 23.95s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Studies have shown that in the absence of federal reproductive health funds we a...

🧠 Expert: health_social:   7%|▋         | 11/162 [03:55<54:55, 21.83s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Obamacare insurance cooperative failures should be expected because theyre like ...

🧠 Expert: health_social:   7%|▋         | 12/162 [04:15<53:23, 21.36s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: A strong bipartisan majority in the House of Representatives voted to defund Oba...

🧠 Expert: health_social:   8%|▊         | 13/162 [04:38<53:47, 21.66s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: What the facts say is . the best scenario for kids is a loving mom and dad ....

🧠 Expert: health_social:   9%|▊         | 14/162 [04:54<49:37, 20.12s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Before World War II very few people actually had health insurance ....

🧠 Expert: health_social:  10%|▉         | 16/162 [05:33<47:08, 19.38s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Orrin Hatch co-sponsored a 1993 health care bill that had an individual mandate ...

🧠 Expert: health_social:  12%|█▏        | 19/162 [06:37<47:10, 19.79s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: In Florida we have 75000 on (a) waiting list for child care and 23000 on waiting...

🧠 Expert: health_social:  12%|█▏        | 20/162 [06:58<47:22, 20.02s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: The sex-offender registry has been around for a long time and the research thats...

🧠 Expert: health_social:  14%|█▎        | 22/162 [07:38<47:30, 20.36s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says In Oregon in 2010 49 percent of all pregnancies were unintended ....

🧠 Expert: health_social:  14%|█▍        | 23/162 [07:56<46:03, 19.88s/it]

  🔄 Self-verification changed verdict: False → True
     Claim: Insured Floridians pay about $2000 for every hospital stay to cover the cost of ...

🧠 Expert: health_social:  15%|█▌        | 25/162 [08:47<52:20, 22.92s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says that each year about 25000 American women become pregnant through rape or i...

🧠 Expert: health_social:  16%|█▌        | 26/162 [09:13<53:46, 23.72s/it]

  🔄 Self-verification changed verdict: True → False
     Claim: Says Denmarks suicide rate has been about twice as high as the United States ove...

In [1]:
pip freeze > requirements_freeze.txt

Note: you may need to restart the kernel to use updated packages.

In [7]:
evaluate_predictions("Results/Llama_test_predictions_with_experts_8_reassurance.csv")

==============================
✅ Verdict Evaluation (overall)
==============================
Samples: 1267
Verdict Accuracy: 0.591

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.64      0.64      0.64       714
       False       0.53      0.53      0.53       553

    accuracy                           0.59      1267
   macro avg       0.58      0.58      0.58      1267
weighted avg       0.59      0.59      0.59      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[454 260]
 [258 295]]

==================================
🌍 Domain Routing Evaluation
==================================
Routing samples: 1267
Domain-Routing Accuracy: 0.740
Domain-Routing Confusion Matrix (rows=true, cols=pred):
[[393  28   2   7  29   3   8   3]
 [ 15 108   3  13   1   0   3   0]
 [  8   3  95   9   2   2   2   1]
 [  7  13   5 106  11   1   2   0]
 [ 55   4   6   3 143  10   8   4]
 [  8   0   1   0   5  39   1   2]
 [  7   3   2   1   6   0  41   1]
 [ 13   3   0   0   4   2   0  12]]
Domain label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

=================================================
📊 Per-Domain Verdict Accuracy (by true super_domain)
=================================================
economy                n= 473 acc=0.651
health_social          n= 143 acc=0.517
foreign_security       n= 122 acc=0.393
law_rights             n= 145 acc=0.628
politics_government    n= 233 acc=0.618
environment_energy     n=  56 acc=0.518
society_culture        n=  61 acc=0.574
misc                   n=  34 acc=0.588

In [1]:
from multiagent_pipeline_2 import run_full_pipeline

SUPER_LABELS_8 = [
        "economy",
        "health_social",
        "foreign_security",
        "law_rights",
        "politics_government",
        "environment_energy",
        "society_culture",
        "misc",
]


df_pred = run_full_pipeline(
    base_model_id="meta-llama/Llama-3.1-8B-Instruct",
    router_lora_dir="adapters/llama-liar-statement-domain-lora_8Classes",
    expert_root="adapters/Llama_experts_8Classes",
    super_labels=SUPER_LABELS_8,
    test_path="Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv",
    out_path="Results/Llama_test_predictions_with_experts_8_2.csv",
)

2026-02-20 05:43:40.967310: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Test set size: 1267
True domain distribution:
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only:   0%|          | 0/1267 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🌍 Routing-only: 100%|██████████| 1267/1267 [10:39<00:00,  1.98it/s]

Predicted domain distribution (router):
domain_pred_router
economy                543
health_social          163
politics_government    157
law_rights             141
foreign_security       105
society_culture         66
environment_energy      60
misc                    32
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 economy:   1%|          | 6/543 [01:29<2:32:42, 17.06s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   1%|▏         | 8/543 [02:04<2:42:55, 18.27s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   2%|▏         | 10/543 [02:24<2:02:17, 13.77s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
🧠 economy:   2%|▏         | 12/543 [03:02<2:32:38, 17.25s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   3%|▎         | 14/543 [03:38<2:44:09, 18.62s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   4%|▍         | 22/543 [05:20<2:21:00, 16.24s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   5%|▍         | 26/543 [06:13<2:18:23, 16.06s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   7%|▋         | 37/543 [08:31<2:15:08, 16.02s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   8%|▊         | 44/543 [09:56<2:12:51, 15.97s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   9%|▊         | 47/543 [10:41<2:20:28, 16.99s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   9%|▉         | 49/543 [11:18<2:33:44, 18.67s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  13%|█▎        | 69/543 [14:37<1:53:30, 14.37s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  13%|█▎        | 73/543 [15:46<2:19:14, 17.78s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  14%|█▍        | 78/543 [17:03<2:23:03, 18.46s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  15%|█▌        | 82/543 [17:59<2:09:34, 16.86s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  17%|█▋        | 91/543 [20:00<2:06:13, 16.75s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  17%|█▋        | 95/543 [20:53<2:01:11, 16.23s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  18%|█▊        | 98/543 [21:46<2:17:27, 18.53s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  19%|█▉        | 104/543 [23:08<2:03:01, 16.81s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  22%|██▏       | 122/543 [26:50<1:46:20, 15.16s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  23%|██▎       | 125/543 [27:50<2:12:55, 19.08s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  24%|██▍       | 131/543 [29:21<2:05:19, 18.25s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  24%|██▍       | 133/543 [30:01<2:14:53, 19.74s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  25%|██▍       | 134/543 [30:28<2:30:58, 22.15s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  26%|██▌       | 140/543 [32:05<2:13:02, 19.81s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  26%|██▌       | 142/543 [32:42<2:13:32, 19.98s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  27%|██▋       | 147/543 [33:42<1:46:53, 16.20s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  27%|██▋       | 149/543 [34:20<2:00:34, 18.36s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  28%|██▊       | 154/543 [35:50<2:10:06, 20.07s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  29%|██▉       | 160/543 [37:02<1:42:00, 15.98s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  31%|███▏      | 170/543 [38:58<1:32:31, 14.88s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  34%|███▍      | 185/543 [42:14<1:43:31, 17.35s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  37%|███▋      | 199/543 [45:21<1:30:27, 15.78s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  37%|███▋      | 203/543 [46:21<1:33:43, 16.54s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  38%|███▊      | 208/543 [47:40<1:36:47, 17.34s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  39%|███▊      | 210/543 [48:30<2:00:09, 21.65s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  39%|███▉      | 212/543 [49:07<1:55:13, 20.89s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  40%|████      | 218/543 [50:40<1:43:18, 19.07s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  41%|████▏     | 224/543 [52:13<1:32:28, 17.39s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  41%|████▏     | 225/543 [52:41<1:49:16, 20.62s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  43%|████▎     | 232/543 [54:29<1:29:39, 17.30s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  43%|████▎     | 233/543 [54:57<1:45:51, 20.49s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  44%|████▎     | 237/543 [55:57<1:31:56, 18.03s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  46%|████▌     | 250/543 [58:47<1:24:37, 17.33s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  48%|████▊     | 258/543 [1:00:42<1:22:11, 17.30s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  49%|████▉     | 266/543 [1:02:41<1:18:58, 17.11s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  50%|████▉     | 271/543 [1:03:47<1:13:06, 16.13s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  51%|█████     | 277/543 [1:05:33<1:28:50, 20.04s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  51%|█████▏    | 279/543 [1:06:21<1:38:21, 22.36s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  53%|█████▎    | 289/543 [1:08:28<1:10:34, 16.67s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  54%|█████▍    | 294/543 [1:09:46<1:13:16, 17.66s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  54%|█████▍    | 295/543 [1:10:14<1:26:07, 20.84s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  55%|█████▍    | 298/543 [1:11:06<1:19:39, 19.51s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  56%|█████▌    | 303/543 [1:12:07<1:03:58, 16.00s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  57%|█████▋    | 309/543 [1:13:38<1:06:46, 17.12s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  60%|██████    | 327/543 [1:16:45<56:49, 15.78s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  64%|██████▍   | 347/543 [1:20:35<55:35, 17.02s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  67%|██████▋   | 364/543 [1:24:00<43:53, 14.71s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  67%|██████▋   | 365/543 [1:24:28<55:40, 18.77s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  68%|██████▊   | 367/543 [1:25:08<59:23, 20.25s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  68%|██████▊   | 371/543 [1:26:18<58:20, 20.35s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  70%|██████▉   | 380/543 [1:28:26<50:25, 18.56s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  72%|███████▏  | 389/543 [1:30:23<44:01, 17.15s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  74%|███████▍  | 403/543 [1:33:33<39:40, 17.01s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  77%|███████▋  | 420/543 [1:36:52<31:51, 15.54s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  79%|███████▊  | 427/543 [1:38:22<32:56, 17.04s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  80%|███████▉  | 433/543 [1:39:48<31:17, 17.07s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  83%|████████▎ | 452/543 [1:43:32<23:34, 15.54s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  84%|████████▍ | 455/543 [1:44:28<26:43, 18.23s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  86%|████████▌ | 468/543 [1:47:08<20:54, 16.72s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 471/543 [1:47:55<20:55, 17.44s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 472/543 [1:48:23<24:22, 20.59s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 474/543 [1:49:01<23:47, 20.69s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████ | 492/543 [1:52:31<12:51, 15.12s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████ | 495/543 [1:53:25<14:35, 18.23s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████▏| 496/543 [1:53:53<16:35, 21.18s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  92%|█████████▏| 502/543 [1:55:20<13:43, 20.08s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  94%|█████████▍| 512/543 [1:57:58<09:23, 18.19s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  95%|█████████▍| 514/543 [1:58:36<09:21, 19.36s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  96%|█████████▌| 521/543 [2:00:08<06:04, 16.55s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  96%|█████████▌| 522/543 [2:00:36<07:00, 20.03s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  98%|█████████▊| 530/543 [2:02:25<03:40, 17.00s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▊| 535/543 [2:03:30<02:09, 16.19s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▉| 537/543 [2:04:14<01:57, 19.55s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▉| 539/543 [2:04:49<01:18, 19.59s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▉| 540/543 [2:05:17<01:06, 22.08s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy: 100%|██████████| 543/543 [2:06:06<00:00, 13.94s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 health_social: 100%|██████████| 163/163 [27:22<00:00, 10.07s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 foreign_security:  78%|███████▊  | 82/105 [13:01<05:27, 14.23s/it]

[WARN] JSON parse failed for domain 'foreign_security': No JSON object found in model output

🧠 foreign_security: 100%|██████████| 105/105 [16:43<00:00,  9.56s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 law_rights:  33%|███▎      | 46/141 [07:28<23:41, 14.96s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  36%|███▌      | 51/141 [08:34<23:55, 15.95s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  44%|████▍     | 62/141 [10:32<19:15, 14.63s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  47%|████▋     | 66/141 [11:32<21:18, 17.05s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  57%|█████▋    | 81/141 [14:15<14:53, 14.90s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  77%|███████▋  | 109/141 [19:17<07:38, 14.31s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights: 100%|██████████| 141/141 [24:36<00:00, 10.47s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 politics_government:  36%|███▌      | 56/157 [08:27<24:04, 14.30s/it]

[WARN] JSON parse failed for domain 'politics_government': No JSON object found in model output

🧠 politics_government:  77%|███████▋  | 121/157 [18:28<08:49, 14.71s/it]

[WARN] JSON parse failed for domain 'politics_government': No JSON object found in model output

🧠 politics_government:  99%|█████████▊| 155/157 [23:34<00:27, 13.99s/it]

[WARN] JSON parse failed for domain 'politics_government': No JSON object found in model output

🧠 politics_government: 100%|██████████| 157/157 [23:51<00:00,  9.12s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 environment_energy:  13%|█▎        | 8/60 [01:34<14:00, 16.16s/it]

[WARN] JSON parse failed for domain 'environment_energy': No JSON object found in model output

🧠 environment_energy: 100%|██████████| 60/60 [09:17<00:00,  9.28s/it]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 society_culture:   2%|▏         | 1/66 [00:32<35:09, 32.45s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   3%|▎         | 2/66 [01:03<33:43, 31.61s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   5%|▍         | 3/66 [01:36<33:53, 32.27s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   6%|▌         | 4/66 [02:07<32:59, 31.93s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   8%|▊         | 5/66 [02:39<32:13, 31.70s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   9%|▉         | 6/66 [03:11<31:51, 31.86s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  11%|█         | 7/66 [03:42<31:02, 31.57s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  12%|█▏        | 8/66 [04:10<29:21, 30.37s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  14%|█▎        | 9/66 [04:38<28:06, 29.59s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  15%|█▌        | 10/66 [05:06<27:15, 29.21s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  18%|█▊        | 12/66 [05:52<23:47, 26.44s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  20%|█▉        | 13/66 [06:20<23:45, 26.90s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  21%|██        | 14/66 [06:48<23:36, 27.25s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  23%|██▎       | 15/66 [07:16<23:25, 27.55s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  26%|██▌       | 17/66 [08:07<21:48, 26.70s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  29%|██▉       | 19/66 [08:45<18:30, 23.64s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  30%|███       | 20/66 [09:14<19:13, 25.07s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  32%|███▏      | 21/66 [09:41<19:24, 25.87s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  33%|███▎      | 22/66 [10:10<19:32, 26.66s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  35%|███▍      | 23/66 [10:38<19:29, 27.20s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  36%|███▋      | 24/66 [11:07<19:25, 27.74s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  38%|███▊      | 25/66 [11:35<19:00, 27.82s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  39%|███▉      | 26/66 [12:03<18:36, 27.90s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  44%|████▍     | 29/66 [13:11<15:15, 24.75s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  45%|████▌     | 30/66 [13:39<15:30, 25.85s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  47%|████▋     | 31/66 [14:08<15:27, 26.51s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  48%|████▊     | 32/66 [14:36<15:18, 27.02s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  52%|█████▏    | 34/66 [15:31<14:38, 27.47s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  53%|█████▎    | 35/66 [16:00<14:17, 27.67s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  55%|█████▍    | 36/66 [16:27<13:50, 27.67s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  56%|█████▌    | 37/66 [16:55<13:22, 27.66s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  58%|█████▊    | 38/66 [17:23<12:58, 27.80s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  59%|█████▉    | 39/66 [17:51<12:34, 27.93s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  61%|██████    | 40/66 [18:19<12:07, 27.99s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  64%|██████▎   | 42/66 [19:14<11:05, 27.72s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  65%|██████▌   | 43/66 [19:42<10:40, 27.84s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  67%|██████▋   | 44/66 [20:10<10:13, 27.88s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  68%|██████▊   | 45/66 [20:38<09:46, 27.94s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  73%|███████▎  | 48/66 [21:48<07:38, 25.46s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  74%|███████▍  | 49/66 [22:16<07:26, 26.28s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  76%|███████▌  | 50/66 [22:44<07:07, 26.71s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  77%|███████▋  | 51/66 [23:12<06:46, 27.13s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  79%|███████▉  | 52/66 [23:40<06:22, 27.34s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  82%|████████▏ | 54/66 [24:28<05:11, 25.95s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  83%|████████▎ | 55/66 [24:56<04:53, 26.64s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  85%|████████▍ | 56/66 [25:24<04:30, 27.08s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  86%|████████▋ | 57/66 [25:52<04:06, 27.38s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  88%|████████▊ | 58/66 [26:21<03:41, 27.74s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  89%|████████▉ | 59/66 [26:49<03:14, 27.73s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  91%|█████████ | 60/66 [27:17<02:47, 27.94s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  95%|█████████▌| 63/66 [28:26<01:17, 25.68s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture: 100%|██████████| 66/66 [29:25<00:00, 26.75s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 misc:  44%|████▍     | 14/32 [02:46<04:32, 15.15s/it]

[WARN] JSON parse failed for domain 'misc': No JSON object found in model output

🧠 misc:  75%|███████▌  | 24/32 [04:37<01:56, 14.51s/it]

[WARN] JSON parse failed for domain 'misc': No JSON object found in model output

🧠 misc: 100%|██████████| 32/32 [05:57<00:00, 11.17s/it]

🌍 Domain routing accuracy: 0.718
Confusion matrix (rows=true, cols=pred):
[[403  28   0   5  20   5   7   5]
 [ 13 110   2  12   2   0   4   0]
 [ 11   2  90  11   2   3   2   1]
 [  9  15   5 103   8   1   2   2]
 [ 69   4   5   5 117  11  12  10]
 [ 12   0   1   0   3  38   2   0]
 [ 10   2   2   5   3   0  37   2]
 [ 16   2   0   0   2   2   0  12]]
Label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict accuracy (overall): 0.639

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.67      0.68       714
       False       0.58      0.60      0.59       553

    accuracy                           0.64      1267
   macro avg       0.63      0.63      0.63      1267
weighted avg       0.64      0.64      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[477 237]
 [221 332]]

===== Per-domain verdict accuracy (by true domain) =====
economy                n= 473 acc=0.643
health_social          n= 143 acc=0.622
foreign_security       n= 122 acc=0.697
law_rights             n= 145 acc=0.634
politics_government    n= 233 acc=0.639
environment_energy     n=  56 acc=0.625
society_culture        n=  61 acc=0.541
misc                   n=  34 acc=0.647

[debug] Fallback count (parsing/enforcer): 151

💾 Saved predictions to: Results/Llama_test_predictions_with_experts_8_2.csv

In [3]:
evaluate_predictions("Results/Llama_test_predictions_with_experts_8_2.csv")

==============================
✅ Verdict Evaluation (overall)
==============================
Samples: 1267
Verdict Accuracy: 0.639

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.68      0.67      0.68       714
       False       0.58      0.60      0.59       553

    accuracy                           0.64      1267
   macro avg       0.63      0.63      0.63      1267
weighted avg       0.64      0.64      0.64      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[477 237]
 [221 332]]

==================================
🌍 Domain Routing Evaluation
==================================
Routing samples: 1267
Domain-Routing Accuracy: 0.718
Domain-Routing Confusion Matrix (rows=true, cols=pred):
[[403  28   0   5  20   5   7   5]
 [ 13 110   2  12   2   0   4   0]
 [ 11   2  90  11   2   3   2   1]
 [  9  15   5 103   8   1   2   2]
 [ 69   4   5   5 117  11  12  10]
 [ 12   0   1   0   3  38   2   0]
 [ 10   2   2   5   3   0  37   2]
 [ 16   2   0   0   2   2   0  12]]
Domain label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

=================================================
📊 Per-Domain Verdict Accuracy (by true super_domain)
=================================================
economy                n= 473 acc=0.643
health_social          n= 143 acc=0.622
foreign_security       n= 122 acc=0.697
law_rights             n= 145 acc=0.634
politics_government    n= 233 acc=0.639
environment_energy     n=  56 acc=0.625
society_culture        n=  61 acc=0.541
misc                   n=  34 acc=0.647

In [9]:
# =========================
# 0) Environment & Imports
# =========================
import os
os.environ.setdefault("TRANSFORMERS_NO_TF", "1")
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "1")  # eine GPU auswählen

import json
import torch
import pandas as pd
from typing import Literal, Dict, Any
from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    pipeline as hf_pipeline,
)
from peft import PeftModel

from langchain_experimental.pydantic_v1 import BaseModel, Field
from langchain_experimental.llms import LMFormatEnforcer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# =========================
# 1) Konstanten & Labels
# =========================

BASE_MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"

# Router-LoRA (Statement -> super_domain)
ROUTER_LORA_DIR = "./adapters/llama-liar-statement-domain-lora_8Classes"  # <--- ANPASSEN

# Experten-LoRAs: je Domain ein Unterordner in EXPERT_ROOT
EXPERT_ROOT = "./adapters/Llama_experts_8Classes"  # <--- ANPASSEN

SUPER_LABELS = [
    "economy",
    "health_social",
    "foreign_security",
    "law_rights",
    "politics_government",
    "environment_energy",
    "society_culture",
    "misc",
]

# =========================
# 2) JSON-Schema & Helper
# =========================

class ClaimVerdict(BaseModel):
    verdict: Literal["True", "False"] = Field(..., description="Binary verdict")
    explanation: str = Field(..., description="2–4 sentences, brief, no stepwise reasoning")

JSON_SCHEMA = ClaimVerdict.schema()


def extract_first_json(text_or_obj):
    """
    Versucht robust, ein JSON-Objekt zu extrahieren.
    - Falls schon ein dict: direkt zurückgeben
    - Falls Liste mit dicts: ersten dict nehmen
    - Falls String: ersten JSON-Block via JSONDecoder finden
    """
    # Falls LMFormatEnforcer schon ein Dict zurückgibt
    if isinstance(text_or_obj, dict):
        return text_or_obj

    if isinstance(text_or_obj, list):
        # evtl. Liste von Strings / Dicts
        for el in text_or_obj:
            if isinstance(el, dict):
                return el
            if isinstance(el, str):
                try:
                    dec = json.JSONDecoder()
                    s = el.strip()
                    for i, ch in enumerate(s):
                        if ch == "{":
                            try:
                                obj, _ = dec.raw_decode(s[i:])
                                return obj
                            except json.JSONDecodeError:
                                continue
                except Exception:
                    continue

    if not isinstance(text_or_obj, str):
        raise ValueError(f"Cannot parse JSON from type {type(text_or_obj)}")

    dec = json.JSONDecoder()
    s = text_or_obj.strip()
    for i, ch in enumerate(s):
        if ch == "{":
            try:
                obj, _ = dec.raw_decode(s[i:])
                return obj
            except json.JSONDecodeError:
                continue

    # Wenn wir hier ankommen, ist wirklich kein JSON drin
    raise ValueError("No JSON object found in model output")


def norm_bool_label(x: str) -> str:
    if not isinstance(x, str):
        return "False"
    s = x.strip().strip(".,:;!?)(").lower()
    if s.startswith("true"):
        return "True"
    if s.startswith("false"):
        return "False"
    return "False"


# =========================
# 3) Router: Statement -> super_domain
# =========================

ROUTER_SYSTEM_PROMPT = """You are a strict domain classifier.

You receive a political or public policy claim (statement) and must map it
to exactly ONE high-level domain label from this list:

- economy: money, jobs, taxes, trade, business, budget, social security, pensions, stimulus
- health_social: healthcare, medicare, medicaid, public health, drugs, families, women, children, veterans, hunger, disability
- foreign_security: foreign policy, wars, military, terrorism, homeland security, nuclear weapons, international relations
- law_rights: crime, courts, civil rights, guns, immigration, legal issues, human rights, abortion, constitutional questions
- politics_government: elections, campaigns, candidates, parties, congress, political promises, redistricting, government rules and procedures
- environment_energy: climate, environment, energy, oil, gas, water, weather, transportation, pollution, natural resources
- society_culture: education, religion, diversity, LGBT, marriage, sports, pop culture, social norms, demographics
- misc: everything that does not clearly fit any of the above

You MUST answer with EXACTLY ONE label string from this list.
Do NOT explain. Only output the label.
"""


def run_router(df: pd.DataFrame) -> pd.Series:
    """
    Phase 1: Router-LoRA laden, alle Statements routen, danach Modell freigeben.
    """
    print("\n=== Phase 1: Routing (Statement -> super_domain) ===")

    # Tokenizer
    try:
        tokenizer = AutoTokenizer.from_pretrained(ROUTER_LORA_DIR, use_fast=True)
    except Exception:
        tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, use_fast=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # Base + LoRA auf *eine* GPU (oder CPU)
    base = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        torch_dtype=torch.float16 if device.type == "cuda" else torch.float32,
    ).to(device)

    model = PeftModel.from_pretrained(base, ROUTER_LORA_DIR)
    model = model.to(device)
    model.eval()

    import re

    preds = []

    label_list = ", ".join(SUPER_LABELS)

    for row in tqdm(df.itertuples(), total=len(df),
                   desc="🌍 Routing-only", dynamic_ncols=True):
        statement = getattr(row, "statement")

        user_content = (
            f"Valid labels:\n{label_list}\n\n"
            f"Statement:\n{statement}\n\n"
            "Return ONLY ONE label from the list above.\n"
            "Respond ONLY with the label.\n\n"
            "Label:"
        )

        messages = [
            {"role": "system", "content": ROUTER_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ]

        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            padding=True,
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            gen = model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                pad_token_id=tokenizer.pad_token_id,
                max_new_tokens=8,
                do_sample=False,
            )

        new_tokens = gen[0][inputs["input_ids"].shape[1]:]
        answer = tokenizer.decode(new_tokens, skip_special_tokens=True).strip().lower()

        if not answer:
            preds.append("misc")
            continue

        # 1) exakte Wort-Matches
        pred_dom = "misc"
        for L in SUPER_LABELS:
            pattern = r"\b" + re.escape(L.lower()) + r"\b"
            if re.search(pattern, answer):
                pred_dom = L
                break
        else:
            # 2) substring fallback
            for L in SUPER_LABELS:
                if L.lower() in answer:
                    pred_dom = L
                    break

        preds.append(pred_dom)

    # Router-Modell freigeben
    del model
    del base
    torch.cuda.empty_cache()

    return pd.Series(preds, index=df.index, name="domain_pred_router")


# =========================
# 4) Experten + LMFormatEnforcer
# =========================

def build_expert_system_prompt(domain_name: str) -> str:
    return f"""You are a fact-checking expert specialized in the '{domain_name}' domain.

You receive a political or public policy claim (statement) and must decide if it is factually correct.

You must output a JSON object that follows this schema:

{json.dumps(JSON_SCHEMA, indent=2)}

The field "verdict" MUST be either "True" or "False".
The field "explanation" MUST be 2–4 concise sentences. 
Do NOT include step-by-step reasoning or lists.

Reply with JSON only. No markdown, no extra text.
"""


def run_expert_for_domain(df: pd.DataFrame, domain_name: str):
    """
    Phase 2 (pro Domain):
    - Experten-LoRA für 'domain_name' laden
    - alle Zeilen dieser Domain fact-checken (mit LMFormatEnforcer)
    - Modell danach freigeben
    """
    expert_dir = os.path.join(EXPERT_ROOT, domain_name)
    if not os.path.isdir(expert_dir):
        raise FileNotFoundError(f"Expert directory for domain '{domain_name}' not found: {expert_dir}")

    print(f"\n=== Experten-Fact-Check für Domain '{domain_name}' (n={len(df)}) ===")

    # Tokenizer
    try:
        tokenizer = AutoTokenizer.from_pretrained(expert_dir, use_fast=True)
    except Exception:
        tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, use_fast=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # Base + LoRA
    base = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        torch_dtype=torch.float16 if device.type == "cuda" else torch.float32,
    ).to(device)

    model = PeftModel.from_pretrained(base, expert_dir)
    model = model.to(device)
    model.eval()

    # HF-Pipeline
    gen_pipe = hf_pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        do_sample=False,
        return_full_text=False,
    )

    # LMFormatEnforcer
    enforced_llm = LMFormatEnforcer(
        pipeline=gen_pipe,
        json_schema=JSON_SCHEMA,
    )

    def fact_check_one(statement: str) -> Dict[str, Any]:
        """
        Ruft den Experten + LMFormatEnforcer auf und gibt IMMER ein dict mit
        verdict ("True"/"False") und explanation (str) zurück.
        Jede Art von Parsing-/Enforcer-Fehler wird abgefangen.
        """
        system_prompt = build_expert_system_prompt(domain_name)
        user_content = f"Claim:\n{statement}\n\nReturn the JSON object now."

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]

        try:
            prompt_text = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        except Exception:
            prompt_text = (
                f"[SYSTEM]\n{system_prompt}\n[/SYSTEM]\n"
                f"User:\n{user_content}\nAssistant (JSON only):"
            )

        try:
            raw = enforced_llm.invoke(prompt_text, max_new_tokens=192)
            parsed = extract_first_json(raw)
            verdict = parsed.get("verdict")
            expl = parsed.get("explanation", "").strip()
        except Exception as e:
            # Hier landen wir, wenn entweder invoke oder JSON-Parsing schiefgeht
            print(f"[WARN] JSON parse failed for domain '{domain_name}': {e}")
            verdict = "False"
            expl = f"Fallback due to parsing error: {str(e)[:200]}"

        if verdict not in ["True", "False"]:
            verdict = "False"
        if not expl:
            expl = "No explanation was provided."

        return {"verdict": verdict, "explanation": expl}

    verdicts = []
    explanations = []

    for row in tqdm(df.itertuples(), total=len(df),
                   desc=f"🧠 {domain_name}", dynamic_ncols=True):
        statement = getattr(row, "statement")
        res = fact_check_one(statement)
        verdicts.append(norm_bool_label(res["verdict"]))
        explanations.append(res["explanation"])

    # Modell freigeben
    del model
    del base
    torch.cuda.empty_cache()

    return pd.Series(verdicts, index=df.index), pd.Series(explanations, index=df.index)


# =========================
# 5) Test-CSV einlesen
# =========================

test_path = "Results/preprocessed_test_cleaned_binary_with_super_domain_8.csv"  # <--- ANPASSEN

df_test = pd.read_csv(
    test_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

df_test = df_test.dropna(subset=["statement", "label"])
df_test = df_test[df_test["statement"].str.strip() != ""]
df_test = df_test[df_test["label"].isin(["True", "False"])]

print("Testset size:", len(df_test))
if "super_domain" in df_test.columns:
    print("Super-Domain-Verteilung (true):")
    print(df_test["super_domain"].value_counts())


# =========================
# 6) Phase 1: Router laufen lassen
# =========================

df_test["domain_pred_router"] = run_router(df_test)

print("\nRouting-only Verteilung:")
print(df_test["domain_pred_router"].value_counts())


# =========================
# 7) Phase 2: Experten pro Domain
# =========================

df_test["domain_pred"] = df_test["domain_pred_router"]
df_test["verdict_pred"] = "False"
df_test["explanation_pred"] = ""

for dom in SUPER_LABELS:
    idxs = df_test.index[df_test["domain_pred_router"] == dom].tolist()
    if not idxs:
        print(f"\n⚠️ Keine vom Router zugewiesenen Beispiele für Domain '{dom}'.")
        continue

    df_dom = df_test.loc[idxs]
    v_dom, e_dom = run_expert_for_domain(df_dom, dom)

    df_test.loc[idxs, "verdict_pred"] = v_dom
    df_test.loc[idxs, "explanation_pred"] = e_dom


# =========================
# 8) Metriken
# =========================

print("\nBeispiel-Zeilen mit Predictions:")
cols_show = ["statement", "super_domain", "domain_pred", "label", "verdict_pred"]
print(df_test[[c for c in cols_show if c in df_test.columns]].head())

# 8a) Domain-Routing-Accuracy
if "super_domain" in df_test.columns:
    true_dom = df_test["super_domain"]
    pred_dom = df_test["domain_pred"]
    dom_acc = accuracy_score(true_dom, pred_dom)
    print(f"\n🌍 Domain-Routing Accuracy: {dom_acc:.3f}")
    print("Domain-Routing Confusion Matrix (rows=true, cols=pred):")
    print(confusion_matrix(true_dom, pred_dom, labels=SUPER_LABELS))
    print("Domain label order:", SUPER_LABELS)

# 8b) Verdict-Accuracy gesamt
y_true = df_test["label"].map(norm_bool_label)
y_pred = df_test["verdict_pred"].map(norm_bool_label)

verdict_acc = accuracy_score(y_true, y_pred)
print(f"\n✅ Verdict Accuracy (gesamt): {verdict_acc:.3f}\n")

print("Classification report (True/False):")
print(classification_report(y_true, y_pred, labels=["True", "False"], zero_division=0))

print("Confusion matrix [rows=true, cols=pred] (True, False):")
print(confusion_matrix(y_true, y_pred, labels=["True", "False"]))

# 8c) Per-Domain Verdict-Accuracy
if "super_domain" in df_test.columns:
    print("\n===== Per-Domain Verdict-Accuracy (nach true super_domain) =====")
    for dom in SUPER_LABELS:
        df_dom_true = df_test[df_test["super_domain"] == dom]
        if df_dom_true.empty:
            continue
        yt = df_dom_true["label"].map(norm_bool_label)
        yp = df_dom_true["verdict_pred"].map(norm_bool_label)
        acc_dom = accuracy_score(yt, yp)
        print(f"{dom:22s} n={len(df_dom_true):4d} acc={acc_dom:.3f}")


# =========================
# 9) Ergebnisse speichern
# =========================

out_path = "Results/test_predictions_with_experts_sequential.csv"  # <--- ANPASSEN
os.makedirs(os.path.dirname(out_path), exist_ok=True)
df_test.to_csv(out_path, index=False, encoding="utf-8")
print(f"\n💾 Predictions gespeichert unter:\n{out_path}")

Using device: cuda
Testset size: 1267
Super-Domain-Verteilung (true):
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

=== Phase 1: Routing (Statement -> super_domain) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🌍 Routing-only: 100%|██████████| 1267/1267 [10:21<00:00,  2.04it/s]

Routing-only Verteilung:
domain_pred_router
economy                543
health_social          163
politics_government    157
law_rights             141
foreign_security       105
society_culture         66
environment_energy      60
misc                    32
Name: count, dtype: int64

=== Experten-Fact-Check für Domain 'economy' (n=543) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 economy:   1%|          | 6/543 [01:23<2:24:38, 16.16s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   1%|▏         | 8/543 [01:57<2:35:06, 17.39s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   2%|▏         | 12/543 [02:51<2:23:42, 16.24s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   3%|▎         | 14/543 [03:25<2:34:18, 17.50s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   4%|▍         | 21/543 [04:50<2:13:04, 15.30s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   4%|▍         | 22/543 [05:17<2:42:12, 18.68s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   5%|▍         | 26/543 [06:07<2:19:41, 16.21s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   6%|▋         | 35/543 [08:00<2:15:07, 15.96s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   7%|▋         | 37/543 [08:33<2:25:12, 17.22s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   8%|▊         | 44/543 [09:57<2:12:17, 15.91s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:   9%|▊         | 47/543 [10:41<2:15:58, 16.45s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  13%|█▎        | 69/543 [14:25<1:49:49, 13.90s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  13%|█▎        | 73/543 [15:26<2:05:17, 16.00s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  15%|█▌        | 82/543 [17:18<1:52:58, 14.70s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  17%|█▋        | 91/543 [19:11<1:59:27, 15.86s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  17%|█▋        | 95/543 [20:02<1:55:23, 15.46s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  19%|█▉        | 104/543 [21:49<1:51:43, 15.27s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  22%|██▏       | 122/543 [25:22<1:42:40, 14.63s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  23%|██▎       | 125/543 [26:19<2:06:48, 18.20s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  24%|██▍       | 131/543 [27:49<2:02:38, 17.86s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  26%|██▌       | 140/543 [30:09<2:06:07, 18.78s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  26%|██▌       | 142/543 [30:45<2:08:23, 19.21s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  27%|██▋       | 147/543 [31:44<1:44:08, 15.78s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  28%|██▊       | 154/543 [33:28<1:59:41, 18.46s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  29%|██▉       | 160/543 [34:39<1:38:58, 15.51s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  31%|███▏      | 170/543 [36:32<1:30:21, 14.54s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  34%|███▍      | 185/543 [39:42<1:39:19, 16.65s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  37%|███▋      | 199/543 [42:47<1:28:17, 15.40s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  38%|███▊      | 208/543 [44:46<1:29:35, 16.05s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  39%|███▊      | 210/543 [45:36<1:55:32, 20.82s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  40%|███▉      | 217/543 [47:15<1:30:27, 16.65s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  40%|████      | 218/543 [47:42<1:47:05, 19.77s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  41%|████▏     | 224/543 [49:18<1:34:11, 17.72s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  41%|████▏     | 225/543 [49:45<1:48:49, 20.53s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  42%|████▏     | 228/543 [50:41<1:44:08, 19.84s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  43%|████▎     | 232/543 [51:37<1:29:46, 17.32s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  43%|████▎     | 233/543 [52:04<1:44:24, 20.21s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  44%|████▎     | 237/543 [53:02<1:29:48, 17.61s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  46%|████▌     | 250/543 [55:55<1:25:34, 17.52s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  48%|████▊     | 258/543 [57:48<1:20:53, 17.03s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  49%|████▉     | 266/543 [59:38<1:14:11, 16.07s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  50%|████▉     | 271/543 [1:00:42<1:09:23, 15.31s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  51%|█████▏    | 279/543 [1:03:07<1:30:19, 20.53s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  53%|█████▎    | 289/543 [1:05:10<1:07:35, 15.97s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  54%|█████▍    | 295/543 [1:06:32<1:06:33, 16.10s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  55%|█████▍    | 298/543 [1:07:25<1:12:53, 17.85s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  57%|█████▋    | 309/543 [1:09:35<1:00:48, 15.59s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  59%|█████▉    | 322/543 [1:11:44<51:49, 14.07s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  60%|██████    | 327/543 [1:12:51<57:43, 16.04s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  62%|██████▏   | 339/543 [1:14:57<48:22, 14.23s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  64%|██████▍   | 347/543 [1:16:40<50:12, 15.37s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  67%|██████▋   | 364/543 [1:19:52<43:41, 14.64s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  67%|██████▋   | 365/543 [1:20:18<53:58, 18.20s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  68%|██████▊   | 367/543 [1:20:56<56:33, 19.28s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  68%|██████▊   | 371/543 [1:22:04<56:02, 19.55s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  70%|██████▉   | 380/543 [1:24:06<46:34, 17.14s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  71%|███████   | 384/543 [1:24:59<42:17, 15.96s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  72%|███████▏  | 389/543 [1:26:12<43:33, 16.97s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  74%|███████▍  | 403/543 [1:29:09<37:34, 16.10s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  77%|███████▋  | 420/543 [1:32:25<30:17, 14.77s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  79%|███████▊  | 427/543 [1:33:53<31:50, 16.47s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  80%|███████▉  | 433/543 [1:35:15<29:32, 16.11s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  83%|████████▎ | 452/543 [1:38:52<22:20, 14.73s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  84%|████████▍ | 455/543 [1:39:45<25:23, 17.31s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  86%|████████▌ | 468/543 [1:42:25<20:39, 16.52s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 471/543 [1:43:10<20:03, 16.72s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 472/543 [1:43:36<23:11, 19.59s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  87%|████████▋ | 474/543 [1:44:12<22:34, 19.63s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████ | 492/543 [1:47:35<12:15, 14.41s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████ | 495/543 [1:48:27<13:51, 17.32s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  91%|█████████▏| 496/543 [1:48:52<15:35, 19.90s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  92%|█████████▏| 502/543 [1:50:12<12:10, 17.83s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  94%|█████████▍| 512/543 [1:52:40<08:58, 17.37s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  95%|█████████▍| 514/543 [1:53:15<08:48, 18.22s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  96%|█████████▌| 522/543 [1:54:54<05:27, 15.60s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  98%|█████████▊| 530/543 [1:56:39<03:26, 15.85s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▊| 535/543 [1:57:39<01:59, 14.95s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▉| 539/543 [1:58:41<01:06, 16.60s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy:  99%|█████████▉| 540/543 [1:59:07<00:58, 19.36s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

🧠 economy: 100%|██████████| 543/543 [1:59:53<00:00, 13.25s/it]

[WARN] JSON parse failed for domain 'economy': No JSON object found in model output

=== Experten-Fact-Check für Domain 'health_social' (n=163) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 health_social:  26%|██▋       | 43/163 [06:54<28:25, 14.21s/it]

[WARN] JSON parse failed for domain 'health_social': No JSON object found in model output

🧠 health_social: 100%|██████████| 163/163 [26:15<00:00,  9.66s/it]

=== Experten-Fact-Check für Domain 'foreign_security' (n=105) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 foreign_security:  78%|███████▊  | 82/105 [12:21<05:10, 13.50s/it]

[WARN] JSON parse failed for domain 'foreign_security': No JSON object found in model output

🧠 foreign_security: 100%|██████████| 105/105 [15:52<00:00,  9.07s/it]

=== Experten-Fact-Check für Domain 'law_rights' (n=141) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 law_rights:  36%|███▌      | 51/141 [08:01<21:37, 14.41s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  44%|████▍     | 62/141 [09:57<18:59, 14.43s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  47%|████▋     | 66/141 [10:56<20:35, 16.47s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights:  57%|█████▋    | 81/141 [13:36<14:30, 14.51s/it]

[WARN] JSON parse failed for domain 'law_rights': No JSON object found in model output

🧠 law_rights: 100%|██████████| 141/141 [22:59<00:00,  9.79s/it]

=== Experten-Fact-Check für Domain 'politics_government' (n=157) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 politics_government:  36%|███▌      | 56/157 [08:03<23:12, 13.78s/it]

[WARN] JSON parse failed for domain 'politics_government': No JSON object found in model output

🧠 politics_government:  77%|███████▋  | 121/157 [17:23<08:17, 13.83s/it]

[WARN] JSON parse failed for domain 'politics_government': No JSON object found in model output

🧠 politics_government: 100%|██████████| 157/157 [22:03<00:00,  8.43s/it]

=== Experten-Fact-Check für Domain 'environment_energy' (n=60) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 environment_energy: 100%|██████████| 60/60 [08:24<00:00,  8.40s/it]

=== Experten-Fact-Check für Domain 'society_culture' (n=66) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 society_culture:   2%|▏         | 1/66 [00:27<30:07, 27.81s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   3%|▎         | 2/66 [00:54<29:00, 27.19s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   5%|▍         | 3/66 [01:20<28:08, 26.80s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   6%|▌         | 4/66 [01:47<27:27, 26.57s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   8%|▊         | 5/66 [02:13<27:00, 26.57s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:   9%|▉         | 6/66 [02:40<26:30, 26.50s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  11%|█         | 7/66 [03:06<26:00, 26.45s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  12%|█▏        | 8/66 [03:32<25:32, 26.41s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  14%|█▎        | 9/66 [03:59<25:03, 26.38s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  15%|█▌        | 10/66 [04:25<24:42, 26.48s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  18%|█▊        | 12/66 [05:09<22:03, 24.52s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  20%|█▉        | 13/66 [05:36<22:16, 25.22s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  21%|██        | 14/66 [06:02<22:12, 25.62s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  23%|██▎       | 15/66 [06:29<21:57, 25.83s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  24%|██▍       | 16/66 [06:56<21:47, 26.14s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  29%|██▉       | 19/66 [07:46<16:29, 21.05s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  30%|███       | 20/66 [08:12<17:23, 22.68s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  32%|███▏      | 21/66 [08:39<17:57, 23.95s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  33%|███▎      | 22/66 [09:06<18:11, 24.80s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  35%|███▍      | 23/66 [09:33<18:11, 25.39s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  36%|███▋      | 24/66 [09:59<17:56, 25.63s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  38%|███▊      | 25/66 [10:25<17:38, 25.82s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  39%|███▉      | 26/66 [10:52<17:18, 25.96s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  44%|████▍     | 29/66 [11:58<14:34, 23.64s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  45%|████▌     | 30/66 [12:25<14:42, 24.50s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  47%|████▋     | 31/66 [12:51<14:33, 24.95s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  48%|████▊     | 32/66 [13:17<14:26, 25.47s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  52%|█████▏    | 34/66 [14:11<13:56, 26.14s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  53%|█████▎    | 35/66 [14:37<13:34, 26.29s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  55%|█████▍    | 36/66 [15:04<13:09, 26.33s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  56%|█████▌    | 37/66 [15:30<12:46, 26.42s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  58%|█████▊    | 38/66 [15:58<12:25, 26.63s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  59%|█████▉    | 39/66 [16:24<12:00, 26.68s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  61%|██████    | 40/66 [16:51<11:30, 26.57s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  64%|██████▎   | 42/66 [17:41<10:20, 25.87s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  65%|██████▌   | 43/66 [18:07<09:58, 26.02s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  67%|██████▋   | 44/66 [18:33<09:35, 26.16s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  68%|██████▊   | 45/66 [19:00<09:13, 26.34s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  73%|███████▎  | 48/66 [20:07<07:17, 24.30s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  74%|███████▍  | 49/66 [20:33<07:02, 24.88s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  76%|███████▌  | 50/66 [21:00<06:44, 25.31s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  77%|███████▋  | 51/66 [21:26<06:23, 25.55s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  79%|███████▉  | 52/66 [21:53<06:02, 25.91s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  82%|████████▏ | 54/66 [22:38<04:56, 24.74s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  83%|████████▎ | 55/66 [23:05<04:37, 25.22s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  85%|████████▍ | 56/66 [23:31<04:15, 25.54s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  86%|████████▋ | 57/66 [23:58<03:52, 25.88s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  88%|████████▊ | 58/66 [24:24<03:28, 26.11s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  89%|████████▉ | 59/66 [24:51<03:03, 26.26s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  91%|█████████ | 60/66 [25:17<02:37, 26.28s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture:  95%|█████████▌| 63/66 [26:23<01:12, 24.20s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

🧠 society_culture: 100%|██████████| 66/66 [27:22<00:00, 24.88s/it]

[WARN] JSON parse failed for domain 'society_culture': No JSON object found in model output

=== Experten-Fact-Check für Domain 'misc' (n=32) ===

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Device set to use cuda:0
🧠 misc:  75%|███████▌  | 24/32 [03:47<01:46, 13.29s/it]

[WARN] JSON parse failed for domain 'misc': No JSON object found in model output

🧠 misc: 100%|██████████| 32/32 [05:02<00:00,  9.47s/it]

Beispiel-Zeilen mit Predictions:
                                           statement   super_domain  \
0  Building a wall on the U.S . Mexico border wil...     law_rights
1  Wisconsin is on pace to double the number of l...        economy
2  Says John McCain has done nothing to help the ...  health_social
3  Suzanne Bonamici supports a plan that will cut...  health_social
4  When asked by a reporter whether hes at the ce...     law_rights

     domain_pred  label verdict_pred
0     law_rights   True         True
1        economy  False         True
2  health_social  False        False
3  health_social   True         True
4        economy  False        False

🌍 Domain-Routing Accuracy: 0.718
Domain-Routing Confusion Matrix (rows=true, cols=pred):
[[403  28   0   5  20   5   7   5]
 [ 13 110   2  12   2   0   4   0]
 [ 11   2  90  11   2   3   2   1]
 [  9  15   5 103   8   1   2   2]
 [ 69   4   5   5 117  11  12  10]
 [ 12   0   1   0   3  38   2   0]
 [ 10   2   2   5   3   0  37   2]
 [ 16   2   0   0   2   2   0  12]]
Domain label order: ['economy', 'health_social', 'foreign_security', 'law_rights', 'politics_government', 'environment_energy', 'society_culture', 'misc']

✅ Verdict Accuracy (gesamt): 0.650

Classification report (True/False):
              precision    recall  f1-score   support

        True       0.69      0.69      0.69       714
       False       0.60      0.60      0.60       553

    accuracy                           0.65      1267
   macro avg       0.64      0.64      0.64      1267
weighted avg       0.65      0.65      0.65      1267

Confusion matrix [rows=true, cols=pred] (True, False):
[[492 222]
 [221 332]]

===== Per-Domain Verdict-Accuracy (nach true super_domain) =====
economy                n= 473 acc=0.655
health_social          n= 143 acc=0.650
foreign_security       n= 122 acc=0.697
law_rights             n= 145 acc=0.641
politics_government    n= 233 acc=0.639
environment_energy     n=  56 acc=0.661
society_culture        n=  61 acc=0.574
misc                   n=  34 acc=0.647

💾 Predictions gespeichert unter:
Results/test_predictions_with_experts_sequential.csv

# old code

In [16]:
import os
import torch
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

os.environ.setdefault("CUDA_VISIBLE_DEVICES", "7")

BASE_MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
EXPERT_ROOT = "adapters/Llama_experts_8Classes"  # da liegen expert_<domain> drin


SUPER_LABELS = [
    "economy",
    "health_social",
    "foreign_security",
    "law_rights",
    "politics_government",
    "environment_energy",
    "society_culture",
    "misc",
]

In [17]:
def build_expert_system_prompt(domain_name: str) -> str:
    return f"""You are a fact-checking expert specialized in the '{domain_name}' domain.

You receive short political or public policy claims (statements) and must decide if they are factually correct.

Answer STRICTLY with one of these two labels:
- True
- False

Do NOT explain. Only output 'True' or 'False'.
"""


def load_expert_model(domain_name: str):
    """
    Lädt Base LLaMA + passenden LoRA-Adapter für die Domain.
    """
    expert_dir = os.path.join(EXPERT_ROOT, f"{domain_name}")
    if not os.path.isdir(expert_dir):
        raise FileNotFoundError(f"Expert directory not found: {expert_dir}")

    # Base-Modell
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto",
    )

    # LoRA-Adapter drauf
    model = PeftModel.from_pretrained(base_model, expert_dir)
    model.eval()

    tokenizer = AutoTokenizer.from_pretrained(expert_dir, use_fast=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    if torch.cuda.is_available():
        model = model.to("cuda")

    return model, tokenizer


def predict_with_expert(statement: str, domain_name: str, model, tokenizer) -> str:
    """
    Nutzt ein geladenes Expertenmodell, um für ein Statement True/False zu predicten.
    """
    system_prompt = build_expert_system_prompt(domain_name)
    user_content = f"Claim:\n{statement}\n\nAnswer:"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_content},
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        padding=True,
    )

    if torch.cuda.is_available():
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        gen = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            pad_token_id=tokenizer.pad_token_id,
            max_new_tokens=4,
            do_sample=False,
        )

    new_tokens = gen[0][inputs["input_ids"].shape[1]:]
    answer = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    # Normalisieren
    first = answer.split()[0].strip().strip(".,:;!?)(").lower() if answer else ""

    if first.startswith("true"):
        return "True"
    if first.startswith("false"):
        return "False"

    # Fallback
    return "False"

In [18]:
test_path = "../own_datasets/test_binary_labels_with_super_domain.csv"

df_test = pd.read_csv(
    test_path,
    sep="\t",
    quotechar='"',
    engine="python",
    dtype=str,
)

# Aufräumen
df_test = df_test.dropna(subset=["statement", "label", "super_domain"])
df_test = df_test[df_test["statement"].str.strip() != ""]
df_test = df_test[df_test["label"].isin(["True", "False"])]

print("Testset size:", len(df_test))
print("Super-Domain-Verteilung (Test):")
print(df_test["super_domain"].value_counts())

Testset size: 1267
Super-Domain-Verteilung (Test):
super_domain
economy                473
politics_government    233
law_rights             145
health_social          143
foreign_security       122
society_culture         61
environment_energy      56
misc                    34
Name: count, dtype: int64

In [19]:
all_results = []
all_rows_with_pred = []  # später für Gesamtauswertung

for domain in SUPER_LABELS:
    df_dom = df_test[df_test["super_domain"] == domain].copy()
    if df_dom.empty:
        print(f"\n⚠️ Domain '{domain}': keine Testbeispiele – wird übersprungen.")
        continue

    print(f"\n===== Evaluating expert for domain: {domain} =====")
    print(f"# Testbeispiele: {len(df_dom)}")
    print("Label-Verteilung (true):")
    print(df_dom["label"].value_counts())

    # Modell laden
    model, tok = load_expert_model(domain)

    preds = []
    for _, row in tqdm(df_dom.iterrows(), total=len(df_dom), desc=f"🧠 {domain}", dynamic_ncols=True):
        statement = row["statement"]
        pred = predict_with_expert(statement, domain, model, tok)
        preds.append(pred)

    df_dom["pred"] = preds
    all_rows_with_pred.append(df_dom)

    y_true = df_dom["label"]
    y_pred = df_dom["pred"]

    acc = accuracy_score(y_true, y_pred)
    print(f"\nAccuracy ({domain}): {acc:.3f}")

    report = classification_report(y_true, y_pred, labels=["True", "False"], zero_division=0)
    print("Classification report:")
    print(report)

    cm = confusion_matrix(y_true, y_pred, labels=["True", "False"])
    print("Confusion matrix [rows=true, cols=pred] (True, False):")
    print(cm)

    all_results.append({
        "domain": domain,
        "n": len(df_dom),
        "accuracy": acc,
    })

    # Speicher freigeben
    del model
    torch.cuda.empty_cache()

===== Evaluating expert for domain: economy =====
# Testbeispiele: 473
Label-Verteilung (true):
label
True     266
False    207
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 economy:   0%|          | 0/473 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
🧠 economy: 100%|██████████| 473/473 [01:28<00:00,  5.35it/s]

Accuracy (economy): 0.670
Classification report:
              precision    recall  f1-score   support

        True       0.70      0.72      0.71       266
       False       0.63      0.61      0.62       207

    accuracy                           0.67       473
   macro avg       0.66      0.66      0.66       473
weighted avg       0.67      0.67      0.67       473

Confusion matrix [rows=true, cols=pred] (True, False):
[[191  75]
 [ 81 126]]

===== Evaluating expert for domain: health_social =====
# Testbeispiele: 143
Label-Verteilung (true):
label
True     82
False    61
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 health_social: 100%|██████████| 143/143 [00:35<00:00,  3.99it/s]

Accuracy (health_social): 0.629
Classification report:
              precision    recall  f1-score   support

        True       0.69      0.63      0.66        82
       False       0.56      0.62      0.59        61

    accuracy                           0.63       143
   macro avg       0.63      0.63      0.63       143
weighted avg       0.64      0.63      0.63       143

Confusion matrix [rows=true, cols=pred] (True, False):
[[52 30]
 [23 38]]

===== Evaluating expert for domain: foreign_security =====
# Testbeispiele: 122
Label-Verteilung (true):
label
True     65
False    57
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 foreign_security: 100%|██████████| 122/122 [00:30<00:00,  3.97it/s]

Accuracy (foreign_security): 0.689
Classification report:
              precision    recall  f1-score   support

        True       0.75      0.62      0.68        65
       False       0.64      0.77      0.70        57

    accuracy                           0.69       122
   macro avg       0.70      0.69      0.69       122
weighted avg       0.70      0.69      0.69       122

Confusion matrix [rows=true, cols=pred] (True, False):
[[40 25]
 [13 44]]

===== Evaluating expert for domain: law_rights =====
# Testbeispiele: 145
Label-Verteilung (true):
label
True     75
False    70
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 law_rights: 100%|██████████| 145/145 [00:22<00:00,  6.41it/s]

Accuracy (law_rights): 0.628
Classification report:
              precision    recall  f1-score   support

        True       0.62      0.73      0.67        75
       False       0.64      0.51      0.57        70

    accuracy                           0.63       145
   macro avg       0.63      0.62      0.62       145
weighted avg       0.63      0.63      0.62       145

Confusion matrix [rows=true, cols=pred] (True, False):
[[55 20]
 [34 36]]

===== Evaluating expert for domain: politics_government =====
# Testbeispiele: 233
Label-Verteilung (true):
label
True     137
False     96
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 politics_government: 100%|██████████| 233/233 [00:58<00:00,  4.00it/s]

Accuracy (politics_government): 0.670
Classification report:
              precision    recall  f1-score   support

        True       0.69      0.80      0.74       137
       False       0.63      0.48      0.54        96

    accuracy                           0.67       233
   macro avg       0.66      0.64      0.64       233
weighted avg       0.66      0.67      0.66       233

Confusion matrix [rows=true, cols=pred] (True, False):
[[110  27]
 [ 50  46]]

===== Evaluating expert for domain: environment_energy =====
# Testbeispiele: 56
Label-Verteilung (true):
label
True     29
False    27
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 environment_energy: 100%|██████████| 56/56 [00:09<00:00,  6.09it/s]

Accuracy (environment_energy): 0.607
Classification report:
              precision    recall  f1-score   support

        True       0.58      0.90      0.70        29
       False       0.73      0.30      0.42        27

    accuracy                           0.61        56
   macro avg       0.65      0.60      0.56        56
weighted avg       0.65      0.61      0.57        56

Confusion matrix [rows=true, cols=pred] (True, False):
[[26  3]
 [19  8]]

===== Evaluating expert for domain: society_culture =====
# Testbeispiele: 61
Label-Verteilung (true):
label
True     37
False    24
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 society_culture: 100%|██████████| 61/61 [00:09<00:00,  6.77it/s]

Accuracy (society_culture): 0.574
Classification report:
              precision    recall  f1-score   support

        True       0.67      0.59      0.63        37
       False       0.46      0.54      0.50        24

    accuracy                           0.57        61
   macro avg       0.57      0.57      0.56        61
weighted avg       0.59      0.57      0.58        61

Confusion matrix [rows=true, cols=pred] (True, False):
[[22 15]
 [11 13]]

===== Evaluating expert for domain: misc =====
# Testbeispiele: 34
Label-Verteilung (true):
label
True     23
False    11
Name: count, dtype: int64

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

🧠 misc: 100%|██████████| 34/34 [00:06<00:00,  5.19it/s]

Accuracy (misc): 0.647
Classification report:
              precision    recall  f1-score   support

        True       0.82      0.61      0.70        23
       False       0.47      0.73      0.57        11

    accuracy                           0.65        34
   macro avg       0.65      0.67      0.64        34
weighted avg       0.71      0.65      0.66        34

Confusion matrix [rows=true, cols=pred] (True, False):
[[14  9]
 [ 3  8]]

In [20]:
df_all_pred = pd.concat(all_rows_with_pred, ignore_index=True)

print("\n===== Gesamt-Performance über alle Domains =====")
y_true_all = df_all_pred["label"]
y_pred_all = df_all_pred["pred"]

acc_all = accuracy_score(y_true_all, y_pred_all)
print(f"Overall accuracy: {acc_all:.3f}")

print("Overall classification report:")
print(classification_report(y_true_all, y_pred_all, labels=["True", "False"], zero_division=0))

print("Overall confusion matrix (True, False):")
print(confusion_matrix(y_true_all, y_pred_all, labels=["True", "False"]))

# Optional: pro Domain Accuracy-Tabelle
print("\nPer-domain accuracy summary:")
for r in all_results:
    print(f"{r['domain']:20s}  n={r['n']:4d}  acc={r['accuracy']:.3f}")

===== Gesamt-Performance über alle Domains =====
Overall accuracy: 0.654
Overall classification report:
              precision    recall  f1-score   support

        True       0.69      0.71      0.70       714
       False       0.61      0.58      0.59       553

    accuracy                           0.65      1267
   macro avg       0.65      0.65      0.65      1267
weighted avg       0.65      0.65      0.65      1267

Overall confusion matrix (True, False):
[[510 204]
 [234 319]]

Per-domain accuracy summary:
economy               n= 473  acc=0.670
health_social         n= 143  acc=0.629
foreign_security      n= 122  acc=0.689
law_rights            n= 145  acc=0.628
politics_government   n= 233  acc=0.670
environment_energy    n=  56  acc=0.607
society_culture       n=  61  acc=0.574
misc                  n=  34  acc=0.647

# Chat-Template

In [2]:
from transformers import AutoTokenizer

for mid in [
    "meta-llama/Llama-3.1-8B-Instruct",
    "google/gemma-7b-it",
    "deepseek-ai/deepseek-llm-7b-base",
]:
    tok = AutoTokenizer.from_pretrained(mid, trust_remote_code=True)
    has_chat = hasattr(tok, "apply_chat_template") and bool(getattr(tok, "chat_template", None))
    print(mid, "has_chat=", has_chat, "chat_template_present=", bool(getattr(tok, "chat_template", None)))
    if has_chat:
        print("template snippet:", tok.chat_template[:200], "...\n")

meta-llama/Llama-3.1-8B-Instruct has_chat= True chat_template_present= True
template snippet: {{- bos_token }}
{%- if custom_tools is defined %}
    {%- set tools = custom_tools %}
{%- endif %}
{%- if not tools_in_user_message is defined %}
    {%- set tools_in_user_message = true %}
{%- endif ...

google/gemma-7b-it has_chat= True chat_template_present= True
template snippet: {{ bos_token }}{% if messages[0]['role'] == 'system' %}{{ raise_exception('System role not supported') }}{% endif %}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 = ...

deepseek-ai/deepseek-llm-7b-base has_chat= False chat_template_present= False